### ISSUE TITLE
ZMap exits with SIGPIPE when running non-interactively via SSH

### ISSUE THREAD

**Issue by hmoore-r7** [zmap/zmap#211]
Running a command line like ```ssh root@host 'zmap ...'``` ends up triggering a SIGPIPE in one of its threads. We are only seeing this behavior with UDP templates, likely due to the low speed of output (180k pps vs 350k+pps). Running ssh with -t, from screen, or using stdout/stderr redirection appears to resolve the issue. I will try to add the relevant strace() output and list the full command-line arguments in a followup comment, but wanted to list the workaround in case other folks are running into the same.

**Comment by zakird** [comment]
@hmoore-r7 does this still occur? working to clean up some issues. would like to get this fixed up if still an issue.

**Comment by hmoore-r7** [comment]
We worked around by keeping the session open, so I have not been able to test lately. Let me give master a shot in a few minutes.

**Comment by hmoore-r7** [comment]
I can't reproduce this by running zmap over a pty-less ssh socket anymore.

**Comment by zakird** [comment]
I'm going to close if no longer seems to be an issue. If comes, back, we can reopen.
