### ISSUE TITLE
New probe? Quote of the Day protocol

### ISSUE THREAD

**Issue by denniskai1234** [zmap/zmap#212]
Hello.

How can i add a new probe for QOTD? From where do i get the request for it?

Hope you can help me out, thanks!

**Comment by zakird** [comment]
This issue has been open for more than a year now. The reality is no core committer has the time to implement this feature and I don't see much reason to keep this issue open. If the requester wants to submit a pull request, we'll be happy to accept.

**Comment by jhart-r7** [comment]
FWIW, I think the more correct way of probing for qotd is to use the `-M udp --probe-args=text: -p 17` argument to send an empty probe instead.  Similarly for most other UDP services that respond to any UDP connection with or without data in the payload.
