### ISSUE TITLE
zmap can not run in openVZ container

### ISSUE THREAD

**Issue by zakird** [zmap/zmap#215]
ZMap does not currently operate in an OpenVZ Linux container.

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:192.168.163.33  P-t-P:192.168.163.33  Bcast:192.168.163.33  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1

**Comment by zakird** [comment]
This should be fixed by the changes present in vpn-great-again, which allows doing ZMap scans at the IP layer instead of just Ethernet layer. Given no person attached to this issue to verify, I'm closing.

**Comment by etmatrix** [comment]
Is there an option in zmap for send packet at the IP layer? In source code there is an error with --vpn, but --vpn doesn't exist as argument.
I'm analyzing the source...

**Comment by dadrian** [comment]
We removed `--vpn` because it did not work.
