### ISSUE TITLE
Add support for dynamic blacklist

### ISSUE THREAD

**Issue by p-l-** [zmap/zmap#218]
It would be nice to have the ability to hosts or network to the blacklist while the scan is running.

This would help when an administrator asks to have its network(s) blacklisted and the scan is still running.

**Comment by d33tah** [comment]
@dadrian @zakird 

Hello! I have a quick question regarding this issue. Does that mean that if I e.g. get an abuse report from a host, there's currently no way to prevent sending further packets to them without re-starting the server? I explored the problem to a degree and realized that given that zmap uses raw sockets, it's not easy to do this sort of filtering at a different layer.
