### ISSUE TITLE
Output randomly gets colored blue

### ISSUE THREAD

**Issue by dadrian** [zmap/zmap#225]
![screen shot 2014-12-14 at 11 08 38 pm](https://cloud.githubusercontent.com/assets/1158264/5430771/29bee38e-83e6-11e4-9cf6-064547848e99.png)

**Comment by dadrian** [comment]
Fixed.

**Comment by dadrian** [comment]
@zakird was able to reproduce this bug

**Comment by zakird** [comment]
cannot reproduce. looks fixed.
