### ISSUE TITLE
inaccurate ntp scan when multiple CDIR ranges

### ISSUE THREAD

**Issue by sunomie** [zmap/zmap#228]
Hey guys.  When I scan one CDIR range that I know has ntp exposed, I find the exposed ntp.  However, when I combine a bunch of CIDR ranges into one scan, I suddenly do not find any ntp exposed (including the range that previously found ntp when scanning separately).  I'm working around this by looping through the ranges, but this obviously loses some of the benefits offered by zmap.  I have tried rate limiting and increasing the cooldown time, but see the same results.  Sorry I don't know more about the cause of this.

**Comment by amirian28** [comment]
@sunomie In the NTP module, print packet was not implemented, hence why you did not see any packets being generated with --dryrun. Print packet has now been implemented for NTP on master. 

Could you specify what specific command you were using to expose the multiple CIDR block bug?

**Comment by sunomie** [comment]
Here are the two exact commands that I had run.  (My zmap is compiled with redis support installed.)  Unfortunately I cannot retest the IPs since we removed all the ntp that we found exposed :(

sudo zmap --source-port=40000-50000 -i eth0 -g --sender-threads=100 -p 123 --probe-module=ntp --output-module=csvredis --output-file=ntp_scan.csv [list of CDIR ips redacted]

sudo zmap --source-port=40000-50000 -i eth0 -g --sender-threads=100 -p 123 --probe-module=udp --output-module=csvredis --output-file=ntp_scan.csv [list of CDIR ips redacted]

**Comment by amirian28** [comment]
@sunomie, testing locally using a similar command with multiple CIDR ranges and capturing the output with tcpdump, I can see packets going to all of the hosts and I correctly receive output. Can you test again with a rate limited ZMap using the -r flag (e.g. `-r 1000`)? By default ZMap runs as fast as the CPU and network card allow, which can overload many networks quickly.

**Comment by dadrian** [comment]
@sunomie, since we haven't heard back, I'm going to go ahead and close this issue. Feel free to reopen if you are still experiencing this behavior with a rate-limited ZMap in the stable branch.
