### ISSUE TITLE
No output - am I doing it wrong?

### ISSUE THREAD

**Issue by whithajess** [zmap/zmap#229]
Ok so this is probably user error but im getting no output from a scan of our network

`sudo zmap -p 80 -o myresults.csv 192.168.0.0/24 -v 5 --summary -f saddr -i eth0 -G 54:e0:32:a3:7d:d4`

I have commented out 
`#192.168.0.0/16      # RFC1918: Private-Use`
from `/etc/zmap/blacklist.conf`

which looking at the below output seems fine at least in terms of blacklisting

I know there are open ports (3) and hosts (15) which I can find with nmap -p 80 192.168.0.0/24

an 07 16:07:47.187 [TRACE] zmap: zmap main thread started
Jan 07 16:07:47.187 [TRACE] zmap: requested ouput-module: default
Jan 07 16:07:47.187 [DEBUG] zmap: no output module provided. will use csv.
Jan 07 16:07:47.187 [DEBUG] zmap: requested output field (0): saddr
Jan 07 16:07:47.187 [WARN] blacklist: ZMap is currently using the default blacklist located at /etc/zmap/blacklist.conf. By default, this blacklist excludes locally scoped networks (e.g. 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blacklist by editing the default ZMap configuration at /etc/zmap/zmap.conf.
Jan 07 16:07:47.187 [INFO] zmap: started
Jan 07 16:07:47.187 [DEBUG] zmap: no source IP address given. will use default address: 192.168.0.10.
Jan 07 16:07:47.187 [INFO] zmap: zmap selected output module: csv
Jan 07 16:07:47.187 [DEBUG] csv: more than one field, will add headers
Jan 07 16:07:47.187 [TRACE] constraint: Initializing
Jan 07 16:07:47.187 [TRACE] whitelist: blacklisting 0.0.0.0/0
Jan 07 16:07:47.187 [TRACE] whitelisting: whitelisting 192.168.0.0/24
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 0.0.0.0/8
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 10.0.0.0/8
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 100.64.0.0/10
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 127.0.0.0/8
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 169.254.0.0/16
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 172.16.0.0/12
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 192.0.0.0/24
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 192.0.2.0/24
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 192.88.99.0/24
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 198.18.0.0/15
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 198.51.100.0/24
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 203.0.113.0/24
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 240.0.0.0/4
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 255.255.255.255/32
Jan 07 16:07:47.187 [TRACE] blacklisting: blacklisting 224.0.0.0/4
Jan 07 16:07:47.187 [TRACE] constraint: Painting value 1
Jan 07 16:07:47.191 [DEBUG] constraint: 0 IPs in radix array, 256 IPs in tree
Jan 07 16:07:47.191 [DEBUG] blacklist: 256 addresses allowed to be scanned (0% of address space)
Jan 07 16:07:47.191 [DEBUG] cyclic: using prime 65537, known_primroot 3
Jan 07 16:07:47.191 [DEBUG] cyclic: primitive root: 30415
Jan 07 16:07:47.191 [DEBUG] cyclic: starting point: 950573577
Jan 07 16:07:47.191 [DEBUG] send: will send from 1 address on 28233 source ports
Jan 07 16:07:47.191 [TRACE] zmap: set thread 2460899072 affinity to core 0
Jan 07 16:07:47.191 [DEBUG] recv: thread started
Jan 07 16:07:47.191 [DEBUG] recv: using dev eth0
Jan 07 16:07:47.221 [DEBUG] recv: receiver ready
Jan 07 16:07:47.221 [DEBUG] recv: duplicate responses will be excluded from output
Jan 07 16:07:47.221 [DEBUG] recv: unsuccessful responses will be excluded from output
Jan 07 16:07:47.221 [DEBUG] zmap: using 1 sender threads
Jan 07 16:07:47.222 [TRACE] zmap: set thread 2450409216 affinity to core 1
Jan 07 16:07:47.222 [DEBUG] send: thread started
Jan 07 16:07:47.222 [TRACE] zmap: set thread 2442016512 affinity to core 2
Jan 07 16:07:47.223 [DEBUG] send: thread finished
Jan 07 16:07:47.223 [DEBUG] zmap: senders finished
 0:01 13%; send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:02 25%; send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:03 38%; send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:04 50%; send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:05 63% (3s left); send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:06 75% (1s left); send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:07 88% (0s left); send: 256 done (8.10 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%

**Comment by whithajess** [comment]
I added -i -G after looking at #168 but this didn't seem to help

**Comment by dadrian** [comment]
Your command itself looks fine.

I see you're scanning 192.168.0.0/24, if you're on a home network you are most likely sending out packets too fast for the router to keep up. Try rate limiting to 100 packets per second (`-r 100`) and see if you get responses.

**Comment by whithajess** [comment]
Hi @dadrian thanks for your help but I gave that a go too and no luck. I also realised that I had got 1.1.0-1 when I installed zmap so I have subsequently updated to zmap 2.0.0-RC1 here is the changed command output (chucked it in a gist as long) https://gist.github.com/whithajess/b30fc360d5de37fcdc62

**Comment by dadrian** [comment]
Does zmap work if you scan a remote IP?

There's an unfortunate bug as a side effect of how zmap was architected where on certain local networks, ZMap is unable to scan local hosts since it addresses packets directly to the gateway rather than the host itself, and the gateway isn't won't always forward packets back into the local network. This is tracked by #88.

**Comment by whithajess** [comment]
Yeah it does, thanks for your help! I was really just trying to get a baseline as this is my first time playing around with this. #88 is the cause
