### ISSUE TITLE
14.04 zmap package in Ubuntu still on version 1.1.0-1

### ISSUE THREAD

**Issue by whithajess** [zmap/zmap#231]
Read documentation and assumed I was getting 1.2.1 when installing the package but ended up with 1.1.0-1 checked https://launchpad.net/ubuntu/+source/zmap and it seems that 1.2.1 is only 14.10 onwards

**Comment by dadrian** [comment]
I'm not sure we can actually fix this. Unfortunately, Ubuntu will only pull in new point releases of packages on new Ubuntu releases, and when we submitted 1.2 to the Debian repository (upstream of Ubuntu), it didn't percolate down in time for the release of 14.04.

**Comment by whithajess** [comment]
Ah that actually explains a lot! Thanks for the info. May pay to make a note in the install documentation but up to you.
