### ISSUE TITLE
[Questions] How would I go about checking http responses to a simple get?

### ISSUE THREAD

**Issue by whithajess** [zmap/zmap#233]
Hi There,

I am doing some security research around Rails websites and would like to basically make a simple http request for a specific URL path, and do this against all hosts found by zmap with port 80 open. This would need to record the saddr if the http response status comes back with a 200.

Is this something I can do with zmap? Do I need to use some kind of extension? Are there any good references I can use for figuring out how to do this?

Thanks in advance for any help you may be able to provide.

**Comment by dadrian** [comment]
Probably something along the lines of

```
zmap -p 80 -o - -r 100000 | ztee --output-file zmap.out.csv | zgrab --port 80 --data /path/to/file/with/http/get --output-file zgrab.out.json
```
Then just parse with grep or jq (or both)!
 ```
cat zgrab.out.json | grep '200 OK' | jq -c '.host' > hosts.txt
```

A couple of things to note:
1. `-o -` outputs to stdout, it will just print IP addresses by default
2. `-r 100000` sets your rate in packets per second. This is usually what we use when on a gigabit connection, you may want slower
3. Depending on which repository you got ztee from (zmap or ztee), the flags are different. We rewrote the whole thing in C recently.
4. Right now I think `--data` might result in base64 output for the response data. It didn't used to, I've been meaning to come up with a flag to fix this (where the output is just the response as a string).

Unfortunately, our documentation on this is horrendous right now. @amirian28 started working on a new version of the website a while back, but it got mothballed and zgrab kept changing. We will hopefully update our website with documentation on how to do things like this in the near future.

**Comment by whithajess** [comment]
Ah cool so I am kind of on the right track I have tried something similar:

    zmap -p 80 --output-fields=* 23.226.228.12 | ./zgrab --port 80 --data=./my-req --output-file=banners.json

Just testing vs one host that I own. but zgrab comes back with an error

    [ERROR] banner-grab: Conversation error with remote host 23.226.228.12:80: read tcp 23.226.228.12:80: i/o timeout
    
   my-req is as follows:

    GET /rails/info/properties HTTP/1.1
    Host: %s

**Comment by whithajess** [comment]
I added a blank line to the bottom of my my-req file when i noticed that the http-req file from zgrab had one and this fixed the above error!

**Comment by dadrian** [comment]
@whithajess, the connection issue is actually an artifact of HTTP, which ends requests with a double `\r\n\r\n`.
