### ISSUE TITLE
the sum of multiple Zmap processes cpu usage is 100%

### ISSUE THREAD

**Issue by Ivan-Zhu** [zmap/zmap#234]
hi, folks.
As you known, Zmap only support scan one port in a process. So I want to scan multiple ports with multi-processes, in order to utilize multiple core of the server. But I find the sum of the multiple-process cupusage is 100%, I thought it was ought to 100%*n (n: the number of the core). if anyone can help me to explain it and how to work around it, it will  be appreciated.

**Comment by dadrian** [comment]
Most likely each ZMap instance is bound to the same core. Unless you're running the 2.0.0 release candidate or newer, ZMap has no way to specify which core to use, and automatically starts using core 0,1,2...etc.

In newer version of ZMap you can specify which cores to bind to using the --cores flag, e.g. `--cores=0,2,4,6`. You can view information about your server's cores by viewing `/proc/cpuinfo`.

**Comment by Ivan-Zhu** [comment]
hi, dadrian, thanks for your reply. Could you explain more why these ZMap instances is bound to the same core, not like other program processes disperse over all the cores?

**Comment by dadrian** [comment]
ZMap explicitly binds to a core for performance reasons, resulting in a thread that executes only on that core for performance reasons, rather than having the operating system bounce the ZMap thread between cores. We by default bind to core 0, then core 1, etc.

**Comment by Lucifer1993** [comment]
Hi, dadrian, why do i try --cores=0 on the first process, and --cores=1 on the second.but the cpu cores still pin to one of them,however,it shows random.how can I do??plz tell me how to deal with?

**Comment by dadrian** [comment]
ZMap uses three threads internally, so you should pass at least 3 unique cores to each ZMap instance. Also, running two instances at the same time will likely overload libpcap, and it might not be able to keep up with the receive traffic.
