### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Nazimbuet** [zmap/zmap#238]
Hello:

I was compiling the source files but got the following error after executing the make command:

nazim@nazim-Precision-T3600 ~/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1 $ make
[  2%] Building C object src/CMakeFiles/zmap.dir/recv.c.o
In file included from /usr/include/pcap/pcap.h:51:0,
                 from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:
/usr/include/pcap/bpf.h:107:8: error: redefinition of ‘struct bpf_program’
In file included from /usr/local/include/pcap.h:48:0,
                 from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:
/usr/local/include/pcap-bpf.h:84:8: note: originally defined here
In file included from /usr/include/pcap/pcap.h:51:0,
                 from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:
/usr/include/pcap/bpf.h:1259:8: error: redefinition of ‘struct bpf_insn’
In file included from /usr/local/include/pcap.h:48:0,
                 from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:
/usr/local/include/pcap-bpf.h:86:9: note: originally defined here
In file included from /usr/include/pcap/pcap.h:51:0,
                 from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:
/usr/include/pcap/bpf.h:1273:12: error: conflicting types for ‘bpf_validate’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:222:5: note: previous declaration of ‘bpf_validate’ was here
In file included from /usr/include/pcap/pcap.h:51:0,
                 from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:
/usr/include/pcap/bpf.h:1274:14: error: conflicting types for ‘bpf_filter’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:221:7: note: previous declaration of ‘bpf_filter’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:123:8: error: redefinition of ‘struct pcap_file_header’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:110:8: note: originally defined here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:161:8: error: redefinition of ‘struct pcap_pkthdr’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:125:8: note: originally defined here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:170:8: error: redefinition of ‘struct pcap_stat’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:134:8: note: originally defined here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:215:8: error: redefinition of ‘struct pcap_if’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:73:16: note: originally defined here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:228:8: error: redefinition of ‘struct pcap_addr’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:74:16: note: originally defined here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:236:16: error: conflicting types for ‘pcap_handler’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:167:16: note: previous declaration of ‘pcap_handler’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:351:5: error: conflicting types for ‘pcap_loop’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:176:5: note: previous declaration of ‘pcap_loop’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:352:5: error: conflicting types for ‘pcap_dispatch’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:177:5: note: previous declaration of ‘pcap_dispatch’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:354:2: error: conflicting types for ‘pcap_next’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:179:2: note: previous declaration of ‘pcap_next’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:355:6: error: conflicting types for ‘pcap_next_ex’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:180:6: note: previous declaration of ‘pcap_next_ex’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:357:5: error: conflicting types for ‘pcap_stats’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:182:5: note: previous declaration of ‘pcap_stats’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:358:5: error: conflicting types for ‘pcap_setfilter’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:183:5: note: previous declaration of ‘pcap_setfilter’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:365:13: error: conflicting types for ‘pcap_strerror’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:187:7: note: previous declaration of ‘pcap_strerror’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:368:5: error: conflicting types for ‘pcap_compile’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:189:5: note: previous declaration of ‘pcap_compile’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:370:5: error: conflicting types for ‘pcap_compile_nopcap’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:191:5: note: previous declaration of ‘pcap_compile_nopcap’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:372:6: error: conflicting types for ‘pcap_freecode’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:193:6: note: previous declaration of ‘pcap_freecode’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:398:6: error: conflicting types for ‘pcap_dump’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:212:6: note: previous declaration of ‘pcap_dump’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:413:7: error: conflicting types for ‘bpf_filter’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:221:7: note: previous declaration of ‘bpf_filter’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:415:5: error: conflicting types for ‘bpf_validate’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:222:5: note: previous declaration of ‘bpf_validate’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:416:7: error: conflicting types for ‘bpf_image’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:223:7: note: previous declaration of ‘bpf_image’ was here
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:17:0:
/usr/include/pcap/pcap.h:417:6: error: conflicting types for ‘bpf_dump’
In file included from /home/nazim/Desktop/Dropbox/Network_Research/ExploreNet/Software/zmap-1.2.1/src/recv.c:16:0:
/usr/local/include/pcap.h:224:6: note: previous declaration of ‘bpf_dump’ was here
make[2]: *** [src/CMakeFiles/zmap.dir/recv.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2

Please tell me what is going wrong here.

Thanks,
Nazim

**Comment by dadrian** [comment]
What platform are you building on?

**Comment by Nazimbuet** [comment]
Linux mint

**Comment by dadrian** [comment]
This looks like an error in libpcap. Do you have the latest libpcap-dev package installed? Is it possible you have more than one version of libpcap on your system?

**Comment by Nazimbuet** [comment]
I think my system doesn't allow more than one version of libpcap. The compilation was complaining about redefinition. I just comment out one inclusion in recv.c file:
//#include <pcap.h>
#include <pcap/pcap.h>

Now make is working fine and I can run zMap. But I am wondering, can it cause(not including both files) any issue.

Thanks,
Nazim

**Comment by dadrian** [comment]
If it compiles, you should be fine.

**Comment by dadrian** [comment]
Since ZMap is compiling on this system now, I'm going to close this issue. Feel free to reopen if there are still issues.
