### ISSUE TITLE
make forge_socket error

### ISSUE THREAD

**Issue by forzxc** [zmap/zmap#255]
when I make forge_socket module, errors pop up
[root@bigdata forge-socket]# make
cc -I../../lib/ -I/lib/modules/forge_socket -Wall -g -O2 -fstack-protector-all -                                            -param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPI                                            C  -lpcap -levent -levent_extra -lm -Wl,-Bsymbolic-functions -Wl,-z,relro,-z,now                                              forge-socket.c   -o forge-socket
/tmp/cckp267K.o: In function `print_status':
/home/zmap/examples/forge-socket/forge-socket.c:70: undefined reference to `even                                            t_new'
/home/zmap/examples/forge-socket/forge-socket.c:74: undefined reference to `log_                                            info'
/tmp/cckp267K.o: In function `main':
/home/zmap/examples/forge-socket/forge-socket.c:393: undefined reference to `log                                            _init'
/home/zmap/examples/forge-socket/forge-socket.c:406: undefined reference to `buf                                            ferevent_socket_new'
/home/zmap/examples/forge-socket/forge-socket.c:411: undefined reference to `eve                                            nt_new'
/home/zmap/examples/forge-socket/forge-socket.c:484: undefined reference to `log                                            _info'
/home/zmap/examples/forge-socket/forge-socket.c:442: undefined reference to `log                                            _init'
/home/zmap/examples/forge-socket/forge-socket.c:489: undefined reference to `log                                            _info'
/home/zmap/examples/forge-socket/forge-socket.c:397: undefined reference to `log                                            _fatal'
/home/zmap/examples/forge-socket/forge-socket.c:460: undefined reference to `log                                            _error'
/home/zmap/examples/forge-socket/forge-socket.c:473: undefined reference to `log                                            _fatal'
/home/zmap/examples/forge-socket/forge-socket.c:470: undefined reference to `log                                            _fatal'
/home/zmap/examples/forge-socket/forge-socket.c:453: undefined reference to `log                                            _fatal'
/tmp/cckp267K.o: In function `stdin_eventcb':
/home/zmap/examples/forge-socket/forge-socket.c:317: undefined reference to `log                                            _debug'
/home/zmap/examples/forge-socket/forge-socket.c:321: undefined reference to `log                                            _info'
/tmp/cckp267K.o: In function `decrement_cur_running':
/home/zmap/examples/forge-socket/forge-socket.c:85: undefined reference to `log_                                            debug'
/home/zmap/examples/forge-socket/forge-socket.c:87: undefined reference to `buff                                            erevent_get_input'
/home/zmap/examples/forge-socket/forge-socket.c:87: undefined reference to `evbu                                            ffer_get_length'
/home/zmap/examples/forge-socket/forge-socket.c:94: undefined reference to `log_                                            info'
/tmp/cckp267K.o: In function `grab_banner':
/home/zmap/examples/forge-socket/forge-socket.c:287: undefined reference to `buf                                            ferevent_socket_new'
/home/zmap/examples/forge-socket/forge-socket.c:289: undefined reference to `buf                                            ferevent_set_timeouts'
/home/zmap/examples/forge-socket/forge-socket.c:297: undefined reference to `buf                                            ferevent_get_output'
/home/zmap/examples/forge-socket/forge-socket.c:303: undefined reference to `log                                            _trace'
/home/zmap/examples/forge-socket/forge-socket.c:310: undefined reference to `log                                            _trace'
/home/zmap/examples/forge-socket/forge-socket.c:280: undefined reference to `log                                            _error'
/home/zmap/examples/forge-socket/forge-socket.c:255: undefined reference to `log                                            _fatal'
/tmp/cckp267K.o: In function `stdin_readcb':
/home/zmap/examples/forge-socket/forge-socket.c:330: undefined reference to `buf                                            ferevent_get_input'
/home/zmap/examples/forge-socket/forge-socket.c:333: undefined reference to `log                                            _debug'
/home/zmap/examples/forge-socket/forge-socket.c:337: undefined reference to `evb                                            uffer_get_length'
/home/zmap/examples/forge-socket/forge-socket.c:339: undefined reference to `evb                                            uffer_readln'
/home/zmap/examples/forge-socket/forge-socket.c:343: undefined reference to `log                                            _debug'
/home/zmap/examples/forge-socket/forge-socket.c:356: undefined reference to `log                                            _trace'
/tmp/cckp267K.o: In function `read_cb':
/home/zmap/examples/forge-socket/forge-socket.c:134: undefined reference to `buf                                            ferevent_get_input'
/home/zmap/examples/forge-socket/forge-socket.c:136: undefined reference to `evb                                            uffer_get_length'
/home/zmap/examples/forge-socket/forge-socket.c:140: undefined reference to `log                                            _debug'
/home/zmap/examples/forge-socket/forge-socket.c:154: undefined reference to `log                                            _fatal'
/tmp/cckp267K.o: In function `event_cb':
/home/zmap/examples/forge-socket/forge-socket.c:120: undefined reference to `log                                            _debug'
/home/zmap/examples/forge-socket/forge-socket.c:108: undefined reference to `log                                            _error'
collect2: ld  return 1
make: *** [forge-socket]  error 1

what's wrong give me some suggest please. thanks

**Comment by dadrian** [comment]
Forge socket needs to be linked against `logger.o`, this is fixed in the current master build.
