### ISSUE TITLE
Whitelist doesn't work?

### ISSUE THREAD

**Issue by rmathus4** [zmap/zmap#256]
I am running the following in a bash file:

#!/bin/bash
zmap -p3389 --whitelist-file=addresses -o rdp.txt

The "addresses" file has the data in CIDR format, for example 1.2.3.4/16 (one on each line).  When I run the scan, it doesn't scan all of the IP addresses and doesn't output a known IP address that has port 3389 open.  I can confirm this when telnet'ing from the server the zmap scan is run on to the affected server.

**Comment by dadrian** [comment]
Can you:

1. Ensure the correct network is being used (`-i` option)
2. Ensure the correct gateway MAC address is detected (`-G` option)
3. Rate limit ZMap to something that your uplink/adapter supports (`-r` option)
4. Ensure nothing is blocking scan traffic upstream.

If all of those look fine, what version of ZMap are you running?

**Comment by rmathus4** [comment]
Version 1.2.1.  I think the -r did it.  I added that and it went much slower this time (which means it actually did the scanning).  I also found the IP address I know was open to RDP and we're good.  Thanks for the explanation though.  It helps a lot!
