### ISSUE TITLE
Zmap not working

### ISSUE THREAD

**Issue by Sandman02** [zmap/zmap#258]
Hi everybody,

I have problems getting Zmap starting. I have Mac OS X 10.10.3 and tried to install it with the built-in package and also tried building it from source code, but always get "-bash: zmap: command not found".

Using the built-in package:
I downloaded the latest version map-1.2.1 and installed it with "brew install zmap". If I type now this again the terminal says "zmap-1.2.1 already installed". From the downloaded folder I try to start Zmap by typing (from the documentation) "zmap -B 10M -p 80 -n 10000 -o results.csv". As result I get:
"-bash: zmap: command not found"
I read in this post (https://github.com/zmap/zmap/issues/214) that zmap is installed to /usr/local/sbin. I tried the same command from that path and got the same result (command not found...). Also tried it with sumo zmap ... to ensure being the root, but was also not working.

Source code:
I installed cmake, gmp, gengetopt, json, byacc, libnet by typing:
"brew install cmake gmp gengetopt json-c byacc libdnet" also tried "sudo port install gmp libdnet byacc flex gengetopt cmake".
It says cmake, gmp, gengetopt, json, byacc, libnet is already installed. 
Then I typed "cmake -DENABLE_DEVELOPMENT=OFF"
There with several files I get this warning:

[ 23%] Building C object src/CMakeFiles/zmap.dir/filter.c.o
In file included from /Users/admin/Downloads/zmap-1.2.1/src/filter.c:2:
In file included from /Users/admin/Downloads/zmap-1.2.1/src/state.h:12:
In file included from /Users/admin/Downloads/zmap-1.2.1/src/../lib/includes.h:2:
In file included from /opt/local/include/dnet.h:15:
/opt/local/include/dnet/ip.h:349:4: warning: 'opt_data' may not be nested in a
      struct due to flexible array member [-Wflexible-array-extensions]
        } opt_data;
          ^

Then I type "sudo make install" and get:

[100%] Built target zmap
Install the project...
-- Install configuration: ""
-- Up-to-date: /etc/zmap/blacklist.conf
-- Up-to-date: /etc/zmap/zmap.conf
-- Installing: /usr/local/sbin/zmap
-- Up-to-date: /usr/local/share/man/man1/zmap.1

Trying to start Zmap I again got: "-bash: zmap: command not found"

If I type "ls" in the terminal it says that there is a file called zmap in /usr/local/bin. In the folder directory this zmap file does not appear. I don´t know if this is normal or strange. 

Has anybody an idea why it is not working? What can I do?

I would very appreciate any advice! 

I was also reading the post below, but also didn´t help me.
https://github.com/zmap/zmap/issues/185

**Comment by dadrian** [comment]
What is the output of `echo $PATH` and does it contain /usr/local/sbin?

**Comment by Sandman02** [comment]
Hi dadrian, thanks very much for your answer. The path variable was indeed the problem, just realized one hour ago what you meant by path in post 185. I am not very experienced working with terminal... but now its working, thanks again!

**Comment by Sandman02** [comment]
The path variable was indeed the problem. I fixed it and its working now. Thanks very much for your response!

**Comment by BBerastegui** [comment]
For future reference. You can modify the $PATH variable to launch zmap:

```
PATH=$PATH:/usr/local/sbin zmap
```

Or add this line to your .bash_profile:

```
export PATH=$PATH:/usr/local/sbin
```

**Comment by abdullahcicekli** [comment]
Thanks for answer :)
