### ISSUE TITLE
ztee fails in CSV mode with "Error writing to stdout"

### ISSUE THREAD

**Issue by billmarczak** [zmap/zmap#259]
I believe the issue is here: https://github.com/zmap/zmap/blob/master/src/ztee.c#L349.  Note that print_from_csv sets stdout_ret to 0 on the first line (field names), and will also set it to 0 for a zmap line where success = 0, if "--success-only" is set.

Perhaps "<= 0" should be "< 0", as "== 0" is not an error condition of fprintf as per the man page.

**Comment by dadrian** [comment]
Thanks for the report. I believe it's fixed, let me know if you have any issues.
