### ISSUE TITLE
Failed to send packets

### ISSUE THREAD

**Issue by Nazimbuet** [zmap/zmap#260]
I have installed zMap in PlanetLab nodes(https://planet-lab.org) but it is not working properly. Can you please suggest me what is going wrong?

bash-3.2# /usr/local/sbin/zmap --probes=3 --bandwidth=1K --probe-module=icmp_echoscan -o test.dat 64.75.214.0/24
May 27 20:40:02.697 [INFO] zmap: output module: csv
May 27 20:40:03.715 [WARN] monitor: Failed to send 767 packets/sec (768 total failures)
 0:01 13%; send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:02 25%; send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:03 38%; send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:04 50%; send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:05 63% (4s left); send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:06 75% (3s left); send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:07 87% (2s left); send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:08 100% (1s left); send: 256 done (9.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
May 27 20:40:11.716 [INFO] zmap: completed

**Comment by zakird** [comment]
can you post with -v5 logging?

**Comment by zakird** [comment]
(whoops sorry didn't mean to close)

**Comment by Nazimbuet** [comment]
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.73. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.223. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.223. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.223. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.170. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.170. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: send_packet failed for 64.75.214.170. Operation not permitted
May 27 23:46:11.744 [DEBUG] send: thread 1 finished
May 27 23:46:11.744 [DEBUG] zmap: senders finished
May 27 23:46:12.698 [WARN] monitor: Failed to send 767 packets/sec (768 total failures)
 0:01 12%; send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:02 25%; send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:03 37%; send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:04 50%; send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:05 62% (4s left); send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:06 75% (3s left); send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:07 87% (2s left); send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:08 99% (1s left); send: 256 done (4.87 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
May 27 23:46:19.747 [DEBUG] recv: thread finished
May 27 23:46:20.700 [INFO] zmap: completed

It is showing operations not permitted. I am running zmap as a super user (following 'su' command)

**Comment by Nazimbuet** [comment]
Please give me the update....

**Comment by zakird** [comment]
Planet Lab doesn't look to support raw sockets. See
https://www.planet-lab.org/raw_sockets/api_socket.html. If you can verify
that you can send ethernet packets, then feel free to re-open, but this
doesn't look like it has anything to do with ZMap, but rather your system
configuration.
