### ISSUE TITLE
does install overwrite blacklist.conf?

### ISSUE THREAD

**Issue by zakird** [zmap/zmap#261]
There is a rumor that our install process currently overwrites your current blacklist with the default ZMap blacklist. We need to check whether this happens and correct if it is the case.

**Comment by dadrian** [comment]
I believe it does. We'll likely have to write some CMake script to do the install properly, using the `install(SCRIPT` CMake directive.

**Comment by zakird** [comment]
closed by cfd840ac9058289492d0e174d477fdc333dc2ebe
