### ISSUE TITLE
parser.h: file not found

### ISSUE THREAD

**Issue by levin-kelevra** [zmap/zmap#271]
make
[ 20%] Built target zmaplib
[ 26%] Built target zblacklist
[ 28%] Generating parser.c
[ 30%] Generating zopt.h
[ 32%] Generating lexer.c
Scanning dependencies of target zmap
[ 33%] Building C object src/CMakeFiles/zmap.dir/aesrand.c.o
[ 35%] Building C object src/CMakeFiles/zmap.dir/cyclic.c.o
[ 37%] Building C object src/CMakeFiles/zmap.dir/expression.c.o
[ 39%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
[ 41%] Building C object src/CMakeFiles/zmap.dir/filter.c.o
zmap/src/filter.c:12:20: fatal error: parser.h: file not found
 #include "parser.h"
                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/zmap.dir/filter.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2

**Comment by dadrian** [comment]
`parser.h` should be generated at the same time as parser.c, but apparently was not.

What operating system is this and and what version of byacc do you have installed?

**Comment by zakird** [comment]
@levin-kelevra I'm going to close this issue due to lack of response. Please free to reopen as needed.

**Comment by levin-kelevra** [comment]
dadrian,
OS Ubuntu 14.04 x64
byacc - 1.9 20140101
cmake version 2.8.12.2
