### ISSUE TITLE
-g option not valid any more

### ISSUE THREAD

**Issue by sheharbano** [zmap/zmap#273]
I would like to print scan summary at the end of my scan, but running zmap
with -g option generates the error:

./src/zmap -i eth0 -p 80 -g
./src/zmap: invalid option -- 'g'

./src/zmap -i eth0 -p 80 --summary
./src/zmap: unrecognized option '--summary'

**Comment by zakird** [comment]
You can use metadata file, which contains more comprehensive information.
Summary was deprecated by this function several versions ago.

**Comment by sheharbano** [comment]
> You can use metadata file, which contains more comprehensive information.
> Summary was deprecated by this function several versions ago.


I have ZMap with no JSON support but it seems I'll need to rebuild to get
meta-data.
Thanks for pointing out the meta-file option.

-- 
--Bano
