### ISSUE TITLE
zmap compile problem 

### ISSUE THREAD

**Issue by shadowcorw** [zmap/zmap#276]
I tried to complie zmap, but get the below problem:

sh-3.2# cmake -DENABLE_DEVELOPMENT=ON
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/----/zmap
sh-3.2# make
[  1%] Building C object lib/CMakeFiles/zmaplib.dir/redis.c.o
In file included from /Users/----/zmap/lib/redis.c:9:
/Users/----/zmap/lib/redis.h:3:10: fatal error: 'hiredis/hiredis.h'
      file not found
#include <hiredis/hiredis.h>
         ^
1 error generated.
make[2]: *** [lib/CMakeFiles/zmaplib.dir/redis.c.o] Error 1
make[1]: *** [lib/CMakeFiles/zmaplib.dir/all] Error 2
make: *** [all] Error 2 

I use port, and installed the nessesery ports: port install gmp libdnet byacc flex gengetopt cmake 
Thx!

**Comment by zakird** [comment]
It sounds like you don't have hiredis, which is a dependency for the Redis plugin. You either need to build without redis support or instill the hiredis library.

**Comment by shadowcorw** [comment]
Ok, it's working now. Thx!
