### ISSUE TITLE
rum zmap in docker,SIOCGIFADDR: Invalid argument,send 0,recv 0 

### ISSUE THREAD

**Issue by sampr0** [zmap/zmap#279]
I run zmap in docker,but failed with this:
Aug 07 17:59:39.014 [INFO] zmap: output module: csv
Aug 07 17:59:39.014 [INFO] csv: no output file selected, will use stdout
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
SIOCGIFADDR: Invalid argument
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:02 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:03 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:04 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
I tried -G,-i,-S,--vpn
but still not work

**Comment by dadrian** [comment]
It's unlikely ZMap will work in Docker, but can you paste the output with logging set to verbose (`-v 5`)?

**Comment by sampr0** [comment]
root@6211ef2ef0a7:/# ip route         
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.2 
default via 172.17.42.1 dev eth0 
root@6211ef2ef0a7:/# arp -a
? (172.17.42.1) at d6:20:6b:6b:20:52 [ether] on eth0
root@6211ef2ef0a7:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:7738 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6863 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:21990072 (21.9 MB)  TX bytes:489267 (489.2 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
root@6211ef2ef0a7:/# zmap -p 80 211.138.17.35 -v 5
Aug 10 01:44:06.003 [TRACE] zmap: zmap main thread started
Aug 10 01:44:06.003 [TRACE] zmap: requested ouput-module: default

Aug 10 01:44:06.003 [DEBUG] zmap: no output module provided. will use csv.
Aug 10 01:44:06.003 [DEBUG] zmap: requested output field (0): saddr
Aug 10 01:44:06.003 [WARN] blacklist: ZMap is currently using the default blacklist located at /etc/zmap/blacklist.conf. By default, this blacklist excludes locally scoped networks (e.g. 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blacklist by editing the default ZMap configuration at /etc/zmap/zmap.conf.
Aug 10 01:44:06.003 [INFO] zmap: started
Aug 10 01:44:06.093 [DEBUG] zmap: no interface provided. will use default interface (eth0).
Aug 10 01:44:06.093 [DEBUG] zmap: no source IP address given. will use default address: 172.17.0.2.
Aug 10 01:44:06.093 [DEBUG] zmap: found gateway IP 172.17.42.1 on eth0
Aug 10 01:44:06.093 [DEBUG] zmap: MAC address of selected gateway d6:20:6b:6b:20:52
Aug 10 01:44:06.093 [INFO] zmap: zmap selected output module: csv
Aug 10 01:44:06.093 [WARN] csv: no output file selected. no results will be provided.
Aug 10 01:44:06.093 [TRACE] constraint: Initializing
Aug 10 01:44:06.093 [TRACE] whitelist: blacklisting 0.0.0.0/0
Aug 10 01:44:06.093 [TRACE] whitelisting: whitelisting 211.138.17.35/32
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 0.0.0.0/8
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 10.0.0.0/8
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 100.64.0.0/10
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 127.0.0.0/8
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 169.254.0.0/16
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 172.16.0.0/12
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 192.0.0.0/24
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 192.0.2.0/24
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 192.88.99.0/24
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 192.168.0.0/16
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 198.18.0.0/15
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 198.51.100.0/24
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 203.0.113.0/24
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 240.0.0.0/4
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 255.255.255.255/32
Aug 10 01:44:06.093 [TRACE] blacklisting: blacklisting 224.0.0.0/4
Aug 10 01:44:06.093 [TRACE] constraint: Painting value 1
Aug 10 01:44:06.099 [DEBUG] constraint: 0 IPs in radix array, 1 IPs in tree
Aug 10 01:44:06.099 [DEBUG] blacklist: 1 addresses allowed to be scanned (0% of address space)
Aug 10 01:44:06.099 [DEBUG] cyclic: using prime 65537, known_primroot 3
Aug 10 01:44:06.100 [DEBUG] cyclic: primitive root: 13004
Aug 10 01:44:06.100 [DEBUG] cyclic: starting point: 1288782202
Aug 10 01:44:06.100 [DEBUG] send: will send from 1 address on 28233 source ports
Aug 10 01:44:06.101 [TRACE] zmap: set thread 1010829056 affinity to core 0
Aug 10 01:44:06.102 [DEBUG] recv: thread started
Aug 10 01:44:06.102 [DEBUG] recv: using dev eth0
Aug 10 01:44:06.108 [DEBUG] recv: receiver ready
Aug 10 01:44:06.108 [DEBUG] recv: duplicate responses will be excluded from output
Aug 10 01:44:06.108 [DEBUG] recv: unsuccessful responses will be excluded from output
Aug 10 01:44:06.108 [DEBUG] zmap: using 1 sender threads
Aug 10 01:44:06.108 [TRACE] zmap: set thread 987727616 affinity to core 1
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
Aug 10 01:44:06.109 [TRACE] zmap: set thread 998217472 affinity to core 0
Aug 10 01:44:06.109 [DEBUG] send: thread started
SIOCGIFADDR: Invalid argument
Aug 10 01:44:06.109 [DEBUG] zmap: senders finished
 0:01 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:02 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:03 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:04 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:05 0% (68 years left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:06 0% (68 years left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:07 0% (68 years left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%

**Comment by dadrian** [comment]
Are you using boot2docker? If so, can you enable Promiscuous Mode on the host-only network that boot2docker created in Virtual Box?

**Comment by dadrian** [comment]
Since I haven't heard back, I'm going to go ahead and close this issue. Feel free to reopen.

**Comment by nanshihui** [comment]
I got the same problem in docker

**Comment by dadrian** [comment]
@ralphholz, I vague recollection of you running ZMap in Docker, did you ever encounter this issue?

**Comment by ralphholz** [comment]
@dadrian We didn't, actually. But I vaguely recall a similar thing under VMWare, when zmap would occasionally get 0% results (but it did send!). Went away on restart. ¯\_(ツ)_/¯

**Comment by dadrian** [comment]
@nanshihui can you try running ZMap with `-i` and the interface name?

**Comment by nanshihui** [comment]
I have alredy tried -i and -g , but still didn't work yet

**Comment by nanshihui** [comment]
the result i got bellow
`[root@host-10-190-167-158 ipProxyDec]$zmap 118.23.12.12/24 -p 80 -i nsaa018e64-3b -v 5 -G "3C:8C:40:0A:CE:A3" --vpn -B 3M
Jan 03 01:52:47.960 [DEBUG] zmap: zmap main thread started
Jan 03 01:52:47.960 [DEBUG] zmap: Loaded configuration file /etc/zmap/zmap.conf
Jan 03 01:52:47.960 [DEBUG] zmap: syslog support enabled
Jan 03 01:52:47.960 [DEBUG] zmap: requested ouput-module: default
Jan 03 01:52:47.960 [DEBUG] zmap: no output module provided. will use csv.
Jan 03 01:52:47.960 [DEBUG] fieldset: probe module does not supply application success field.
Jan 03 01:52:47.960 [DEBUG] zmap: requested output field (0): saddr
Jan 03 01:52:47.960 [DEBUG] filter: no output filter. will use default: exclude duplicates and unssuccessful
Jan 03 01:52:47.960 [WARN] blacklist: ZMap is currently using the default blacklist located at /etc/zmap/blacklist.conf. By default, this blacklist excludes locally scoped networks (e.g. 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blacklist by editing the default ZMap configuration at /etc/zmap/zmap.conf.
Jan 03 01:52:47.961 [DEBUG] constraint: blacklisting 0.0.0.0/0
Jan 03 01:52:47.961 [DEBUG] constraint: Painting value 1
Jan 03 01:52:47.976 [DEBUG] constraint: 0 IPs in radix array, 256 IPs in tree
Jan 03 01:52:47.976 [DEBUG] constraint: 256 addresses (0% of address space) can be scanned
Jan 03 01:52:47.976 [DEBUG] zmap: no source IP address given. will use default address: 10.190.167.158.
Jan 03 01:52:47.976 [DEBUG] send: gateway MAC address 3c:8c:40:0a:ce:a3
Jan 03 01:52:47.976 [INFO] zmap: output module: csv
Jan 03 01:52:47.976 [INFO] csv: no output file selected, will use stdout
Jan 03 01:52:47.976 [DEBUG] zmap: Isomorphism: 155
Jan 03 01:52:47.976 [DEBUG] send: srcip_first: 2661793290
Jan 03 01:52:47.976 [DEBUG] send: srcip_last: 2661793290
Jan 03 01:52:47.976 [DEBUG] send: will send from 1 address on 28233 source ports
Jan 03 01:52:47.977 [DEBUG] send: using bandwidth 3000000 bits/s, rate set to 4464 pkt/s
Jan 03 01:52:47.977 [DEBUG] send: no source MAC provided. automatically detected fa:16:3d:29:f3:2d as hw interface for nsaa018e64-3b
Jan 03 01:52:47.977 [DEBUG] send: source MAC address fa:16:3d:29:f3:2d
Jan 03 01:52:47.978 [DEBUG] zmap: Pinning receive thread to core 0
Jan 03 01:52:47.978 [DEBUG] recv: capturing responses on nsaa018e64-3b
Jan 03 01:52:48.016 [DEBUG] recv: duplicate responses will be excluded from output
Jan 03 01:52:48.016 [DEBUG] recv: unsuccessful responses will be excluded from output
Jan 03 01:52:48.016 [DEBUG] zmap: 1 sender threads spawned
Jan 03 01:52:48.016 [DEBUG] zmap: Pinning a send thread to core 1
Jan 03 01:52:48.016 [DEBUG] zmap: Pinning monitor thread to core 2
Jan 03 01:52:48.016 [DEBUG] send: send thread started
SIOCGIFADDR: Invalid argument
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
Jan 03 01:52:48.017 [DEBUG] zmap: senders finished
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:02 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:03 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:04 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:05 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:06 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:07 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:08 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:09 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:10 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:11 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:12 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:13 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:14 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:15 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%`

**Comment by dadrian** [comment]
@nanshihui If you're compiling from master, can you add a `fprintf(stderr, "%s, %s", if_ip.ifr_name, zconf.iface)` between line 49 and 50 in `send-linux.h`, and let me know what the output is? https://github.com/zmap/zmap/blob/4784fb1754b5775bd7b0a3e23b9cd3c2d9f3f5d4/src/send-linux.h#L49

**Comment by nanshihui** [comment]
thanks  first.
@dadrian 


root@host-10-190-167-158 zmap]$[root@host-10-190-167-158 ipProxyDec]$zmap 118.23.12.12/24 -p 80 -i nsaa018e64-3b -v 5 -G "3C:8C:40:0A:CE:A3" --vpn -B 3M
bash: [root@host-10-190-167-158: command not found
[root@host-10-190-167-158 zmap]$zmap 118.23.12.12/24 -p 80 -i nsaa018e64-3b -v 5 -G "3C:8C:40:0A:CE:A3" --vpn -B 3M
Jan 03 03:13:25.591 [DEBUG] zmap: zmap main thread started
Jan 03 03:13:25.591 [DEBUG] zmap: Loaded configuration file /etc/zmap/zmap.conf
Jan 03 03:13:25.591 [DEBUG] zmap: syslog support enabled
Jan 03 03:13:25.591 [DEBUG] zmap: requested ouput-module: default
Jan 03 03:13:25.591 [DEBUG] zmap: no output module provided. will use csv.
Jan 03 03:13:25.591 [DEBUG] fieldset: probe module does not supply application success field.
Jan 03 03:13:25.591 [DEBUG] zmap: requested output field (0): saddr
Jan 03 03:13:25.591 [DEBUG] filter: no output filter. will use default: exclude duplicates and unssuccessful
Jan 03 03:13:25.592 [WARN] blacklist: ZMap is currently using the default blacklist located at /etc/zmap/blacklist.conf. By default, this blacklist excludes locally scoped networks (e.g. 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blacklist by editing the default ZMap configuration at /etc/zmap/zmap.conf.
Jan 03 03:13:25.593 [DEBUG] constraint: blacklisting 0.0.0.0/0
Jan 03 03:13:25.593 [DEBUG] constraint: Painting value 1
Jan 03 03:13:25.605 [DEBUG] constraint: 0 IPs in radix array, 256 IPs in tree
Jan 03 03:13:25.605 [DEBUG] constraint: 256 addresses (0% of address space) can be scanned
Jan 03 03:13:25.605 [DEBUG] zmap: no source IP address given. will use default address: 10.190.167.158.
Jan 03 03:13:25.605 [DEBUG] send: gateway MAC address 3c:8c:40:0a:ce:a3
Jan 03 03:13:25.605 [INFO] zmap: output module: csv
Jan 03 03:13:25.605 [INFO] csv: no output file selected, will use stdout
Jan 03 03:13:25.606 [DEBUG] zmap: Isomorphism: 166
Jan 03 03:13:25.606 [DEBUG] send: srcip_first: 2661793290
Jan 03 03:13:25.606 [DEBUG] send: srcip_last: 2661793290
Jan 03 03:13:25.606 [DEBUG] send: will send from 1 address on 28233 source ports
Jan 03 03:13:25.606 [DEBUG] send: using bandwidth 3000000 bits/s, rate set to 4464 pkt/s
Jan 03 03:13:25.606 [DEBUG] send: no source MAC provided. automatically detected fa:16:3d:29:f3:2d as hw interface for nsaa018e64-3b
Jan 03 03:13:25.606 [DEBUG] send: source MAC address fa:16:3d:29:f3:2d
Jan 03 03:13:25.608 [DEBUG] zmap: Pinning receive thread to core 0
Jan 03 03:13:25.608 [DEBUG] recv: capturing responses on nsaa018e64-3b
Jan 03 03:13:25.639 [DEBUG] recv: duplicate responses will be excluded from output
Jan 03 03:13:25.639 [DEBUG] recv: unsuccessful responses will be excluded from output
Jan 03 03:13:25.640 [DEBUG] zmap: 1 sender threads spawned
Jan 03 03:13:25.640 [DEBUG] zmap: Pinning a send thread to core 1
Jan 03 03:13:25.640 [DEBUG] zmap: Pinning monitor thread to core 2
Jan 03 03:13:25.640 [DEBUG] send: send thread started
nsaa018e64-3b,nsaa018e64-3bSIOCGIFADDR: Invalid argument
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
Jan 03 03:13:25.641 [DEBUG] zmap: senders finished
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:02 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:03 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:04 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:05 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:06 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:07 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:08 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:09 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:10 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:11 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:12 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:13 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:14 0% (0s left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%

**Comment by nanshihui** [comment]
from the output  , the interface name is right...

**Comment by nanshihui** [comment]
finally, I delete the code from  line 50 to line 53 in send-linux.h, and it did work.
@dadrian ,is it  safe ?
[ https://github.com/zmap/zmap/blob/4784fb1754b5775bd7b0a3e23b9cd3c2d9f3f5d4/src/send-linux.h#L49]( https://github.com/zmap/zmap/blob/4784fb1754b5775bd7b0a3e23b9cd3c2d9f3f5d4/src/send-linux.h#L49)

**Comment by dadrian** [comment]
This does raise an interesting question as to why we even both to get the source IP, since we don't seem to use it later in the code. Does ZMap seem to be working without those lines?

@zakird thoughts?

**Comment by zakird** [comment]
If I'm not missing something here, we just never use that variable so I don't see why it'd matter?
