### ISSUE TITLE
interpret results of redis-packet output module

### ISSUE THREAD

**Issue by janemba** [zmap/zmap#281]
Hi,

I tried to use redis module from zmap so I use the following command :
 # zmap --bandwidth=10M --output-module=redis-packed --output-fields='saddr-raw'  --output-args=tcp://localhost:6379/list --target-port=443 x.x.x.x/24

I redis-monitored the output and I got binary data. My question is where can I find the documentation to interpret this data ?

Cheers

**Comment by zakird** [comment]
The redis-packed module will put only the IP address in redis in binary form. If you want more options of what's put in redis, you can use the redis-csv module, which will place the equivalent of one line of the CSV output file into the redis queue.

**Comment by janemba** [comment]
OK so I should switch to this module.

I change my command-line by that :
 # zmap --bandwidth=10M --output-module=csvredis --output-args=tcp://localhost:6379/list --target-port=443 x.x.x.x/24

and I got the following error :
 Aug 31 21:11:07.402 [FATAL] constraint: '-1' is not a valid prefix length

So I used -f switch with only 'saddr' and I got that error :
 Aug 31 21:12:02.961 [FATAL] csvredis: module does not support user defined output fields

What is the usage of the command-line with csvredis module ?

Cheers,

**Comment by dadrian** [comment]
If you use the latest release candidate, you should have the output module `redis-csv`, which does what you want. `csvredis` outputs both packed binary to Redis and a CSV to a file. `redis-csv` outputs a CSV as a string to a redis queue.

**Comment by janemba** [comment]
awesome.
