### ISSUE TITLE
Add flag for force installing  conf files

### ISSUE THREAD

**Issue by tdi** [zmap/zmap#290]
It would be nice to have some flag, say `FORCE_CONF_INSTALL` that would install conf files even if there /etc is already populated. 

This is needed for Debian/Ubuntu packaging. When building a zmap package, and for some reason you have your zmap installed, the package won't include conf files. Mind that Debian packaging has a mechanism called conffiles that makes sure that none of user changes are overwritten. 

PS: Now I just patch CMakeLists every 2.X release to just install the files.

**Comment by zakird** [comment]
I've added FORCE_CONF_INSTALL as a cmake option, which should fix this. LMK if this works.

**Comment by zakird** [comment]
This was added. Closing given no response.
