### ISSUE TITLE
[FATAL] zmap: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Pablohn26** [zmap/zmap#296]
Because a typo (zmap instead of nmap) I have gotten a segmentation fault when you run 
    
    zmap -O example.com

would be interesting to improve the deal of arguments

**Comment by dadrian** [comment]
Agreed, that should definitely not happen. @paul-pearce, if you're sitting in the code still it'd be great if you could investigate, it looks like we just have an out-of-bounds index in the selection of the output modules.

**Comment by paul-pearce** [comment]
What version?

**Comment by zakird** [comment]
Can you please confirm that this is happening in the master branch? I am able to confirm on older versions, but this seems to be fixed in master.

**Comment by zakird** [comment]
This is the bt on older versions: https://gist.github.com/zakird/32691310090c8375e651

**Comment by zakird** [comment]
I am closing this issue as there has been no additional information from the reporter on how to reproduce the bug.

**Comment by Pablohn26** [comment]
Sorry about the delay. It was and old version (1.2.1). Tested and fixed on latest version.
