### ISSUE TITLE
Zmap cannot parse subshell command and thus ignores host argument and scans random internet

### ISSUE THREAD

**Issue by phrag** [zmap/zmap#297]
The following command parses incorrectly and ignores everything after the $(date +%s) subshell command, and thus scans the random internet.

sudo zmap -d --verbosity=5  -i eth2:1 -p 22 --summary -o Port.SSH-$(date +%s).csv 1.2.3.4/24 5.6.7.8/24 9.10.11.12/24

The netblocks are example.

**Comment by zakird** [comment]
can you paste log with -v5 so we can see how this is being parsed out?

**Comment by phrag** [comment]
If i do that, i start scanning the random internet...

When this bugged, i recieved a flood of abuse mails... i do not want to trigger that again.

Do you have a safer method to test please?

**Comment by zakird** [comment]
You could set max hosts.

**Comment by phrag** [comment]
Could i use -d (dryrun)?

**Comment by phrag** [comment]
Unfortuntaley i cannot reproduce this without executing it and do not have time to debug.

Closing, apologies.

**Comment by dadrian** [comment]
For future reference, you can add `-n 1`, which will only send a single packet.
