### ISSUE TITLE
documentation referencing deprecated options

### ISSUE THREAD

**Issue by gelim** [zmap/zmap#298]
Hi,

you're referencing the "-O extended_file" option of zmap in the file examples/forge-socket/README.
This feature has since been removed.

Using the default (csv) format is still compatible with the forge-socket example ?
Thanks

**Comment by zakird** [comment]
Yes, you can export the data you need from ZMap using the CSV output module and specified the --output-fields that you need. I'll fix the documentation.

**Comment by zakird** [comment]
updated in d9ab985.

**Comment by gelim** [comment]
Thanks for the explanation and quick fix !
