### ISSUE TITLE
zmap can not work on my pppoe...

### ISSUE THREAD

**Issue by ecawen** [zmap/zmap#299]
so saddly, zmap can not work fine under my pppoe, pppoe interface is ppp0, if only -p,show:
Oct 21 00:47:09.727 [FATAL] get_gateway: Unexpected hardware address length (0).

    If you are using a VPN, supply the --vpn flag (and provide an interface via -i)
if --vpn,work but no recv;
if --vpn -i eth0, work still no recv;

if -i ppp0, show
Oct 21 00:49:29.782 [FATAL] get-gateway: interface specified (ppp0) does not match the interface of the default gateway (eth0). You will need to manually specify the MAC address of your gateway.

if --vpn -i ppp0, show:
Oct 21 00:49:38.811 [FATAL] recv: couldn't compile filter

if work, no recv, tcpdump on eth0, link below:
---------------------
00:37:05.134433 00:00:ff:06:b7:61 > 45:00:00:28:d4:31, ethertype Unknown (0xc0a8), length 54: 
        0x0000:  0003 dbe8 93a8 b9a8 0050 feae 371a 0000  .........P..7...
        0x0010:  0000 5002 ffff 8fe4 0000 0000 0000 0000  ..P.............
        0x0020:  0000 0000 0000 0000                      ........
00:37:05.134436 00:00:ff:06:33:f3 > 45:00:00:28:d4:31, ethertype Unknown (0xc0a8), length 54: 
        0x0000:  0003 dbe8 1717 b3f0 0050 dc20 e881 0000  .........P......
        0x0010:  0000 5002 ffff 8354 0000 0000 0000 0000  ..P....T........
        0x0020:  0000 0000 0000 0000                      ........

**Comment by dadrian** [comment]
Have you tried specifying the MAC address of your gateway using `-G`?

**Comment by ecawen** [comment]
sorry but i never get gateway mac on my pc if use ppppoe, if run ifconfig, it show mac filtered, or if run arp -a, it show none.  if ok, I think it is changed oftenly when pppoe dialup again, should not fit me...
I will see the mac filter real message when i get home.

**Comment by ecawen** [comment]
ppp0      Link encap:Point-to-Point Protocol  
          inet addr:114.248.101.40  P-t-P:114.248.96.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:24 errors:0 dropped:0 overruns:0 frame:0
          TX packets:26 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:1365 (1.3 KiB)  TX bytes:1140 (1.1 KiB)

root@zck70:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         *               0.0.0.0         U     0      0        0 ppp0
114.248.96.1    *               255.255.255.255 UH    0      0        0 ppp0
192.168.1.0     *               255.255.255.0   U     0      0        0 eth0
root@zck70:~# arp -a
localhost (192.168.1.8) at f0:de:f1:37:f0:0b [ether] on eth0
root@zck70:~#
root@zck70:~# arping 114.249.96.1
arping: lookup dev: No matching interface found using getifaddrs().
arping: Unable to automatically find interface to use. Is it on the local LAN?
arping: Use -i to manually specify interface. Guessing interface eth0.
ARPING 114.249.96.1
Timeout

**Comment by ecawen** [comment]
![11](https://cloud.githubusercontent.com/assets/4194205/10695966/3cbfd940-79d9-11e5-8789-c072c34d9214.png)

**Comment by zakird** [comment]
I believe that --vpn has been broken for a while. This issue should really be make "--vpn" work again. @ecawen if you have time to work on this, that would be wonderful. Realistically it'll be a bit before the core team has a chance to look at this.

**Comment by ecawen** [comment]
may be debian also has some problem, see the new pic, when sendto(), the last two btyes of the first 16 bytes,  shoud be 08 00, but sendto() is 00 00,  which 08 sign it is IP protocol,  zmap can not control this whether -X or not, also zmap may have some problem when recv, it should 16 bytes butsizeof(struct ether_header) is 14 bytes,  but first, I cant send pkt successfully,  I dont know if there some kernel pppoe args to set to resolv it. I am looking for the function sendto() to see what is happen, it is a little hard...

**Comment by ecawen** [comment]
cmd is:
zmap -p 21 100.x.x.x/24 -i ppp0 -G 00:00:00:00:00:00 -S pppoe_ip

pic can not upload there now, it always show uploading...

**Comment by ecawen** [comment]
![pppoe2](https://cloud.githubusercontent.com/assets/4194205/10928498/dd574cae-82e3-11e5-97b9-9f5353f263ae.jpg)

**Comment by zakird** [comment]
I've taken a look at this over the last several days and have made some adjustments that allow for sending and receiving IP layer packets in the `vpn-great-again` branch. The reality is, though, I don't think we're going to add support for PPP connections if we need to implement this specifically. ZMap has a pretty limited scope---which is doing full Internet-wide scans, and this isn't within that scope for the core maintainers. If you want to submit a PR that fixes this, then we can reconsider.

**Comment by dkasak** [comment]
Why not remove the `--vpn` flag then, since it's broken?

**Comment by nanshihui** [comment]
may be  it will work in the next version
