### ISSUE TITLE
ZMap does not guarantee UTF-8 

### ISSUE THREAD

**Issue by zakird** [zmap/zmap#301]
ZMap currently outputs non-UTF8 encoded data. This hasn't been a problem previously because we constructed most of the strings. However, this model broken when the DNS module was introduced. We need to ensure that strings are UTF-8 valid (by escaping any invalid characters). A couple of notes:

1) json-c does not escape invalid UTF-8 (so therefore doesn't save us). As well, we really want every output module to be outputting real strings

2) This is what Golang does. We should probably do something similar "String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason."

3) I'm attaching a file which is known to cause problems and can be used for testing. We can test by trying to parse the JSON with python.

[out.txt](https://github.com/zmap/zmap/files/20331/out.txt)

**Comment by zakird** [comment]
Paul I'm assigning this to you for now, but anyone can grab it.

**Comment by paul-pearce** [comment]
I changed the milestone to 3.0 given that this needs to pull in a new library.

**Comment by zakird** [comment]
We should use standard behavior for invalid characters:


pearce [3:37 PM] 
>>>s = chr(0x6a) + chr(0xc0) + chr(0x0c)
>>> s
'j\xc0\x0c'
>>> s.decode("utf-8", "replace")
u'j\ufffd\x0c'

pearce [3:37 PM]
it replaces it with the rune.

zakir [3:38 PM]

**Comment by paul-pearce** [comment]
Expanding on Zakir's comment a bit. We had some discussion about the escaping behavior for the fix as deployed. We decided to change it and go with a "lossy" solution where the bad bytes are replaced with a �. This matches the behavior of most languages. Sadly. 

I will queue this fix up and change the code when I get a chance.
