### ISSUE TITLE
Malloc(incorrect checksum for freed object)

### ISSUE THREAD

**Issue by The-Sec** [zmap/zmap#303]
zmap(3035,0x700000081000) malloc: *** error for object 0x7fedd4a00100: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

On a mac Retina, mid 2012(2,6Ghz, 16Gb) OS X 10.11.1
From github latest version(zmap 2.1.1)
(git clone git://github.com/zmap/zmap.git)
(cmake -DENABLE_DEVELOPMENT=ON)
(make)
and
(cmake -DENABLE_DEVELOPMENT=OFF)
(make)

Same outcome.

(Coredump.tar.gz)
https://drive.google.com/file/d/0B2O2GU6FW1MxdDRpUFdMekxsR0k/view?usp=sharing

**Comment by dadrian** [comment]
Can you post the logs as well (ideally with `-v 5`)?

**Comment by The-Sec** [comment]
[code]
Dev:zmap root# ./src/zmap -p 80 0.0.0.0/0 -v 5 > /dev/null
[/code]
Oct 30 08:40:20.317 [DEBUG] send: send_packet failed for [inet_ntoa error]. No buffer space available
Oct 30 08:40:20.317 [DEBUG] send: send_packet failed for 145.89.182.51. No buffer space available
Oct 30 08:40:20.318 [DEBUG] send: send_packet failed for 145.89.182.51. No buffer space available

**Comment by dadrian** [comment]
The core dump isn't loading for me, and I can't duplicate on my own install. Do you know which commit you were using? Also, we're you directly on OS X, or were you in a docker container or a VM?

**Comment by The-Sec** [comment]
i used the GIt hub version from 27 oct. 15:33 so just before or after https://github.com/zmap/zmap/commit/647643fb192ff44793bde899f8b4a7d1580e2913

i'm running it directly on the hardware no VM or docker container, as root.

**Comment by dadrian** [comment]
It looks like there was a race condition in the arguments passed to debug logger that was causing this crash. I believe I fixed this in 865f76c1998a.
That being said, in the log you posted above, it looks like your NIC was dropping packets because ZMap was sending faster than the NIC could handle You should try rate limiting ZMap using `-r` or `-B`, and also possibly only use one sender thread `-T 1`.

**Comment by zakird** [comment]
There has been no additional information on whether this was fixed in more than two months. I am closing the issue. If the problem occurs again in the future, please feel free to reopen.
