### ISSUE TITLE
master code on day 10.29, compile err

### ISSUE THREAD

**Issue by ecawen** [zmap/zmap#306]
cmake ./ is not error, but make show below.  now I am finding the header on some package, I think it should be: libunistring-dev on debian.

[ 19%] Building C object src/CMakeFiles/zmap.dir/aesrand.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/cyclic.c.o
[ 21%] Building C object src/CMakeFiles/zmap.dir/expression.c.o
[ 23%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
/home/dev/zmap/src/fieldset.c:15:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.

**Comment by paul-pearce** [comment]
You are correct. Master now has a new dependency on libunistring. In the same commit that added the dependency INSTALL was updated to mention libunistring as well as how to install it on all common platforms.

This will be merged into zmap release 3.0 and be called out more prominently as a new dependency (I believe).

I'm going to go ahead and close this. If upon review the documentation is show lacking, please comment.
