### ISSUE TITLE
zmap compile error unistr.h

### ISSUE THREAD

**Issue by wulidongdong** [zmap/zmap#307]
[ 12%] Built target zmaplib
[ 15%] Built target zblacklist
[ 16%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
/root/zmap/src/fieldset.c:15:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.
src/CMakeFiles/zmap.dir/build.make:138: recipe for target 'src/CMakeFiles/zmap.dir/fieldset.c.o' failed
make[2]: *** [src/CMakeFiles/zmap.dir/fieldset.c.o] Error 1
CMakeFiles/Makefile2:166: recipe for target 'src/CMakeFiles/zmap.dir/all' failed
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

OS:kali 2.0

**Comment by paul-pearce** [comment]
See https://github.com/zmap/zmap/issues/306. This will be a new dependency as of zmap 3.0. The new dependency and how to install it is discussed in INSTALL.

**Comment by wulidongdong** [comment]
thx

**Comment by chaozai1028l** [comment]
[ 23%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
/data/ZMAP/zmap/src/fieldset.c:15:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/zmap.dir/fieldset.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2

have a answer?

**Comment by paul-pearce** [comment]
"""
See #306. This will be a new dependency as of zmap 3.0. The new dependency and how to install it is discussed in INSTALL.
"""
Does that not work?

**Comment by zakird** [comment]
Please do not attach new issues to Github issues that were closed _years_ ago. If there is a problem, start a new issue. As @paul-pearce has indicated, ZMap depends on libunstring, which is documented in INSTALL. If you have followed those instructions and are still encountering issues, please open a new support issue with documentation on your system is setup and what packages are installed.
