### ISSUE TITLE
sendto failures fatal doesn't happen until the end of scan

### ISSUE THREAD

**Issue by zakird** [zmap/zmap#318]
Jan 06 00:00:11.272 [FATAL] monitor: maxiumum number of sendto failures (1) exceeded

**Comment by zakird** [comment]
fixed by cbe2848.

**Comment by dragonkid** [comment]
How can I bypass this bug in ZMAP 2.x.x?

**Comment by zakird** [comment]
I'm not sure if I understand. What do you mean bypass? It's fixed in master or you can just not use the feature.

**Comment by dragonkid** [comment]
I did build ZMAP from master, but the scan also stopped with the same error message.

So I add the parameter `--max-sendto-failures 1000000` to complete the scan, I am not sure was that right?

**Comment by kevien** [comment]
i met the same problem.....

**Comment by kevien** [comment]
how to avoid this problem?

**Comment by zakird** [comment]
I'm still not quite sure what issue is being encountered here. Can you elaborate?

**Comment by kevien** [comment]
i try this --max-sendto-failures 1000000(large number)   ,problem has solved  ....

**Comment by zakird** [comment]
If you actually have a large number of sendto errors, then something is probably wrong. Likely your machine can't keep up with what you're doing. Sendto errors result in packets not being sent. If you ignore huge numbers of them, you might as well just scan less of the Internet. The right solution is probably to scan at a lower rate.

**Comment by kevien** [comment]
i get it ,thanks 👍
