### ISSUE TITLE
Zmap doesn`t get rst packages if not set --output-module

### ISSUE THREAD

**Issue by BingoZ** [zmap/zmap#331]
Hi, I recently find zmap can not catch rst packages if you use the default output module and don`t add "--output-module=csv/json" in your command in the newest 2.1.0 version, and the numbers of recved in update-status don`t +1 if zmap catches a rst package. I  use mac os and don`t try if it occurs on other systems.

**Comment by zakird** [comment]
This is expected behavior. ZMap will only output IP addresses that responded with SYN-ACK packets unless a more advanced output module is used that can differentiate between different packet types.

**Comment by BingoZ** [comment]
The recv number of update-status will not update if a RST packet is caught and output. I think it`s not a bad idea to let output-filter control the classification of output IP addr zmap catches and make the update-status associated to the output.

**Comment by BingoZ** [comment]
The phenomenon I found is, if you set '-N 100 --output-module=csv' in your command, zmap will output more than 100 ip addrs including 100 ip addrs of replying SYN-ACK , the others are ip addrs of RST, but the 'recv-success-total' of update-status will be smaller than 100 when zmap stops.

**Comment by zakird** [comment]
To clarify, `--status-updates` give you updates during the scan, not at the completion. More could happen after you receive the last status update. If you want end of scan information, you should be using `--metadata-file`. So in that sense, it does make sense that the number you seen on screen or through `--status-updates` is smaller than 100.

**Comment by BingoZ** [comment]
I don`t think you have caught what I mean. It`s ZMAP that forgets to count RST replys so more than 100 ip is output and recv-success-total only represent the number of SYN-ACK replys partially.As RST reply sometimes may means UDP port reply of SYN request, I think it should not be ignored.
Any way, you may have your considerations and zmap is still a great program. I`m looking forward to the new release.

**Comment by BingoZ** [comment]
I recently found other bugs and I don`t know if you have gotten it, so I should list then blew.
1. Using '-N 10 -p 161 -M udp xxxxxx -f saddr,sport,data' , I find output in which port is not 161.
2. Adding '--output-module=csv' to command above, much worse.
Again, I use zmap on mac os.

**Comment by zakird** [comment]
Sometimes protocols will respond from different ports and can therefore not generically filter on port in every UDP situation. The UDP scan module is generic and therefore does not currently handle this. If you want to filter on port as well, this can be done by setting an output-filter.

**Comment by zakird** [comment]
I'm going to close this issue. This is expected behavior and I don't think there's anything we can right now to solve this. If more specific UDP logic is needed, you should create a specific probe module for that.
