### ISSUE TITLE
Utility to iterate over IPv4 space

### ISSUE THREAD

**Issue by jhart-r7** [zmap/zmap#333]
One great feature of `zmap` is its ability to iterate (and then scan) the entire IPv4 space minus some blacklisted hosts without needing to keep track of what has or hasn't been scanned yet thanks to its internal [cyclic generator](https://github.com/zmap/zmap/blob/master/src/cyclic.c).  Its ability to shard and break a huge set of random, discontiguous IPs into smaller shards/chunks for processing by distributed systems running `zmap` is very helpful from a scanning perspective.

It would be excellent to have this sharding-enabled, blacklist-aware cyclic generator exposed through `zmap` or as a separate utility that given a blacklist and an optional # number of shards, shard number and seed, will output the IPv4 addresses generated by this generator configured with this blacklist and shard information.  Such a utility could be useful for people doing studies related to the public IPv4 space, among other things.

`zlist`, `ziterate` or something similar sounds like a good name.

**Comment by aaspring** [comment]
The [documentation](https://zmap.io/documentation.html) gives the command 

```
zmap -p 443 -s 3 -n 10 --dryrun | grep daddr | awk -F'daddr: ' '{print $2}' | sed 's/ |.*//;'
```

which allows you to do exactly this. The IPs will be outputted to stdout which you can then pipe into a file or another program's stdin. You can use all the standard flags to set the black list, seed, number of shards, specific shard number, etc. You can also pass ```-c 0``` to avoid having to wait for the cooldown.

**Comment by jhart-r7** [comment]
Thanks @aaspring -- I had considered that route.  My primary concern with that being the solution is that there is so much more that is happening under the covers that this utility doesn't need -- building packets, calculating checksums, finding source IPs/ports to send from, etc.  I even wrote a new probe module specifically to work around this so that when run with `--dryrun` all it had to do was print out the source/destination IP and there was nothing at higher layers happening.

**Comment by jhart-r7** [comment]
I have some WIP code that should do this.  Once I get it working or get to the point where I need help, whichever comes first, I'll throw up a PR.

**Comment by jhart-r7** [comment]
I've got the guts of this done; I used the setup for `zmap` and `zblacklist` as my point of reference and modeled `ziterate`'s building/usage/code after them.  My C is terribly rusty and this segfaults currently (see my comments in the code), but I feel like this is the right direction.  

If anyone was interested in where this stands and/or could help with the segfault, see https://github.com/jhart-r7/zmap/tree/issue/333-ipv4-iterate-cyclic-zlist or 
https://github.com/zmap/zmap/compare/master...jhart-r7:issue/333-ipv4-iterate-cyclic-zlist?expand=1
