### ISSUE TITLE
libhiredis Dependency Issue on CentOS 7

### ISSUE THREAD

**Issue by GreenOut** [zmap/zmap#334]
Hey there,

this issue exist for quite some time and usually I fixed it by removing the latest version of libhiredis and download/install the required version "libhiredis.so.0.10()(64bit)".

It would be very nice if the developers could update zmap to work with the latest libhiredis version on CentOS 7.

![libhiredis](https://cloud.githubusercontent.com/assets/15252503/13666020/fe4066a2-e6b7-11e5-82cd-f80c2439742f.PNG)

(On the screenshot it doesn't give out an error because it's a fresh install server without the newest version of libhiredis installed. It's just to show that an old version is required to install zmap)

-----
Little help for other CentOS 7 Users with the same problem. Remove, Download, Install hiredis and try to install zmap again.

Download: `wget ftp://195.220.108.108/linux/epel/6/x86_64/hiredis-0.10.1-3.el6.x86_64.rpm`
Install: `rpm -i hiredis-0.10.1-3.el6.x86_64.rpm`

**Comment by zakird** [comment]
Unfortunately, I don't think this is a ZMap issue, but rather how ZMap has been packaged in Centos (which we don't have direct control over). ZMap itself builds against the latest version of hiredis (on my machine, this is version 0.13.3). 

I'd also note that ZMap version 1.2.1 is fairly old at this point---it was released several years ago now. ZMap 2.1.1 rpms should be available in the Fedora repos.

**Comment by GreenOut** [comment]
Well, someone has to do something to fix this :+1:

**Comment by zakird** [comment]
@cicku any ideas on the packaging side?

**Comment by cicku** [comment]
I think zmap in epel7 channel needs an update. Just rebuild the package is OK.

I don't know too much of Fedora nor CentOS recently because I haven't watched them doing anything to the package.

**Comment by zakird** [comment]
Is this something we can do, or is there a correct person to talk to within
the CentOS community?

**Comment by cicku** [comment]
I believe this guy @Fale has responsibility on zmap@epel7. If I have time I can compile it by myself but I really couldn'y find time working on Fedora at least until August. (https://admin.fedoraproject.org/pkgdb/package/rpms/zmap/)

**Comment by Fale** [comment]
A fixed version of zmap is already in the EPEL7 testing repo and should soon become stable :-). https://bodhi.fedoraproject.org/updates/?packages=zmap

**Comment by zakird** [comment]
I'm going to close this issue as it sounds like this has been resolved. Please feel free to reopen if that's not the case.
