### ISSUE TITLE
Perl support in zmap?

### ISSUE THREAD

**Issue by computernewb** [zmap/zmap#336]
I doubt this will ever happen, but will zmap ever support the Perl scripting language? I have a Perl script for nmap that uses things that aren't in Python. I don't know any Python and as far as I know, pyperl hasn't been updated in over 15 years. 

So I was wondering if Perl support would ever be considered for this program?

**Comment by dadrian** [comment]
I'm confused. Not only does ZMap not currently support Python as a scripting language, ZMap doesn't support _any_ scripting language, and it's not even immediately obvious what "supporting a scripting language" means in the context of ZMap.

To more directly answer your question, we would not ever consider implementing Perl scripting support.

**Comment by computernewb** [comment]
It doesn't? I thought I read somewhere that it did. Perhaps I got it mixed with nmap. Lol, anyways, thanks.
