### ISSUE TITLE
zmap source IP address option

### ISSUE THREAD

**Issue by BingoZ** [zmap/zmap#338]
The `-S` option is very useful to protect scanner itself, right now  `-S` just accept singal IP addr or IP ranges like `10.0.0.0-10.0.0.9`. But sometimes set `-S` to IPs which are far from each other, in different segment, like `10.0.0.1, 10.0.1.15,10.1.1.25`, if the machine allows, I think is much safer than continuous IP ranges.

**Comment by dadrian** [comment]
I agree this is a good feature. Do you have any idea how common it is for network cards to support non-contiguous IPs?

**Comment by BingoZ** [comment]
Yeh, it is hard to set IPs in different ranges for one network card, but it can help to set IPs in one range and not continuous,  to a network card. I think if `-S` supports settings like `10.0.0.1,10.0.0.100-10.0.0.120` is enough.

**Comment by zakird** [comment]
We'd happily merge a pull request for this functionality. However, I don't think the core team will be able to get to this for while.
