### ISSUE TITLE
Some ip addresses are missed by ZMAP

### ISSUE THREAD

**Issue by BingoZ** [zmap/zmap#339]
Hi, I find some addresses can be missed by ZMAP， like `125.39.240.113`, if you telnet its port 80, you can find it is open, but zmap can not scan it out in SYN mode. 
I capture the packet and guess it is because the syn packet sent out by ZMAP doesn`t set MSS in TCP option. Is this a little bug or just under your considerations?

**Comment by dragonkid** [comment]
I think this may be the reason why SYN was dropped.
[https://live.paloaltonetworks.com/t5/Management-Articles/SYN-Packets-Without-MSS-Are-Dropped-With-SYN-Cookie-Enabled/ta-p/52351](url)

Zmap should send normal SYN packet to avoid this.

**Comment by dadrian** [comment]
Thanks for the report, we'll look into getting this fixed.

**Comment by zakird** [comment]
I suspect the right thing to do here is to do A/B testing with this option set and unset. If there are no hosts lost by setting it, then it's an easy change. If you do lose hosts, then we're going to have to figure out a better. @dragonkid any chance you've tried testing with both?

**Comment by dragonkid** [comment]
I found the ip `202.108.152.150` which can be used for test.

I have tried to set the option, no hosts was lost.

Should I make a pull request?

**Comment by zakird** [comment]
That would be perfect, thank you.

**Comment by dragonkid** [comment]
@zakird  I am already make the pull request. Was that ok?
