### ISSUE TITLE
banner grab other udp ports

### ISSUE THREAD

**Issue by s3c1t** [zmap/zmap#341]
hi
i used pkt files for banner garbbing from defined upd ports (https://github.com/zmap/zmap/tree/master/examples/udp-probes)
now my question is: how to create or get (form specifed refrence) pkt files for other udp protocols (other  ports) in order to banner grabbing
thanks.

**Comment by dadrian** [comment]
The .pkt files are just the raw binary of a UDP payload, and shouldn't be too hard to generate from a packet capture. If you need values in the packet set based on destination host, see the UDP templating features, look at one of the .tpl files for an example.

**Comment by s3c1t** [comment]
thank you so much. for responding me
Is there another way for banner garbbing other upd ports
except udp ports listed in https://github.com/zmap/zmap/tree/master/examples/udp-probes

**Comment by dadrian** [comment]
You would need to create the relevant probe yourself.

**Comment by s3c1t** [comment]
thanks.
how to decode banner grabbed data field value.
for exmaple:
65720a37000000010000000000000000000000000000000000000001000186a000000002000000060000006f00000001000186a000000002000000110000006f00000000
i hex decoded above value but unclear

**Comment by zakird** [comment]
You'll have to parse those externally, or build a probe module to parse them. The UDP module outputs raw data.

**Comment by zakird** [comment]
This doesn't look like an issue that needs to be resolved within the ZMap code base, and as such Im going to close this issue.
