### ISSUE TITLE
UDP templates result in malformed probes

### ISSUE THREAD

**Issue by jhart-r7** [zmap/zmap#343]
Using the currently shipping zmap template for performing UDP probes of SIP endpoints (https://github.com/zmap/zmap/blob/master/examples/udp-probes/sip_options.tpl):

```
/usr/local/sbin/zmap -i en0 -s 5060 -p 5060 192.168.0.1 -M udp --probe-args=template:/Users/jhart/rapid7/zmap/examples/udp-probes/sip_options.tpl       
```

The resulting packet is invalid/problematic for a number of reasons:

* It is padded at the end with null bytes (0x00).  The number of bytes appended seems to vary and does not look like a symptom of word alignment/etc.
* The total length of the IP packet in the IPv4 header and/or the length in the UDP header is wrong, resulting in:
** the final trailing CR+LF (that is vital to the SIP message) being trimmed in the middle.
** The `Content-Length` field being subject to mishandling by receiving SIP endpoints since there is actually a body (albeit all NULLs)

This isn't a problem with just the example template file but likely any template file regardless of what interpolation they are using.  For example, this simple example results in a probe containing "foo 192.168.0", but is missing the trailing `.1` to complete the IP address):

```
foo ${DADDR}
```

It also sets the wrong UDP payload length (off by 2).

I have reproduced this with zmap 2.1.1 installed via homebrew on OS X and an older fork built shortly after #160 was first added (reports "2.0.0-RC1") running on 64-bit Ubuntu 14.04.

Will find a place to drop a pcap shortly.

**Comment by zakird** [comment]
Thanks for the note. Would you be willing to submit a pull request. Rapid7 initially introduced this functionality and we don't use it at all. You're likely in a much better position to fix the code than the Michigan team is.

**Comment by jhart-r7** [comment]
Unfortunately I don't have a fix for this right now.

**Comment by jhart-r7** [comment]
I've got a partial fix for this that corrects the second of the problems I discovered (the incorrect IP and UDP header lengths, which was actually a case of the templatized value getting truncated).  

I've got an eye on the other problem too.
