### ISSUE TITLE
not available response field

### ISSUE THREAD

**Issue by s3c1t** [zmap/zmap#346]
i installed zmap from source. my current vesrion zmap is 2.1.1
According to documentation zmap.i wanted to run following line
zmap -p 80 -f "response,saddr,daddr,sport,seq,ack,in_cooldown,is_repeat,timestamp" -o output.csv
when i run.. appeared following error
May 21 10:56:50.738 [FATAL] fieldset: specified field (response) not available in selected probe module.
help me please

**Comment by zakird** [comment]
Response is not a valid field as logged. You can list supported fields by running --list-output-fields.
