### ISSUE TITLE
IP do not in whitelist will be returned

### ISSUE THREAD

**Issue by dragonkid** [zmap/zmap#347]
I found a bug of ZMAP which will return IP which do not in whitelist when scanning with UDP.

You can regenerate it like that:
1. `zmap -p 161 223.240.192.196 --probe-module udp --probe-args=file:SNMPv1public`
2. wait several seconds
3. `zmap -p 161 223.240.192.145 --probe-module udp --probe-args=file:SNMPv1public`

then you will get this:

```
May 24 16:18:08.735 [WARN] zmap: too few targets relative to senders, dropping to one sender
May 24 16:18:09.007 [INFO] zmap: output module: csv
May 24 16:18:09.008 [INFO] csv: no output file selected, will use stdout
 0:00 1%; send: 1 done (24 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:00 1%; send: 1 done (24 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
223.240.192.196
 0:01 13%; send: 1 done (24 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
0.0.0.0
 0:02 25%; send: 1 done (24 p/s avg); recv: 2 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 200.00%
 0:03 38%; send: 1 done (24 p/s avg); recv: 2 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 200.00%
 0:04 50%; send: 1 done (24 p/s avg); recv: 2 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 200.00%
 0:05 63% (3s left); send: 1 done (24 p/s avg); recv: 2 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 200.00%
223.240.192.145
 0:06 75% (2s left); send: 1 done (24 p/s avg); recv: 3 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 300.00%
 0:07 88% (1s left); send: 1 done (24 p/s avg); recv: 3 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 300.00%
 0:08 101% (0s left); send: 1 done (24 p/s avg); recv: 3 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 300.00%
May 24 16:18:18.105 [INFO] zmap: completed
```

I am still not sure if the `0.0.0.0` is also a bug.

I think the reason why this occured is the `validate_packet` method of `module_udp` is too simple.

**Comment by dadrian** [comment]
You're picking a retransmission of the response from the previous scan. We could probably add a check to make sure that any received packet is from a non-blacklisted server. @zakird, thoughts?

**Comment by dragonkid** [comment]
I think that will be perfect:) 

And do you known why `0.0.0.0` appreared in the results? Do you have the same problem?

**Comment by zakird** [comment]
We can't process this generically at a framework level. For example, you can get back a valid ICMP Time Exceeded message from a host on path to the destination, but is not the destination. In order to know whether a packet is valid, you must have application layer logic (e.g., `validate_packet`) but this would generally this type of check would be done at a framework level. Likely the right thing to do is to provide a closure to validate_packet that you can use to check whether an IP was allowed.

**Comment by zakird** [comment]
Looking at this code, I think I'd be willing to add this check anyway because `validate_gen` is already kinda screwed up here.

**Comment by jhart-r7** [comment]
I can confirm this.  It seems like any UDP datagram seen on the wire during the scan that has the same source port as the destination port we scanned, and if it passes the output filter, it will be returned as a valid/open response, regardless of whether or not the source address is blacklisted or if we even sent a probe there in the first place.
