### ISSUE TITLE
"zmap: could not detect default gateway address for 0." on VPS with strange interfaces

### ISSUE THREAD

**Issue by sanderjo** [zmap/zmap#35]
(git version of zmap, which BTW reports "zmap 1.0.0".)

Summary:
On a VPS, with a non-normal ifconfig, I get strange results from zmap which I cannot solve with -i nor -G

Long story:

On a VPS, I get:

root@superdoos:~# zmap -p 80 -N 10 -B 1M -o -
Aug 20 18:22:20.820 [INFO] zmap: started
Aug 20 18:22:20.899 [FATAL] zmap: could not detect default gateway address for 0. Try setting default gateway mac address (-G).
root@superdoos:~#

My ifconfig shows:

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:5.2.2.1  P-t-P:5.2.2.3  Bcast:0.0.0.0  Mask:255.255.255.255

(public IPv4 address a bit altered)

Specifying "-i venet0:0" or "-i venet0:0" results in the same problem.

Additionally specifying -G results in another error message, a high ETA and no useful ports found:
# zmap -p 80 -N 10 -B 1M -o - -i venet0 -G 00:00:00:00:00:00

Aug 20 18:27:12.031 [INFO] zmap: started
SIOCGIFADDR: Invalid argument
 0:01 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%
 0:02 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%
 0:03 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%
 0:04 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%
 0:05 0% (68 years left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%
 0:06 0% (68 years left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%
 0:07 0% (68 years left); send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: -nan%

**Comment by brammittendorff** [comment]
Same issue here, masscan to. I juse evilscan now: https://github.com/eviltik/evilscan

**Comment by roeea2** [comment]
So even though this issue as closed and I remember @zakird said in another post that this issue will not be fixed.
I found a way to baypass it and my solution is to install a docker on the VPS which is using a none kvm method.

It worked from within the docker (don;t use --vpn)
