### ISSUE TITLE
[FATAL] get-iface-ip: ioctl failure: No such device

### ISSUE THREAD

**Issue by mark7191** [zmap/zmap#357]
Trying to start the zmap scan, i'm getting error 

> [FATAL] get-iface-ip: ioctl failure: No such device

Upon checking the interfaces, there is no eth0 showing up. Only lo, em1 and em2.

Using -i em2 is the only way to make it work, however i'm getting errors for some reason

> [WARN] monitor: Dropped 425 packets in the last second, (425 total dropped (pcap: 425 + iface: 0))

Is this an issue and how could i resolve it?

**Comment by dadrian** [comment]
It sounds like there's two issues here: one is that ZMap does not autodetect which interface to use correctly, and the other is that packets are getting dropped. ZMap delegates to libpcap for detecting interfaces---if you run tcpdump does it also have issues unless you manually set the interface? If so, there's probably nothing we can do about that.

As for the packets getting dropped, you might be running ZMap too fast for your NIC or hardware. Try rate limiting with `-r` to 100000pps or less.

**Comment by alievinfo** [comment]
Use zmap -i interface name
