### ISSUE TITLE
Fragment reassembly

### ISSUE THREAD

**Issue by tsellers-r7** [zmap/zmap#358]
Based on my understanding of the code it looks like Zmap doesn't do fragment reassembly prior to handle_packet ( recv.c ) handing the packet up to the probe module's process_packet function. Is this correct?  

while I can see how this wouldn't have been needed or caused a problem in the past given the original design and usage, I'm currently running into issues with this when handling large responses to UDP probes.

Are there currently any plans for implementing fragment reassembly in Zmap?  Would there be any concerns would doing so?

Thanks much.

**Comment by zakird** [comment]
You are correct---we do not currently reassemble packet fragments. Prior experiments for the protocols we've scanned have resulted in only a negligible number of packets being fragmented. There is data provided in --metadata-file if you're trying to measure this.

At this point, we do not have any plans on adding support. However, I'm not strictly against the idea. We would, however, need to figure out a lightweight manner of doing this that would wouldn't slow down other scans. This shouldn't be too difficult to do given that the first packet will tell you whether there are additional fragments coming. If you think you can implement a reasonable solution, we'd happily consider.

**Comment by zakird** [comment]
This hasn't been touched in years and given that the core team has no plans to address this issue, closing.
