### ISSUE TITLE
fatal error: parser.h: No such file or directory

### ISSUE THREAD

**Issue by btro** [zmap/zmap#359]
So I've downloaded several versions (git, 2.1.1 and 2.1.0) and always I receive the following error during compilation:
`Building C object src/CMakeFiles/zmap.dir/shard.c.o
/home/ubuntu/sslscan/src/github.com/zmap/zgrab/zmap/zmap-2.1.0/src/filter.c:12:20: fatal error: parser.h: No such file or directory
 #include "parser.h"
                    ^
compilation terminated.
`

I followed the installation instructions and installed the dependencies via 
`sudo apt-get install build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev`
then 
`cmake -DENABLE_DEVELOPMENT=OFF .`
`make -j4`
and make fails. I need ztee, which is not included in the apt package of my Ubunutu distribution and I hope to receive it from the source install. 

Can someone help me?

this seemt to be related to #271 
therefore my details:
byacc - 1.9 20140101
cmake version 2.8.12.2
Kernel: Linux 3.13.0-92-generic x86_64
Ubuntu 14.04.4 LTS

**Comment by zakird** [comment]
I believe that parser.h is generated by byacc. Can you double check that you can run flex and byacc on your machine?

What happens when you run:

`flex -o "src/lexer.c" --header-file="src/lexer.h" "src/lexer.l"`

and

`byacc -d -o "src/parser.c" "src/parser.y"`

**Comment by btro** [comment]
weird... after a reboot it worked now. Btw: this issue did not happen on debian 8. 
It is a Amazon EC2 instance. Thanks for your input though.

for the record though, the output was:
`ubuntu@XXXXX:~/zmap-2.1.1$ flex -o "src/lexer.c" --header-file="src/lexer.h" "src/lexer.l"
ubuntu@XXXXX:~/zmap-2.1.1$ byacc -d -o "src/parser.c" "src/parser.y"
`
