### ISSUE TITLE
module_tcp_synscan.c functions should be static

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zmap#370]

**Comment by dadrian** [comment]
IIRC they can't be, because the probe_module_t is a publicly exposed struct and contains pointers to each of the functions, which therefore need to be linkable from outside the synscan module.

**Comment by zakird** [comment]
That's not true, and many of ours are:

https://github.com/zmap/zmap/blob/master/src/probe_modules/module_tcp_cisco_backdoor.c
https://github.com/zmap/zmap/blob/master/src/probe_modules/module_dns.c
https://github.com/zmap/zmap/blob/master/src/probe_modules/module_icmp_echo.c

**Comment by dadrian** [comment]
@zakird++
@dadrian--
