### ISSUE TITLE
zmap defaults number of senders to (num_cores - 2), not 1 as documented

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zmap#374]
zmap help text:

>   -T, --sender-threads=n        Threads used to send packets  (default=`1')

This text is generated here: https://github.com/zmap/zmap/blob/master/src/zopt.ggo.in#L169

However the zmap.c does not honor the default and instead defaults to num_cores - 2 if the option is not set:

https://github.com/zmap/zmap/blob/master/src/zmap.c#L757

I'm happy to fix this with a PR but I'm not sure what the right behavior is. Should the default be 1 or num_cores - 2?

**Comment by zakird** [comment]
I think that the right behavior is (cores - 2) as this is what providers the speed guarantees that ZMap does 1gigE without any configuration. Would you be willing to update the documentation?

**Comment by paul-pearce** [comment]
To document a discussion that happened offline: We're going with changing the default behavior to match the current documentation: not specifying -T results in 1 sender thread.
