### ISSUE TITLE
how to make a pkt?

### ISSUE THREAD

**Issue by kolet** [zmap/zmap#379]
hi there, i've been using this awasome tools , i did read the read me and manual but their is no mention on how to make a pkt file, ive been reading some issue and some one else asked the same question as i did.
the answer that he got was to sniff the packtes through wireshark and save it as raw
so i did all things and its not working for me, i will appriciate if some one could explain from a-z on how to make a pkt,
i am trying to make a pkt dns payload
so here is what i did, tell me what i am doing wrong.
http://imgur.com/a/bki8J
so this is what i am doing
i right click the stream, i follow the  udp/tcp stream , selecting what i sent (37bytes) to the dns server, changing to raw where it says "show data as", and saving it.
i did that for both of the stream showed in the pic since i dont know which one i need to save, anyway its not working with both of them.. :(
hopefully one of u could help me and help others , perhaps i am not the only one who want to make a pkt file ;)

**Comment by dadrian** [comment]
The `.pkt` files have the raw binary content of the UDP payload, starting after the UDP header. You can make this using your favorite hex editor / tcpdump / wireshark. If you need more specific instructions, look at the documentation for those tools.
