### ISSUE TITLE
Logging to syslog hardcoded for zblacklist/ziterate

### ISSUE THREAD

**Issue by hdm** [zmap/zmap#388]
The zblacklist and ziterate programs (in 2.1.1 & master) are hardcoded to log to syslog. This is problematic when doing large filtering operations due to creation of a huge amount of log data and CPU usage of the system logging daemons.

zblacklist.c
```
if (log_init(logfile, conf.verbosity, 1, "zblacklist")) {
```

ziterate.c
```
if (log_init(logfile, conf.verbosity, 1, "ziterate")) {
```

Can this behavior be changed to default to no syslog logging for these tools, or configured via a command-line option or environment variable instead?

**Comment by dadrian** [comment]
I don't see any reason why we can't add --disable-syslog to match ZMap.
