### ISSUE TITLE
get only the destination ip after shuffling targets

### ISSUE THREAD

**Issue by vayneYang** [zmap/zmap#390]
Hello!
I hope to use the function of breaking targets. Then I found the --dryrun option. 
And `grep daddr | awk -F'daddr: ' '{print $2}' | sed 's/ |.*//;'`
But it seems like it will still go through the stage of sending packets( not actually send out ) and won't give me the result immediately. Can anyone tell me what should I do?
Thanks!

**Comment by zakird** [comment]
I don't understand what you mean. To clarify --dry-run does not send any
packets. If you want to only generate IPs you should use ziterate.

**Comment by vayneYang** [comment]
Haha, I means `--dryrun` will still go through the stage of building packets. (Poor ability of expression..) And I found a similar issue in #333 by the keyword 'ziterate'. Thanks a lot !
