### ISSUE TITLE
zmap unable to write to file

### ISSUE THREAD

**Issue by beruhan** [zmap/zmap#400]
**I run zmap get the error 'csv: unable to write to file',I saved the data to /var/ directory,follow is zmap log.**
``Dec 14 18:17:26.176 [WARN] monitor: Dropped 240 packets in the last second, (46282 total dropped (pcap: 46282 + iface: 0))
Dec 14 18:17:28.852 [WARN] monitor: Dropped 338 packets in the last second, (46796 total dropped (pcap: 46796 + iface: 0))
Dec 14 18:17:31.010 [WARN] monitor: Dropped 324 packets in the last second, (47509 total dropped (pcap: 47509 + iface: 0))
Dec 14 18:17:32.734 [WARN] monitor: Dropped 480 packets in the last second, (48363 total dropped (pcap: 48363 + iface: 0))
Dec 14 18:17:33.143 [WARN] monitor: Dropped 259 packets in the last second, (48716 total dropped (pcap: 48716 + iface: 0))
Dec 14 18:17:36.628 [WARN] monitor: Dropped 273 packets in the last second, (49140 total dropped (pcap: 49140 + iface: 0))
Dec 14 18:17:38.661 [WARN] monitor: Dropped 221 packets in the last second, (49800 total dropped (pcap: 49800 + iface: 0))
Dec 14 18:17:40.355 [WARN] monitor: Dropped 268 packets in the last second, (50271 total dropped (pcap: 50271 + iface: 0))
Dec 14 18:20:03.461 [FATAL] csv: unable to write to file @zakird @dadrian

**Comment by beruhan** [comment]
the version I used is v2.1.1 @zakird

**Comment by beruhan** [comment]
and this is my vps config.  @zakird @dadrian 
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           799M  8.6M  790M   2% /run
/dev/xvda1      394G  2.7G  375G   1% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           799M     0  799M   0% /run/user/1000

**Comment by beruhan** [comment]
zmap -p 80 -o - -b /root/iots0.1/blacklist.conf -w /root/iots0.1/global_ip -B 30M -c 8 -M tcp_synscan -l /var/metadata/20161214T164559/80-http-banner-ipv4_full-20161214T1646-zmap-log.log -m /var/metadata/20161214T164559/80-http-banner-ipv4_full-20161214T1646-zmap-metadata.json 2>/dev/null | ztee /var/metadata/20161214T164559/80-http-banner-ipv4_full-20161214T1646-zmap-results.csv | zgrab --port=80 --http="/" --output-file=- --gomaxprocs=3 --http-max-redirects=3 --senders=2000 --timeout=5 --log-file=/var/metadata/20161214T164559/80-http-banner-ipv4_full-20161214T1646-zgrab-log.log --metadata-file=/var/metadata/20161214T164559/80-http-banner-ipv4_full-20161214T1646-zgrab-metadata.json 2>/dev/null | tee /var/metadata/20161214T164559/80-http-banner-ipv4_full-20161214T1646-zgrab-results.json | java -jar /root/iots0.1/lib/jar/matchapp.jar "match-ipv4_full-20161214T164559" 80 "HTTP" TCP 0 2>match.log @zakird

**Comment by dadrian** [comment]
@beruhan Stop tagging individual contributors.
