### ISSUE TITLE
Hitting some kind of bottleneck, connection isn't anywhere close to saturated

### ISSUE THREAD

**Issue by laptopdude90** [zmap/zmap#408]
I'm trying to do a simple scan of the internet, just to make sure I can get zmap working properly. Even with no limit set, I'm only sending roughly 7Kp/s, or about 10Mbps out. I have a 50Mbps connection, so there's a lot more for it to work with.

The server it is running on has 2 CPUs(It's a virtual machine), but it never makes it above 60% saturation. The modest 2GB of RAM I have allocated don't get used up, only 500MB is needed at a time.

My router is a white box running pfsense. The CPU and RAM aren't overused on it either, but I did notice that the state table fills up quickly. I've tried tripling its maximum size, but it has had no effect on the throughput. 

Any help would be appreciated here, I'm not experienced with networking on this scale.

**Comment by dadrian** [comment]
Can you share what command you're running?

**Comment by laptopdude90** [comment]
Sure. 

 sudo zmap -p 80

**Comment by dadrian** [comment]
Try adding `-T 1` to limit to one thread, and then play with `-r` to set a rate roughly equivalent to your bandwidth. Start low, and see how high you can get.

**Comment by paul-pearce** [comment]
If you're running off the head of master, `-T 1` is now the default. Btw.

**Comment by laptopdude90** [comment]
Aha! The single thread was eating up one CPU core. Running with 10 threads causes 100% CPU usage, and it scans at 40Kp/s now. I'll add 4 more cores and report back.

**Comment by laptopdude90** [comment]
Okay, so now I'm getting a good 800-900Kp/s(Now using a VPN, my network became a bottleneck around 30 or 40). I'm only getting a 0.02% hit rate on port 80. 

-r 500: 1.3%
-r 5000: 1.3%
-r 50000: 0.55%
-r 500000: 0.05%
-r 5000000: 0.02%

**Comment by dadrian** [comment]
I anticipate that your upstream or hypervisor is dropping packets. A single-core non-VM machine can easily hit >1M PPS with only 1 thread.

**Comment by laptopdude90** [comment]
Thanks. Do you think it's more likely the VPN I'm using, or the hypervisor? Is there any easy way to tell?

**Comment by laptopdude90** [comment]
By the way, thanks so much for the help. I really wouldn't be able to get anywhere without you, and I'm immensely grateful. I feel like you don't get the appreciation you deserve, like a lot of people who help end users, so I just wanted to let you know it's incredibly useful. Again, thank you so much :)

**Comment by dadrian** [comment]
The lack of send speed is probably a VM issue, the missing packets are probably your upstream.

Thanks for the kind words :)
