### ISSUE TITLE
Banner grab on HTTPS services?

### ISSUE THREAD

**Issue by mackwage** [zmap/zmap#412]
What is best syntax to use to banner grab against an HTTPS service? 

`zmap -p 443 --output-fields=*  |ztee results.csv |./zgrab --port 443 -tls -banners --output-file=banners.json`

This results in a blank banners file. If I add the http then I logs the http app response whereas I am just looking for the service banner.

**Comment by mackwage** [comment]
I should note that I purposely removed the IP from the command line :)

**Comment by dadrian** [comment]
That command looks fine, but HTTPS doesn't have a service banner.
