### ISSUE TITLE
Zmap how to scan the specified IP segment text

### ISSUE THREAD

**Issue by 13145202427** [zmap/zmap#413]
For example: zmap -p 123 -M udp --probe-args=file:ntp_123_monlist.pkt -o monlist_fingerprint.txt
This command is to scan a single IP segment
If I want to scan a lot of IP segment, put it in the scan.txt how to scan it
scan.txt contents are as follows
36.96.0.0/11
36.128.0.0/10
36.192.0.0/11
59.191.240.0/20
59.192.0.0/10
60.0.0.0/11
110.240.0.0/12
111.0.0.0/10
222.16.0.0/12
222.32.0.0/11
222.64.0.0/11
183.0.0.0/10

How do I scan this text
Like this？：
zmap -p 123 -M udp --probe-args=file:scan.txt -o monlist_fingerprint.txt

Please help me correct, write the correct order, thank you very much

**Comment by zakird** [comment]
You want to use --whitelist.

**Comment by 13145202427** [comment]
How to operate?Can you give an example?

**Comment by zakird** [comment]
``--whitelist-file=scan.txt``

**Comment by 13145202427** [comment]
zmap -p 123 -M udp --whitelist-file=scan.txt -o monlist_fingerprint.txt
Is like this?

**Comment by zakird** [comment]
That looks fine.

**Comment by 13145202427** [comment]
ok，thank you. i will test
