### ISSUE TITLE
Parsing original IP header within ICMP error message payload

### ISSUE THREAD

**Issue by sheharbano** [zmap/zmap#418]
The following line in the files below assumes that sizeof(struct icmp) == 8):

struct ip *ip_inner = (struct ip *) &icmp[1];

https://github.com/zmap/zmap/blob/master/src/probe_modules/module_icmp_echo_time.c#L129
https://github.com/zmap/zmap/blob/master/src/probe_modules/module_icmp_echo.c#L116

This does not correctly extract the original IP header within ICMP error message payload. 

I think this should be:

struct ip *ip_inner = (struct ip*) ((char *)icmp + 8); 
// Assuming here that ICMP header is 8 bytes long which is the case for ICMP error messages

**Comment by zakird** [comment]
Fixed by #424
