### ISSUE TITLE
Bug of could not detect GW MAC address

### ISSUE THREAD

**Issue by dragonkid** [zmap/zmap#421]
I did have the MAC address of gateway in my ARP cache table, and I also tried to run `arp <gateway_ip>`. But the error message continued.

```
Apr 12 14:56:35.997 [FATAL] zmap: could not detect GW MAC address for 10.11.11.254 on eth0. Try setting default gateway mac address (-G), or run "arp <gateway_ip>" in terminal.
```

I recognized that I have a large ARP cache table with 117 records, but the method of `get_hw_addr` in `get_gateway-linux.h:95` only read 8192 bytes of it. When I expand the buf size to 16384, the error disappeared.

I think this was not the right way to fix this error, any suggestions?

**Comment by dadrian** [comment]
Arguably, we should extend `read_nl_socket` to handle arbitrary length responses, but I don't particularly want to introduce dynamic memory management. I don't think I would be opposed to a PR that doubled the size of that buffer.

@zakird thoughts?

**Comment by zakird** [comment]
I don't think this is worth it. Let's just make it like like 64KB and move on.
