### ISSUE TITLE
Document ztee CSV and JSON handling in the manpage

### ISSUE THREAD

**Issue by cdzombak** [zmap/zmap#429]
`ztee` has some support for working with CSV and JSON, but [its manpage](https://github.com/zmap/zmap/blob/4784fb1754b5775bd7b0a3e23b9cd3c2d9f3f5d4/src/ztee.1.ronn) doesn't mention this at all.

(I can't find anything about it on the wiki, either.)

**Comment by zakird** [comment]
@cdzombak would be willing to tackle this for ZMap 3.0 release? We're working on cleaning out a bunch of these issues.

**Comment by cdzombak** [comment]
@zakird yes, but I don't know how the JSON handling works, only CSV and `--raw` mode.

**Comment by zakird** [comment]
Neither do I :|

**Comment by zakird** [comment]
I'm not honestly sure if JSON handling actually exists

**Comment by cdzombak** [comment]
https://github.com/zmap/zmap/blob/master/src/ztee.c#L234 and https://github.com/zmap/zmap/blob/master/src/ztee.c#L124 seem to imply it's not implemented. I don't know what it is/was supposed to do.

**Comment by dadrian** [comment]
If it doesn't exist, remove all references to it from the docs and make sure we're not linking against libjson, etc.

**Comment by cdzombak** [comment]
Will do.
