### ISSUE TITLE
zmap --status-updates-file param seems unstable

### ISSUE THREAD

**Issue by mawenlong3** [zmap/zmap#431]
zmap -u param seems unstable,I use the following command,`zmap -p 80 --output-fields=* -b -B 30M -l zmap-log.log -m zmap-metadata.json -u zmap-status.csv --quiet`, it often occured the error 'could not open output file zmap-status.csv',I need to run many times to succeed.I have used the sudo

**Comment by dadrian** [comment]
I've heard varying reports of this in the past, but unfortunately I don't remember the workaround at the moment. I'll try to look into this soon.

**Comment by mawenlong3** [comment]
yeah,thanks for your reply,Looking forward to you fix the problem,

**Comment by dadrian** [comment]
Can you try ensuring the status updates file doesn't already exist before you run the scan?

**Comment by mawenlong3** [comment]
yes,i'msure ,I deleted the status file before each run. It excute sometimes successful,sometimes failed, I was puzzled by that
