### ISSUE TITLE
Travis should perform builds without zmap config files

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zmap#435]
It looks like PR #428 totally broke gateway detection. The only way it worked (in tests and via travis) was the presence of a zmap global config. It seems wise to consider changes to Travis to avoid this kind of failure in the future.

**Comment by dadrian** [comment]
So this doesn't actually matter in Travis, since we don't _run_ ZMap, we just build it. The real issue here is we don't have automated regression testing of functionality.
