### ISSUE TITLE
Blacklisted host that does not resolve to an IP causes error.

### ISSUE THREAD

**Issue by bvandersloot** [zmap/zmap#436]
https://github.com/zmap/zmap/blob/master/lib/blacklist.c#L131

getaddrinfo will return non-zero for a host that resolves to no IP. The program promptly throws up its hands and quits. A better behavior is to just ignore that entry.

**Comment by cdzombak** [comment]
Per an internal discussion, the existing flag `--ignore-blacklist-errors` should cause these lookup errors to be ignored. 

The _default_ `zblacklist` behavior should not change.
