### ISSUE TITLE
multiple ports support?

### ISSUE THREAD

**Issue by ghost** [zmap/zmap#44]
can add multiple ports function?

**Comment by lupus721** [comment]
it's still not suport multiple ports ?

**Comment by dkran** [comment]
Ouch. I like zmaps randomization much more, but the multiple port thing is a killer.

**Comment by dadrian** [comment]
@dkran What's your use case for multiple-port scanning?

**Comment by dkran** [comment]
Any service can conceivably be run on any port. So to get an accurate census of the internet, zmap's randomization and collection of tools is required, but service discovery on "1-65,535" would give a way more accurate result.  I can scan the ipv4 address space from home in a short time on one port, but my accuracy would suffer due to this.  Plus services running on odd ports is what makes the internet interesting.  Like the botnets that constantly try to brute-force me. I understand that's a massive, massive increase on the time it would take, but with enough shards and processing we would have a complete picture rather than a "guess" that everyone is running certain services on certain ports.  And if they're secure.

**Comment by ekodikara** [comment]
> Any service can conceivably be run on any port. So to get an accurate census of the internet, zmap's randomization and collection of tools is required, but service discovery on "1-65,535" would give a way more accurate result. I can scan the ipv4 address space from home in a short time on one port, but my accuracy would suffer due to this. Plus services running on odd ports is what makes the internet interesting. Like the botnets that constantly try to brute-force me. I understand that's a massive, massive increase on the time it would take, but with enough shards and processing we would have a complete picture rather than a "guess" that everyone is running certain services on certain ports. And if they're secure. @dadrian
> 
> I originally started a github repo using masscan to discover ips, then had multiple nmap nodes that could be run from any computer in the world to process all the ports, using nodejs and rethinkdb, along with those command line tools. Although much slower, it had much higher accuracy on a single IP. I even wrote a parser for nmap xml to json since nothing existed in the JS ecosystem.
> 
> edit: Did a test last night, and most of the ports that came up were not standard HTTP ports but entirely odd ports (used masscan at a rate of 60MB / sec on ports 1-65535 and was getting thousands of results on odd ports. I've stored them in the rethinkdb queue and I'll use nmap service discovery on it, passing back and forth with websockets. Unfortunately rethinkdb didn't handle that rate of input well, I need more RAM or servers, but I'll solve this problem. I guess there's no perfect tool for this job yet.

How many minutes took to scan the ipv4 using one port : ex port 80 ? (better to add the pc spec's also)

**Comment by LCHOICEzz** [comment]
> Any service can conceivably be run on any port. So to get an accurate census of the internet, zmap's randomization and collection of tools is required, but service discovery on "1-65,535" would give a way more accurate result. I can scan the ipv4 address space from home in a short time on one port, but my accuracy would suffer due to this. Plus services running on odd ports is what makes the internet interesting. Like the botnets that constantly try to brute-force me. I understand that's a massive, massive increase on the time it would take, but with enough shards and processing we would have a complete picture rather than a "guess" that everyone is running certain services on certain ports. And if they're secure. @dadrian
> 
> I originally started a github repo using masscan to discover ips, then had multiple nmap nodes that could be run from any computer in the world to process all the ports, using nodejs and rethinkdb, along with those command line tools. Although much slower, it had much higher accuracy on a single IP. I even wrote a parser for nmap xml to json since nothing existed in the JS ecosystem.
> 
> edit: Did a test last night, and most of the ports that came up were not standard HTTP ports but entirely odd ports (used masscan at a rate of 60MB / sec on ports 1-65535 and was getting thousands of results on odd ports. I've stored them in the rethinkdb queue and I'll use nmap service discovery on it, passing back and forth with websockets. Unfortunately rethinkdb didn't handle that rate of input well, I need more RAM or servers, but I'll solve this problem. I guess there's no perfect tool for this job yet.

I agree with you that the distribution scan mode can find more alive IPs and ports in my test data. Meanwhile，I want to say that the scan results of Zmap  are effected by upstream routers. Last 2 years I rent some VPS to scan global IP addresses, only 30Mbps can get property response data.  So if you want to scan global IPv4 addresses and 65535 ports, you'd better rent lots of nice servers or hosts. :)

**Comment by LCHOICEzz** [comment]
sry, change property to properly. :)

**Comment by OsamaMahmood** [comment]
any update on the multi-port scan support?

**Comment by parthmalhotra** [comment]
Still waiting for multiport support :)

**Comment by dadrian** [comment]
We will implement multiple ports sometime after the pandemic, when the ZMap team can meet up in person again.
