### ISSUE TITLE
Donwload file on 200 response

### ISSUE THREAD

**Issue by JonhSilver** [zmap/zmap#440]
It is possible with Zmap to check targets for file Robots.txt and download it if exist?

**Comment by cdzombak** [comment]
This isn't something zmap by itself does.

You could use zmap to get a list of hosts with a particular port (80, 443) open, then use that list of hosts as input for [zgrab](https://github.com/zmap/zgrab). You'd ask zgrab to request `robots.txt` with the `--http` option, like: `zgrab --http=/robots.txt`.

**Comment by JonhSilver** [comment]
But how fast is Zgrab? How many targets it can check in 1 day?

**Comment by cdzombak** [comment]
> how fast is Zgrab? How many targets it can check in 1 day?

Its speed depends exactly what kind of grab you’re running. On a fast enough server with a 1Gbps network connection, you should be able to do this in under a day.
