### ISSUE TITLE
CSV output only includes header if more than one field is present

### ISSUE THREAD

**Issue by jhart-r7** [zmap/zmap#445]
There may be some pseudo-CSV standard where this functionality is expected, but with zmap, when you use the CSV output plugin, if there is only one field in the output, no header is included in the output.  When there is more than one field in the output, a header is included.

This can make some workflows that utilize zmap CSV a little more complicated.  Example:

```
### default output for TCP csv includes just one field, no header
$  /usr/local/sbin/zmap -v1 -qp 3389 -O csv  192.168.1.0/24               
192.168.1.1
192.168.1.42
192.168.1.41
192.168.1.40
192.168.1.44
192.168.1.57
192.168.1.63
192.168.1.38
192.168.1.39
^C
### explicitly asking for the addr field, we still get no header
$  /usr/local/sbin/zmap -v1 -qp 3389 -O csv  192.168.1.0/24 -f saddr
192.168.1.1
192.168.1.44
192.168.1.57
192.168.1.38
192.168.1.42
192.168.1.41
192.168.1.39
192.168.1.40
192.168.1.63
^C
### explicitly asking for the saddr and daddr field, we now get a header
$  /usr/local/sbin/zmap -v1 -qp 3389 -O csv  192.168.1.0/24 -f saddr,daddr
saddr,daddr
192.168.1.44,192.168.1.45
192.168.1.39,192.168.1.45
192.168.1.41,192.168.1.45
192.168.1.38,192.168.1.45
192.168.1.42,192.168.1.45
192.168.1.40,192.168.1.45
192.168.1.1,192.168.1.45
192.168.1.57,192.168.1.45
192.168.1.63,192.168.1.45
```

**Comment by dadrian** [comment]
If I remember correctly, we do this so that the common case of `zmap | zgrab` or equivalent only has IP addresses sent through the pipe. Also, usually when there's only one column, it's considerably easier to handle the output with standard Unix tools if you don't have the header row.

I suspect we could add an option to always show or never show the CSV header. @zakird thoughts?

**Comment by paul-pearce** [comment]
My $0.02. IIRC, if you don't specify an output module, it gives you a legacy "common case" CSV-like output. Specifying CSV then gives you a different output.

I'd leave this behavior if no output module is specified, but if CSV is specified, output the header.

**Comment by zakird** [comment]
+1 @pearce

**Comment by dadrian** [comment]
I like that as well.

**Comment by jhart-r7** [comment]
Agreed.  That solution works for me.

@dadrian, regarding one column being easier, I agree.  In this case the things downstream from zmap read in the CSV and need to infer the column/attribute name from the header.  My only work around right now is to request more fields than I need such that I can get at the field that I want and I can just ignore the extraneous fields.

**Comment by jhart-r7** [comment]
thanks guys!
