### ISSUE TITLE
CentOS Linux release 7.3.1611 get-iface-ip: ioctl failure: No such device

### ISSUE THREAD

**Issue by happyalexkg** [zmap/zmap#448]
Hello
I build from source zmap
with :
cmake -DWITH_PFRING=ON -DENABLE_DEVELOPMENT=OFF .
make
when i tring to run zmap with zc:
./zmap -p 80 -o data.csv -i zc:enp6s0 --cores 15 --bandwidth=1G
**Aug 22 18:23:39.344 [FATAL] get-iface-ip: ioctl failure: No such device** -- why it's happend ?

**info:**
 cat /proc/net/pf_ring/dev/enp6s0/info
Name:         enp6s0
Index:        4
Address:      00:25:90:02:47:38
**Polling Mode: NAPI/ZC**
Type:         Ethernet
Family:       Intel e1000e
TX Queues:    1
RX Queues:    1
Num RX Slots: 0
Num TX Slots: 4096

[root@localhost src]# lsmod | grep zc
e1000e_zc             249997  0
ptp                    19231  1 e1000e_zc

[root@localhost src]# ifconfig  -a | grep enp
enp6s0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
enp7s0: flags=4355<UP,BROADCAST,PROMISC,MULTICAST>  mtu 1500

----------------------------------
Result of execution if use just name of interface without zc
Aug 22 18:23:19.347 [INFO] zmap: output module: csv
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 751103 745 Kp/s (744 Kp/s avg); recv: 7039 6.98 Kp/s (6.97 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.94%
 0:02 0%; send: 1514495 763 Kp/s (754 Kp/s avg); recv: 15698 8.66 Kp/s (7.81 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.04%
 0:03 0%; send: 2328575 814 Kp/s (774 Kp/s avg); recv: 24631 8.93 Kp/s (8.18 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.06%
 0:04 0%; send: 3158015 829 Kp/s (788 Kp/s avg); recv: 33775 9.14 Kp/s (8.42 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.07%
 0:05 0% (1h18m left); send: 3941887 784 Kp/s (787 Kp/s avg); recv: 42902 9.13 Kp/s (8.56 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.09%

But i have 1Gb networking and would like to use all speed or 80%

**Comment by dadrian** [comment]
Hi,

You don't need ZC to get 1Gbps networking, just up the number of threads (`-T 2` or `-T 4`). In the ZC case, it sounds like ZMap can't detect the IP assigned to the interface. If ZMap can't detect the IP of an interface, you can pass it as a command line option `--source-ip`. Same for source MAC, gateway MAC, etc. See `--help` for a description of those options.

**Comment by Shadowlilbro** [comment]
Get-iface-ip: ioctl failure: No such device

I'm getting same error accept I don't know what to do at all
