### ISSUE TITLE
Building C object src/CMakeFiles/zmap.dir/fieldset.c.o

### ISSUE THREAD

**Issue by chaozai1028l** [zmap/zmap#473]
hi,
   please, look this question. 
   os : centos 7 x64
   question:
[ 23%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
/data/ZMAP/zmap/src/fieldset.c:15:20: fatal error: unistr.h: No such file or directory
 #include <unistr.h>
                    ^
compilation terminated.
make[2]: *** [src/CMakeFiles/zmap.dir/fieldset.c.o] Error 1
make[1]: *** [src/CMakeFiles/zmap.dir/all] Error 2
make: *** [all] Error 2

if os is ubuntu ,have to install libunistring-dev  but in centos 7    
yum install libunistring-dev  
it will display no-package available, please help me :)

**Comment by cdzombak** [comment]
@chaozai1028l per [INSTALL](https://github.com/zmap/zmap/blob/master/INSTALL.md), on CentOS the library name is `libunistring-devel`.
