### ISSUE TITLE
Packet rate limit option (-r) not respected after a point, sometimes

### ISSUE THREAD

**Issue by jhart-r7** [zmap/zmap#475]
In some testing of zmap with the `-r` and `-B` options, I observed that, at least with my systems, once the effective packet rate reaches ~244,000/s, the packet/s or bandwidth rate limit is ignored and zmap runs unbounded.

We run a UDP scan with something like:

```
/usr/local/sbin/zmap -i eth0 -S <sources> -s <port>  -v1 -b <blacklist_path> -r 350000 --output-filter='success = 1 && repeat = 0 && sport = <port>' -p <port>  -M udp -O csv -f timestamp_ts,saddr,sport,daddr,dport,ipid,ttl,data --probe-args=file:<some_file>
```

TCP studies are run similarly but with the respective TCP options passed instead.  The same issues is observed there.

The 350000 number was presumably chosen at some point in the past as a result of hardware testing.

In testing, however, I've observed that this rate is not respected:

```
 0:00 0%; send: 105 0 p/s (2.84 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:00 0%; send: 359 347 Kp/s (9.52 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 483036 482 Kp/s (465 Kp/s avg); recv: 95 94 p/s (91 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:02 0%; send: 967710 484 Kp/s (475 Kp/s avg); recv: 198 102 p/s (97 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:03 0%; send: 1452376 484 Kp/s (478 Kp/s avg); recv: 303 104 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:04 0%; send: 1936978 484 Kp/s (480 Kp/s avg); recv: 402 98 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:05 0% (2h06m left); send: 2421597 484 Kp/s (481 Kp/s avg); recv: 502 99 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:06 0% (2h06m left); send: 2906187 484 Kp/s (481 Kp/s avg); recv: 594 91 p/s (98 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:07 0% (2h06m left); send: 3388092 482 Kp/s (481 Kp/s avg); recv: 688 93 p/s (97 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:08 0% (2h06m left); send: 3872806 485 Kp/s (482 Kp/s avg); recv: 792 103 p/s (98 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:09 0% (2h06m left); send: 4357405 484 Kp/s (482 Kp/s avg); recv: 898 105 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:10 0% (2h06m left); send: 4842041 484 Kp/s (482 Kp/s avg); recv: 995 96 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:11 0% (2h06m left); send: 5326684 484 Kp/s (482 Kp/s avg); recv: 1087 91 p/s (98 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:12 0% (2h06m left); send: 5811381 485 Kp/s (483 Kp/s avg); recv: 1160 72 p/s (96 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:13 0% (2h06m left); send: 6296071 484 Kp/s (483 Kp/s avg); recv: 1265 104 p/s (96 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:14 0% (2h05m left); send: 6780748 484 Kp/s (483 Kp/s avg); recv: 1366 100 p/s (97 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:15 0% (2h05m left); send: 7265344 484 Kp/s (483 Kp/s avg); recv: 1484 117 p/s (98 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:16 0% (2h05m left); send: 7750032 485 Kp/s (483 Kp/s avg); recv: 1591 106 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
 0:17 0% (2h05m left); send: 8234624 484 Kp/s (483 Kp/s avg); recv: 1690 98 p/s (99 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
```

That pattern continues until the scan completes.  Eventually it starts dropping packets and the system becomes unreachable.

Changing to the bandwidth based limitations and I see the same behavior as the `-B` option passes `164M`, however I suspect this is more a function of the payload size.  Sure enough, with the payload size we have and that bandwidth, the effective packets/s rate is ~244,000.

I've played with the various options I'm specifying and none of them beyond `-r` or `-B` seem to have an impact on the rate issue.  It is very odd that there is a specified rate that causes the effective rate to be much higher.  I'm baffled as to what could be causing this.  The only work around I have at this point is to specify a lower rate.

Any ideas?

**Comment by paul-pearce** [comment]
Hmm. Which metric are you seeing that increases forever? The instantaneous rate bounces around a bit, but the average rate does continue to increase. Is it the average? Can you post more of the monitor log?

Does something like nload support this log-observed increase?

I think the right place to start investigating is that when you specify 244000, your instantaneous Kp/s is 244Kp/s but when you specify 245000 it becomes 484Kp/s.

What's the output of, say, `-r 300000`?

**Comment by paul-pearce** [comment]
Also, what is the network hardware for each?

**Comment by dadrian** [comment]
So, this is going to sound really crazy, but can you try changing this line to be a `uint64_t` instead of `uint32_t`? https://github.com/zmap/zmap/blob/master/src/send.c#L246

I came across this recently, and while I'm not entirely convinced this is affecting your case, I believe this is overflowing in some scans which would throw off the rate limiting.

**Comment by jhart-r7** [comment]
@dadrian thanks for the suggestion -- i tried that but saw no change.

@paul-pearce it is the send rate and average that doesn't seem to settle down.  In several tests it remained at > 500kp/s throughout the entire scan.  system 1 is "Intel Corporation I210 Gigabit Network Connection (rev 03)", system2 is "Intel Corporation 82574L Gigabit Network Connection".  I installed `nload` and observed that with `-r 244000` I see ~15-16Mb/s in, ~450Mbs/s out.  With `-r 245000` I see ~26Mb/s in, >800Mb/s out.

**Comment by paul-pearce** [comment]
I'm working my way back through the source code. Some additional thoughts:

1) Can you add -v5 -l logfile and include as much of the logfile as your comfortable with, both for 244000 and 245000. In particular, the number of threads in use.

2) Are the number of threads the same between both machines?

3) Are the blacklists the same between both machines.

Assuming I didn't miss some weird overflow bug, I'm rummaging through the iteration and sharding code, and that relies on stuff like number of threads and size of blacklist/whitelist.

**Comment by jhart-r7** [comment]
Ah, and I missed something in my initial testing -- system1 initially seemed like it was respecting the option because another scan happened to be running at the same time and sapping resources.  *Both* systems exhibit the same behavior wrt this rate option in that it is not respected.  

I'll update accordingly as I have new information

**Comment by jhart-r7** [comment]
@paul-pearce 

```
Oct 04 15:57:08.462 [DEBUG] zmap: zmap main thread started
Oct 04 15:57:08.462 [DEBUG] zmap: Loaded configuration file /etc/zmap/zmap.conf
Oct 04 15:57:08.462 [DEBUG] zmap: syslog support enabled
Oct 04 15:57:08.462 [DEBUG] zmap: requested ouput-module: csv
Oct 04 15:57:08.462 [DEBUG] fieldset: probe module does not supply application success field.
Oct 04 15:57:08.462 [DEBUG] zmap: requested output field (0): timestamp_ts
Oct 04 15:57:08.462 [DEBUG] zmap: requested output field (1): saddr
Oct 04 15:57:08.463 [DEBUG] zmap: requested output field (2): sport
Oct 04 15:57:08.463 [DEBUG] zmap: requested output field (3): daddr
Oct 04 15:57:08.463 [DEBUG] zmap: requested output field (4): dport
Oct 04 15:57:08.463 [DEBUG] zmap: requested output field (5): ipid
Oct 04 15:57:08.463 [DEBUG] zmap: requested output field (6): ttl
Oct 04 15:57:08.463 [DEBUG] zmap: requested output field (7): data
Oct 04 15:57:08.463 [DEBUG] filter: will use output filter success = 1 && repeat = 0 && sport = 123
Oct 04 15:57:08.463 [DEBUG] blacklist: no whitelist file or whitelist entries provided
Oct 04 15:57:08.471 [DEBUG] constraint: Painting value 1
Oct 04 15:57:08.504 [DEBUG] constraint: 3648720896 IPs in radix array, 2847143 IPs in tree
Oct 04 15:57:08.504 [DEBUG] constraint: 3651568039 addresses (85% of address space) can be scanned
Oct 04 15:57:08.505 [DEBUG] zmap: found gateway IP a.b.c.d on eth0
Oct 04 15:57:08.505 [DEBUG] send: gateway MAC address 00:01:e8:aa:bb:cc
Oct 04 15:57:08.505 [INFO] zmap: output module: csv
Oct 04 15:57:08.505 [INFO] csv: no output file selected, will use stdout
Oct 04 15:57:08.505 [DEBUG] csv: more than one field, will add headers
Oct 04 15:57:08.505 [DEBUG] zmap: Isomorphism: 2127832886
Oct 04 15:57:08.505 [DEBUG] send: srcip_first: a
Oct 04 15:57:08.505 [DEBUG] send: srcip_last: b
Oct 04 15:57:08.505 [DEBUG] send: will send from 25 addresses on 1 source ports
Oct 04 15:57:08.505 [DEBUG] send: using bandwidth 165000000 bits/s, rate set to 245535 pkt/s
Oct 04 15:57:08.505 [DEBUG] send: no source MAC provided. automatically detected 00:25:90:aa:bb:cc as hw interface for eth0
Oct 04 15:57:08.505 [DEBUG] send: source MAC address 00:25:90:aa:bb:cc
Oct 04 15:57:08.506 [DEBUG] zmap: Pinning receive thread to core 0
Oct 04 15:57:08.506 [DEBUG] recv: capturing responses on eth0
Oct 04 15:57:08.539 [DEBUG] recv: duplicate responses will be included in output
Oct 04 15:57:08.539 [DEBUG] recv: unsuccessful responses will be included in output
Oct 04 15:57:08.539 [DEBUG] zmap: 1 sender threads spawned
Oct 04 15:57:08.539 [DEBUG] zmap: Pinning a send thread to core 1
Oct 04 15:57:08.540 [DEBUG] zmap: Pinning monitor thread to core 2
Oct 04 15:57:08.540 [DEBUG] send: send thread started
Oct 04 15:57:08.540 [DEBUG] send: source MAC address 00:25:90:aa:bb:cc
```

Number of threads is unspecified so I assume the default.  Blacklists are identical.

**Comment by paul-pearce** [comment]
Dumb thing to suggest while I'm reading send.c and being sad, can you move to the head of master and ensure the problem continues? Also, make sure nothing new shows up in the log file while you see the increases continue.

**Comment by jhart-r7** [comment]
@paul-pearce I reproduced this at the current head of master too after seeing the sharding changes (I discovered this while using sharding but the problem persists without it).  The log file remains unchanged after that last line.

To be clear, the rate does not *increase* but it does exceed the rate that I specified and seems to hold there:

```
 6:04 5% (1h59m left); send: 176247616 484 Kp/s (484 Kp/s avg); recv: 40605 107 p/s (111 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.02%
```

**Comment by jhart-r7** [comment]
In some testing it seems like https://github.com/zmap/zmap/commit/c04bc6d060f0ce1f198ff7eda6bf1a685d3b8efa is the point where this option started malfunctioning.  I tried increasing the threads but couldn't find a value that resulted in the specified rate being respected.

🤔

**Comment by paul-pearce** [comment]
Behavior changing at that commit is not surprising, as this has something to do with sharding and number of threads, and in that commit we changed the default zmap invocation from N threads to 1.

Some things to test:

1) At c04bc6d, try specifying `-T 1` and see send rate breaks as it does at master (I suspect it will)

2) At c04bc6d with no `-T` specified, add `-v5 -l logfile` and find how many senders are being created from the log file. Go back to the head of master, and try passing `-T N` where N is that number of senders. I expect the problem goes away.

**Comment by jhart-r7** [comment]
@paul-pearce I suspect for 2  you meant before c04bc6d because at c04bc6d  it will use 1 thread if not specified.  _Before_ c04bc6d, it uses 22 senders.  When I switch to the tip of master and use `-T 22`, the problem goes away as you expected.

**Comment by paul-pearce** [comment]
I just committed some code to a debug branch, https://github.com/zmap/zmap/tree/rate_debug

We're looking at the code that actually limits send.c. It seems like _some_ assumption is being violated and we don't understand what it is.

The code in that branch adds some assertions to `src/send.c`. I don't expect any of them will fail, but it's a good starting place. 

Run it, and if things continue to escalate (no assertion failures), please go into `src/send.c` and uncomment the 4 printf's with 'XXX` in them. Run it for a few moments, and then provide me with the output of all the XXX's. I want to understand how the counters are progressing. Please do this for both send rates.

**Comment by paul-pearce** [comment]
Hmm. I somehow got it in my head you sketched this as 14.04. But you didn't.

What OS is this? How are you building zmap?

**Comment by jhart-r7** [comment]
@paul-pearce it is Ubuntu 14.04.5 LTS, zmap built from source with `cmake . && make -j4 && make install`

**Comment by paul-pearce** [comment]
@jhart-r7 k. Do give the debug branch above a try and let me know.

**Comment by paul-pearce** [comment]
@jhart-r7 are you using `-P` by any chance?

**Comment by paul-pearce** [comment]
Update: 

I'm now fairly confident I understand the error. Here's the setup.

1) Send rate limiting is controlled by a `delay` variable. This variable controls a busy loop.
2) At startup, we try to calibrate what this delay value should be. We then, through send iterations, try to converge to a value that will cause the sending thread to slow down enough.
3) There's a bug here https://github.com/zmap/zmap/blob/0258a49568d56a4f62a0c7df741f6a13df1ce0d7/src/send.c#L318 where we set delay to 1 on the first loop iteration. This causes our sendrate to spike.
4) Independent of the bug, if send rate is configured over some threshold (I think it's 2x what the box can handle, by nature of the convergence algorithim), and the delay drops to 1, we begin to misbehave.

So the fix is:

1) Fix the bug that causes us to drop to 1 immediately.
2) Fail if we hit 1, as it implicitly means were operating up against system limits. 

I pushed a fix to the `rate_debug` branch. Please deploy it and let me know if things are working properly for you. If they are, I'll float this by the others and see if we're happy. (Ideally, you'd like to support delay=1, but it makes everything else awful.)

**Comment by jhart-r7** [comment]
@paul-pearce I am not using `-P`.

I've built that `rate_debug` branch and it appears to be respecting the rate specified :)

**Comment by paul-pearce** [comment]
Great. I'll PR shortly. 

Thank you for the report and helping out! This was a nasty one.

**Comment by jhart-r7** [comment]
👍
