### ISSUE TITLE
Monitor, thread_state, iteration all incorrectly tally IPs instead of packets

### ISSUE THREAD

**Issue by paul-pearce** [zmap/zmap#478]
Well, this is awkward.

All of the code in `monitor.c` for calculating number of packets sent is based on calls to `iterator_get_sent`. This tallies `it->thread_shards[i].state.sent`. This is incredments _per IP_ in `send.c`, not per-packet.  This means when we have multiple packet streams (`-P`) we report IPs/sec, not packets/sec.

For example, at `-r 60000 -P 1` monitor reports 60Kp/s. External monitoring confirms. At `-r 60000 -P 2` monitor reports 30Kp/s, but the line rate is actually 60Kp/s, as `send.c` limits itself correctly.

I think the fix here is to multiply all the monitor statistics by `zconf.packet_streams` but this needs further thought.

Note: The types of the sent variables in `monitor.c` need to be transitioned to `uint64_t` if they begin to accurately reflect the true number of packets sent.

(A cursory glance seems to indicate recv is ok since it's from the pcap, but I didn't check the types.)

**Comment by dadrian** [comment]
This was fixed by #513
