### ISSUE TITLE
Max results (-N) option not respected exactly

### ISSUE THREAD

**Issue by jhart-r7** [zmap/zmap#479]
With a few different zmap versions, including https://github.com/zmap/zmap/commit/0258a49568d56a4f62a0c7df741f6a13df1ce0d7 and most recently with the current HEAD of master 5b33c8a9cc94ebc760eb0fe4d037771e4c1e3567, I've noticed that when running with the `-N` option to stop after receiving X results, it doesn't always stop exactly at X.  Sometimes it does, but more often than not it stops at nearly X.

Here is a sample test, scanning a fixed UDP port and telling zmap to stop after 1000 results.  As you can see, it never makes it to 1000:

```
for f in `seq 1 5`; do ./src/zmap -i eth0 -s 123 -b <blacklist> -T 22  --output-filter='success = 1 && repeat = 0 && sport = 123' -p 123  -M udp -O csv -f timestamp_ts,saddr,sport,daddr,dport,ipid,ttl,data -N 1000 --probe-args=file:<probe> -c 30 > foo 2> /dev/null && wc -l foo; done
991 foo
992 foo
987 foo
993 foo
994 foo
```

The only option (that I'm not specifying above) that seems to have any impact on how close to 1000 it gets it the `-r` option for rate limiting.  I suspect this is related to #475 and others.

For context, I only ever use this option for testing a particular zmap configuration.  I don't do this with "full" scans.

**Comment by paul-pearce** [comment]
What happens if you run output filter `success = 1`? What about `success = 1 && repeat = 0`.

My expectation is `success = 1` will give you >= MAX, and `success = 1 && repeat = 0` will give you exactly MAX.

I suspect the discrepancy is with respect to source port (ICMP?). The counter is based only on success and not a dupe. If you add other filters, they won't be taken into account.

**Comment by dadrian** [comment]
If you're using multiple threads or multiple shards, you will send out no-more-than `-N`, but due to the way the blacklist works, we can't actually send the exact number without precomputing every packet we would send. We need to update the docs about this.

**Comment by paul-pearce** [comment]
@dadrian `-n` is max targets, `-N` is max results.

**Comment by dadrian** [comment]
Oh! Interesting.

**Comment by paul-pearce** [comment]
A good question to ask is: Should `-N` reflect the output filters, or just `success == 1 && repeat == 0` as it does now. I think ideally it should reflect the output filters, but I've not dug that far into the code (I suspect this is handled at completely different layers).

**Comment by jhart-r7** [comment]
So the answer on the source port hardcoding is that, without this, on very active scanner nodes that are experiencing background network noise, DoS, malicious traffic, etc, will capture some of these unrelated packets and consider them as part of the output.  

@paul-pearce IMO, `-N` should reflect the filter.

**Comment by zakird** [comment]
I agree that `-N` should be the number of results that are returned to the user. I'm not sure if we have a counter for this, but it shouldn't be hard to do. This seems like a small enough change that I'm happy to see it as part of the 3.0 release.
