### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by porjo** [zmap/zmap#495]
Current stable release is v2.1.1 from 2015 and 351 commits since then. Any chance of tagging a new stable release?

**Comment by zakird** [comment]
Thanks for the issue. Yes, we agree! We've been meaning to get ZMap 3.0 out the door for quite a while, but it's been tough to find the time to get the set of issues we originally set out to complete finished. Right now, it looks like there are still a handful of bugs that appeared last fall that we want to clean up: https://github.com/zmap/zmap/milestone/13. I think it's reasonable that we could get these cleaned up by spring this year and tag 3.0.

**Comment by porjo** [comment]
Thanks for the update. Keep up the great work!

**Comment by zakird** [comment]
We've tagged ZMap 3.0.0 Beta 1: https://github.com/zmap/zmap/tree/v3.0.0-beta1. Only 4 years late. 🎉
