### ISSUE TITLE
Send rate exceeds system capabilities if we use high bandwidth

### ISSUE THREAD

**Issue by MasonQAQ** [zmap/zmap#496]
If scan by using high bandwidth, like:`zmap -B 100M`, zmap will log fatal error and exit:`send rate exceeds system capabilities`

**Comment by dadrian** [comment]
This is either a duplicate of #481, or you're actually exceeding your system's capabilities. Try using an additional thread if you have a spare core (`-T`), or running the scan on faster hardware.
