### ISSUE TITLE
zmap drop packets when not use ztee

### ISSUE THREAD

**Issue by niubencoolboy** [zmap/zmap#497]
I use zmap and zgrab to scan 80 http protocol,I found there may be something wrong.
when I scan use ztee as filter,command as follows:
```sudo zmap -p 80 -B 30M -w ip_lundun -f saddr --output-module=csv -m zmap_metadata.json -l zmap.log -o - | ztee zmap_result.csv | zgrab --port 80 --http="/" --output-file=banners.json --metadata-file=zgrab_metadata.json --log-file=zgrab.log```,
![with_ztee](https://user-images.githubusercontent.com/15031635/35617926-66378d80-06b4-11e8-83c7-a809d22ec93c.png)
But when I do not use ztee,zmap will drop packets,command as follows:
```sudo zmap -p 80 -B 30M -w ip_lundun -f saddr --output-module=csv -m zmap_metadata.json -l zmap.log -o - | zgrab --port 80 --http="/" --output-file=banners.json --metadata-file=zgrab_metadata.json --log-file=zgrab.log```,
![no_ztee](https://user-images.githubusercontent.com/15031635/35617949-71301996-06b4-11e8-8efc-36d1572be196.png)
How to solve this problem when I do not use ztee?

**Comment by zakird** [comment]
The reason this doesn't work without `ztee` is that ZGrab blocks input until it's ready to process it. ZMap will work fine with any program that's not blocking its output. This can be ztee, a file, or other utilities. The solution _is_ to use ztee.
