### ISSUE TITLE
zmap how to scan a range in format of 10.0.0.0-10.0.0.15

### ISSUE THREAD

**Issue by saeedsafavi26** [zmap/zmap#512]
i now i can scan a range of ips by its CIDR like 10.0.0.1/26
is there any way to scan a range of ips by ip_from-ip_to format like nmap??
for example :
zmap -p 80 120.0.0.10-120.0.5.29

**Comment by Syc0x00** [comment]
You can try [this](https://www.ipaddressguide.com/cidr) and put the ranges in your whitelist.

Ex:

```120.0.0.10/31
120.0.0.12/30
120.0.0.16/28
120.0.0.32/27
120.0.0.64/26
120.0.0.128/25
120.0.1.0/24
120.0.2.0/23
120.0.4.0/24
120.0.5.0/28
120.0.5.16/29
120.0.5.24/30
120.0.5.28/31
```

**Comment by zakird** [comment]
This is not currently possible, you'll need to express the ranges in CIDR blocks.
