### ISSUE TITLE
[FATAL] get-gateway: interface specified (tun0) does not match.

### ISSUE THREAD

**Issue by ZephyNet** [zmap/zmap#514]
Can anyone help me? 

I'm trying to use this command zmap -p22 -w india.lst -o mfu.txt -B100M 

but i keep getting this error "May 06 18:16:52.175 [FATAL] get-gateway: interface specified (tun0) does not match the interface of the default gateway (eth2). You will need to manually specify the MAC address of your gateway.
" i could try fix it but don't know where to put my mac address

**Comment by ajholland** [comment]
The gateway mac address can be specified using `-G` or `--gateway-mac`
