### ISSUE TITLE
is aes_input  thread safe? confused   me

### ISSUE THREAD

**Issue by chushuai** [zmap/zmap#515]
I am very confused  how to ensure  aes_input  thread safe? ,It is a principle？
https://github.com/zmap/zmap/blob/5058a4d8fc77b2b1b14ec6f2b84ec7818e7307b8/src/validate.c#L44

**Comment by dadrian** [comment]
It's not thread-safe, however there is only ever a single receive thread.

**Comment by chushuai** [comment]
no,the send thread also used this
https://github.com/zmap/zmap/blob/5d60326ec331fd260da000ecfa24e1143988ff2c/src/send.c#L380
