### ISSUE TITLE
--disable-syslog  not work at Ubuntu 18.04

### ISSUE THREAD

**Issue by MYMhaly** [zmap/zmap#522]
zmap version: **zmap-2.1.1**
(compiled from source code)

**--disable-syslog** not work at ubuntu 18.04. 

<img width="997" alt="1804" src="https://user-images.githubusercontent.com/35482619/40154836-0c66dbaa-59c3-11e8-8ac7-f2dce77e7232.png">

<img width="996" alt="1705" src="https://user-images.githubusercontent.com/35482619/40159234-dca528be-59da-11e8-81da-d82c857ef5f9.png">

**Comment by ajholland** [comment]
I recommend cloning master and compiling that from source. 

Unfortunately, v2.1.1 is almost 3 years old and therefore out of date. I've confirmed this behavior does not occur on ZMap from master branch on Ubuntu 18.04.
