### ISSUE TITLE
Unset rate parameter will cause zmap to fatal error

### ISSUE THREAD

**Issue by ajholland** [zmap/zmap#525]
https://github.com/zmap/zmap/commit/3236996d1ff432ee4d067a91d4731b6e84b891d2#diff-7e832c503c89f8b93bb9b0b0d9e8e67dR171

With this line, running `zmap -p 80` quits after stating that the send rate is impossibly slow. (It's really just not set). 

I kinda agree with this change so that the default invocation doesn't send at full-line rate. But I know that also is a feature of zmap? (sending packets at full-line rate). 

Also, this has implications for doing a dry run as I wouldn't expect to have to set a rate parameter to do a dry run.  

At the most, we might have to make a couple changes to make full-line rate the default again. 
At the least, just append the fatal comment to say "rate must be specified". 

@zakird @jhart-r7 @dadrian thoughts on the best approach for this?

**Comment by jhart-r7** [comment]
Yeah, I encountered this same thing just the other day while testing something.  It felt odd to have to set a rate when testing only.  It looks like the handling of line rate (`zconf.rate = 0`) is probably not working at the moment.  There also looks to be a problem if the max bandwidth is specified, because that could result in a `rate` of 0 too.

**Comment by zakird** [comment]
I think it's fine to have a safe default, something like 10K pps and a log message designating this. 0 was supposed to be "full speed, do not rate limit". I think it's clear that the current behavior is broken.

**Comment by dadrian** [comment]
> 0 was supposed to be "full speed, do not rate limit"

We should definitely fix whatever is broken, so long as the concept of "do not rate limit" still exists. This was previously special cased on `zconf.rate = 0`, but it doesn't have to be that way.

**Comment by zakird** [comment]
@ajholland any chance you'd be willing to tackle this? I think we need to specifically:

 (1) support setting `0` as a support rate on the command-line, which does not limit the speed of the scan (and update docs to explain this)

(2) Set default send rate to be something a bit more conservative, maybe 10K pps.

**Comment by zakird** [comment]
This is resolved by #530.
