### ISSUE TITLE
Aborted (core dumped) error when scanning

### ISSUE THREAD

**Issue by zerjioang** [zmap/zmap#528]
I just downloaded latest version (commit 0e94a7cd7c3f4fd363af9c39cb882a218439491b) of your code via
```bash
git clone https://github.com/zmap/zmap
```
I built a Docker image using the `Dockerfile` provided, and I was not able to run scan, no matter the options I choose.

I run my container (following Dockerfile instructions) with:

```bash
docker run -it --entrypoint=/bin/bash zmap_ubuntu
```

After that I executed with no success `zmap -p 80` and it gave to me next error:

```bash
zmap: /zmap-master/lib/constraint.c:110: _set_recurse: Assertion `0 <= len && len <= 32' failed.
Aborted (core dumped)
```

**Comment by ajholland** [comment]
I think this was a byproduct of #526 but I've submitted a PR that resolves it.
