### ISSUE TITLE
how to filter the muticast response when scannig with udp

### ISSUE THREAD

**Issue by leaixian** [zmap/zmap#533]
When i use zmap to scan network, the response contains muticast respone, I want to filter these muticast response.Zmap version is 2.1.1

**Comment by zakird** [comment]
This is not currently possible. You'll need to filter these out in a later stage of the pipeline.

**Comment by leaixian** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        OK，Thank you for your reply!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1453406129
                            
                    
                        
                            
                                    1453406129@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/13/2019 02:11，Zakir Durumeric<notifications@github.com> wrote： 


This is not currently possible. You'll need to filter these out in a later stage of the pipeline.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
