### ISSUE TITLE
how to set ttl for generated probe packets

### ISSUE THREAD

**Issue by LuKePicci** [zmap/zmap#535]
I was trying to figure out how to set the TTL fields of probe packets, in my particular case ICMP echo packets but I can't see this option for tcp probes either. Should I patch the probe module(s) to achieve this?

**Comment by zakird** [comment]
Yes, you'll need to patch probe modules to do this. I would recommend that if you do this, you introduce a global CLI flag since it can be used by many modules. We'd happily accept a pull request that introduces this functionality.
