### ISSUE TITLE
How to Discover All Servers Run at UDP Port 53 (country based)

### ISSUE THREAD

**Issue by emremuratercan** [zmap/zmap#536]
I am trying to discover all servers which serve at UDP port 53 with a code of 
`zmap -M udp -p 53 --whitelist-file ... --ignore-invalid-hosts --max-sendto-failures 100000000 --bandwidth=... -o ...`
I just discovered that, the output does not include all IPs in
 zmap -M udp --probe-args=file:Desktop/dns_53.pkt -p 53 --whitelist-file ... --ignore-invalid-hosts --max-sendto-failures 100000000 --bandwidth=...-o ....
or 
`zmap -M udp --probe-args=file:Desktop/dns_53_queryAwww.google.com.pkt -p 53 --whitelist-file ... --ignore-invalid-hosts --max-sendto-failures 100000000 --bandwidth=... -o ....`
What is going wrong? As my opinion first code's output need to include the others.
What am i supposed to do to discover all servers run at UDP port 53 in a country (list includes couple cidr)?
Thanks.

**Comment by fakirpic** [comment]
ya bu siki kullanmayi çözebildin mi amını sikim baştan programı kodlasam daha kolay olurdu arg girmekten.

**Comment by zakird** [comment]
From what I can tell in your code, this is because there's no specified UDP packet in the first command. You likely want to be using the dns probe module for doing dns scans.
