### ISSUE TITLE
Zmap with PF_RING

### ISSUE THREAD

**Issue by comozo** [zmap/zmap#538]
Hi,

We are trying to run zmap with PF_RING. 
We have followed the install process with PF_RING. We have checked that PF_RING is working fine but when run zmap the hitrate is 0%

As an example output:
sudo ./src/zmap -i zc:enp65s0f0 -M udp -p 53 --source-ip=X.X.X.X --source-mac=X:X:X:X:X:X  -G X:X:X:X:X:X X.X.X.X/32

Oct 29 19:10:20.942 [WARN] blacklist: ZMap is currently using the default blacklist located at /etc/zmap/blacklist.conf. By default, this blacklist excludes locally scoped networks (e.g. 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blacklist by editing the default ZMap configuration at /etc/zmap/zmap.conf.
Oct 29 19:10:23.597 [INFO] zmap: output module: csv
Oct 29 19:10:23.597 [INFO] csv: no output file selected, will use stdout
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 13%; send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:02 25%; send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:03 38%; send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:04 50%; send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:05 63% (3s left); send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:06 75% (2s left); send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:07 88% (1s left); send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:08 100% (0s left); send: 1 done (508 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
Oct 29 19:10:32.931 [INFO] zmap: completed

We are running this commit: 

3d52a0b793bb55146baf82630e438b1b6fa66ec6

#### Network card:
*-network:0
       description: Ethernet interface
       product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:41:00.0
       logical name: enp65s0f0
       version: 01
       serial: 00:e0:ed:42:98:66
       size: 10Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical fibre
       configuration: autonegotiation=off broadcast=yes driver=ixgbe driverversion=4.1.5 duplex=full firmware=0x800000cb ip=x.x.x.x latency=0 link=yes multicast=yes port=fibre 

#### PF_RING:

PF_RING Version          : 7.3.0 (dev:871afb2a4c7e2f9c88f08e66734a4669e89a0ca0)
Total rings              : 0

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 17
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

Modules
ixgbe                 299008  0
vxlan                  49152  1 ixgbe
ptp                    20480  2 tg3,ixgbe

Thank you for the help.

**Comment by comozo** [comment]
Also during zmap compilation we have this warning: 
```
zmap/src/zmap.c:210:60: warning: passing argument 8 of ‘pfring_zc_run_balancer’ from incompatible pointer type [-Wincompatible-pointer-types]
      zconf.pf.prefetches, round_robin_bursts_policy, NULL, distrib_func,
                                                            ^
In file included from zmap/src/socket.h:18:0,
                 from zmap/src/send.h:13,
                 from zmap/src/zmap.c:36:
/usr/local/include/pfring_zc.h:532:1: note: expected ‘pfring_zc_distribution_func {aka long int (*)(struct <anonymous> *, void *, void *)}’ but argument is of type ‘int32_t (*)(pfring_zc_pkt_buff *, pfring_zc_queue *, void *) {aka int (*)(struct <anonymous> *, void *, void *)}’
 pfring_zc_run_balancer(
```

**Comment by dadrian** [comment]
What version of PF_RING are you using? We originally did this with 6.0.1, and it looks like the API might have changed since then.

**Comment by zakird** [comment]
Closing due to no response from reporter.
