### ISSUE TITLE
Zmap with IP2Location LITE Geolocation

### ISSUE THREAD

**Issue by m-cameron** [zmap/zmap#540]
Can we support geolocation results query in Zmap?

IP2Location LITE has free database with city, coordinates, ZIP code and time zone information.
https://lite.ip2location.com/database/ip-country-region-city-latitude-longitude-zipcode-timezone

**Comment by zakird** [comment]
This is probably out of scope for the ZMap scanning itself. However, Zannotate (https://github.com/zmap/zannotate) can do this for you, you'll just need to pipe zmap results through.
