### ISSUE TITLE
Zgrab: [FATAL] ztee: Error writing to stdout

### ISSUE THREAD

**Issue by FaqiaIqbal** [zmap/zmap#541]
Hi. I am using the following command:  zmap -w input.txt -meta.json -p 80 -B 5k | ztee results.csv | ./zgrab --port 80 --output-file=banners.json -timeout 30 --http="/" -log-file log.csv 
And it gives me the following error: [FATAL] ztee: Error writing to stdout,  
and then just stops working. How do I fix this?

**Comment by zakird** [comment]
ZGrab or whatever you're piping output into likely crashed and did not allow input.
