### ISSUE TITLE
icmp_echo_time timestamps not accurate

### ISSUE THREAD

**Issue by Maximilian-Fuchs** [zmap/zmap#562]
I'm trying to measure round trip times (RTTs) with the icmp_echo_time module.
In the results I can find between 15% and 45% negative round trip times, which shouldn't be possible. The positive RTTs in my results also seem way to high.

There seems to be an issue with the timestamps that are written at send and receive of an ICMP packet.

I tried slow measurements (at 100kbit/s) but that didn't help.
Also tried measurements from different machines with the same faulty results.

Has anyone managed to get valid measurements with the icmp_echo_time probe module yet?

**Comment by Maximilian-Fuchs** [comment]
Ok, it was the fault of our evaluation script 🤦‍♂️.
But the absolute RTTs are still higher than the ones optained with `ping` command from the bash.

Maybe we can get a more accurate timestamp if we use libpcap for obtaining the receive timestamp instead of gettimeofday.

Greetings,
Max

**Comment by rwlrwlrwlrwl** [comment]
Will you plan to fix this issue?
