### ISSUE TITLE
Does zmap support IPv6?

### ISSUE THREAD

**Issue by icamys** [zmap/zmap#565]

**Comment by ogasser** [comment]
There is a ZMap fork with IPv6 support: https://github.com/tumi8/zmap

**Comment by icamys** [comment]
@ogasser Thanks for response! I thing with time the development of IPv6 zmap will lag behind original zmap, as many people use and contribute to original zmap. Are you planning to create a PR for supporting IPv6 to this original repository?

**Comment by ogasser** [comment]
There is no plan to create a PR for this repository. We periodically merge changes from the original ZMap repository into the https://github.com/tumi8/zmap repo.
