### ISSUE TITLE
Does zmap scan TCP ports comprehensively?

### ISSUE THREAD

**Issue by vkotronis** [zmap/zmap#568]
Asking in reference to this paper:
```
Bano, Shehar, et al. "Scanning the internet for liveness." ACM SIGCOMM Computer Communication Review 48.2 (2018): 2-9.
```
I have 2 main questions in this regard:
1) Does zmap also cover cases (TCP Rst packets) where the host responds with the Ack bit not set? Or does it record all TCP Rst packets?
2) If not, does this affect the scanning coverage results in a meaningful way?

Essentially what I am asking is if there are cases (corner or more mainstream) that are not properly covered by the tool, when scanning a certain TCP port. Thanks in advance!

**Comment by zakird** [comment]
Yep, this is possible. You just need to make sure that your output filter is empty or that you use the CSV output module so that you can differentiate.
