### ISSUE TITLE
Is it normal that 100 rate used a full core??

### ISSUE THREAD

**Issue by kxmp** [zmap/zmap#570]
I'm using it on vm(vmware with debian). It only have a core.
I found that when I set rate to 100 it just used all cpu. Why it's so high!! Is it same for you other guys?

**Comment by zakird** [comment]
ZMap isn't optimized for large Internet-wide scans, not for executing very slow scans. If you're worried about CPU usage, you're likely better using a tool design for small scans like nmap.

**Comment by kxmp** [comment]
So it's normal. Because in my environment 100 1000 & 4000 are all 100%cpu
