### ISSUE TITLE
Typo in redis-csv output module causes binary field overwriting prior fields in the output

### ISSUE THREAD

**Issue by secmobi** [zmap/zmap#572]
In `output_modules/module_redis_csv.c` [line 185](https://github.com/zmap/zmap/blob/master/src/output_modules/module_redis_csv.c#L185), when copying `FS_BINARY` type field's value to the output buffer, the code is:

			hex_encode_str(out, (unsigned char *)f->value.ptr,
				       f->len);

This mistake (typo?) will cause that, when configured `--output-fields` to value like `saddr,timestamp_str,data`, the final output will only contain `data` field value -- `saddr` and `timestamp_str` values which have been copied to the `out` buffer will be overwritten by the above code mistakenly. 

The bug could be stably re-produced by the current HEAD code. Have tested the obvious bugfix method (of replacing `out` to `dataloc`) and that resolved the issue well.

**Comment by zakird** [comment]
This was resolved by #573.
