### ISSUE TITLE
How to  capture and save the raw response  when  scanning with zmap ? 

### ISSUE THREAD

**Issue by Changliting-letty** [zmap/zmap#582]
Hi,I'm sorry to trouble you. I'm new to this field. I want to  save the DNS's raw response with zmap  .But I can't make it successfully.I have been puzzled  for two weeks.Could you please  give me some suggestions?   I have no idea about the  breakthrough  to deal with my problem. What should I do ?
Thanks very much.

**Comment by zakird** [comment]
You can set this using the `--output-fields` flag. If you run with help or just `--output-fields=*`, you'll see what the available fields are.

**Comment by Changliting-letty** [comment]
Thank you for your kind answer .I know what you mean .And I have tried this. In the fieds set ,there isn't data.    I mean that  I want to save the response packet. How to dump pcap?    Very sorry to bother you again...

**Comment by zakird** [comment]
You're best running tcpdump in the background if you want a pcap.

**Comment by Changliting-letty** [comment]
HAHA,Thanks  a lot. I'll have a try. Thank you for your help and patience.
