### ISSUE TITLE
The application of Zmap

### ISSUE THREAD

**Issue by Mrdsj** [zmap/zmap#584]
Can zmap be used for scanning network layer or transport layer?

**Comment by leaixian** [comment]
Yes,both ip layer and transport layer are ok.

**Comment by Mrdsj** [comment]
It's the first time I use this tool,can you tell me what should I do?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leaixian"<notifications@github.com&gt;; 
发送时间: 2020年1月3日(星期五) 下午5:24
收件人: "zmap/zmap"<zmap@noreply.github.com&gt;; 
抄送: "2629173176"<2629173176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zmap/zmap] The application of Zmap (#584)




Yes,both ip layer and transport layer are ok.

**Comment by leaixian** [comment]
Maybe this article can be helpful for you!
link: https://linux.cn/article-5860-1.html#bestpractices

**Comment by Mrdsj** [comment]
OK,thank you so much!
