### ISSUE TITLE
IP generation process of ZMap is flawed for some seed values

### ISSUE THREAD

**Issue by rstrullu** [zmap/zmap#586]
We have the following bug to report. This bug targets all the known versions of Zmap.

In some (rare) cases, the IP generation of Zmap is flawed and the scan does not cover the full IP range or enter in an infinite loop. This occurs when the number generated by the random generator or the seed specified by the user (with the -e paramater or in the zmap.conf file) is equal to some problematic value. The probability is estimated to 7*10^(-9) (approximatively the euromillion jackpot probability) but is non zero. The bug can be reproduced with the following seed values and the current version of Zmap on github (commit f44fc15):

346296650 -> infinite loop
551370190 -> infinite loop
668513199 -> partial scan (63% of the scan)
950005475 -> partial scan (50% of the scan)
1853945527 -> partial scan (33% of the scan)
2250056444 -> infinite loop
2963139306 -> partial scan (12% of the scan)
8582731091 -> single IP generation
9561776755 -> single IP generation

This list is not exaustive and the number of problematic values is approximatively equal to 2^37.

The command line for testing the bug is the following:
zmap -p 80 -d -e [seed_value] | grep "ip" | wc -l
or equivalently for faster result:
ziterate -b ../conf/blacklist.conf -e [seed_value] | wc -l

The bug is due to the fact that the multiplication in the finite field is coded as a 64-bit unsigned multiplication followed by a modular reduction. This sequence of operations is sound when the two operands are less than 2^32. Some elements of the finite field used by Zmap are however greater than 2^32. In particular, if the primitive element generated by the RNG exceeds 2^32-14, then, during the generation of the cyclic group, one of the multiplication exceeds 2^64 and the multiplication in the finite field is flawed. Moreover, a special case occurs when the primitive element is greater than 2^32. In this case, the function that generates the primitive element (find_primroot) cast the value into 32 bits, resulting in a value that is not a primitive element.

To fix this bug, we recommand to modify the function that generate the primitive element of the finite field. However we do not recommand to change the multiplication of the finite field. Actually using a big number library like mpz will deeply impact the performance of the IP generation process. Moreover the multiplication on 64-bits and the reduction can be coded as two assembly instructions on modern CPUs and it is the most efficient method for coding the generation of the cyclic group. Therefore we only recommand to check that the primitive element is less or equal to 2^32-14. It ensures that all the multiplications with this operand will have a result less than 2^64. This can be done by modifying the function find_primroot in the file cyclic.c:

static uint32_t find_primroot(const cyclic_group_t *group, aesrand_t *aes)
{
  uint64_t retv;
  do {
	  uint32_t candidate =
	      (uint32_t)((aesrand_getword(aes) & 0xFFFFFFFF) % group->prime);
	  if (candidate == 0) {
		  ++candidate;
	  }
	  while (check_coprime(candidate, group) != COPRIME) {
		  ++candidate;
		  // special case where we need to restart check from begin
		  if (candidate >= group->prime) {
			  candidate = 1;
		  }
	  }
	  retv = isomorphism(candidate, group);
  } while (retv > ((1<<32)-14)); //bug fix
	return retv;
}

Rémi Strullu and Johan Mazel

**Comment by dadrian** [comment]
I independently thought of this bug while working on a similar codebase, and agree with you, but how did you arrive specifically at the `2^{32}-14` bound?

**Comment by rstrullu** [comment]
The bound can be proved as follow:

Let b=2^32-14 and let p=2^32+15 (p is the maximal cardinality of the finite field used by Zmap). Let g a generator of (Z/pZ)* less or equal to b. Then for all x in Z/pZ, x is less or equal to 2^32+14 and g*x is less than (2^32+14)*(2^32-14) = 2^64 - 14^2 < 2^64. Therefore there is no overflow in the 64-bit multiplication between g and x if g is less or equal to b. 

Conversely, suppose that g is a generator strictly greater than b. Since g generates (Z/Zp)*, during the generation of the cyclic group there is an integer n such that g^n=2^32+14. In other words, there will be a step during the IP generation process of Zmap where the current sate will be equal to 2^32+14. Then g*(2^32+14) is greater or equal to (2^32-13)*(2^32+14) > 2^64. Therefore there is always an overflow in the 64-bit multiplication if g is strictly greater than b.

**Comment by dadrian** [comment]
@rstrullu Can you confirm the fix in #587
