### ISSUE TITLE
problem with banner-grab-tcp

### ISSUE THREAD

**Issue by alibenrejeb96** [zmap/zmap#588]
i'm having a problem while trying to use banner-grab-tcp even though i have properly installed libevent-dev .
command : zmap -p 80 -N 10000 -o - | ./banner-grab-tcp -p 80 -c 100 -d -v http-req > http-banners.out
error msg : ./banner-grab-tcp : no such file or directory

**Comment by zakird** [comment]
I'd strongly recommend you use ZGrab2: https://github.com/zmap/zgrab2.
Banner Grab isn't maintained and really ought to be deleted.
