### ISSUE TITLE
strange rate limit of zmap which use 100% cpu

### ISSUE THREAD

**Issue by bosskwei** [zmap/zmap#589]
Hi,
I found something really strange in zmap,
```bash
[1] sudo zmap -T 1 --rate=49 --target-port=80 --output-file=results.txt 0.0.0.0/0
[2] sudo zmap -T 1 --rate=50 --target-port=80 --output-file=results.txt 0.0.0.0/0
```
`--rate=49` use 1% cpu, but `--rate=50` use 100% cpu.

(the number 49 and 50 may verify on different platform, but you can do a binary search to find this number)

**Comment by dadrian** [comment]
To handle accurate, but high-rate limiting, the ZMap rate limit is implemented as a busy loop rather than a sleep. The cut off is 50 packets per second for using the sleep vs busy-wait rate limit. 

https://github.com/zmap/zmap/blob/master/src/send.c#L259
