### ISSUE TITLE
Scanning allowed srv

### ISSUE THREAD

**Issue by qyservers** [zmap/zmap#590]
Our website http://qyservers.xyz

**Comment by imfht** [comment]
@qyservers 
> Fatal error: Uncaught Error: Class 'mysqli' not found in /home/admin/web/cp.qyservers.xyz/public_html/include/db.php:6 Stack trace: #0 /home/admin/web/cp.qyservers.xyz/public_html/login.php(2): require_once() #1 {main} thrown in /home/admin/web/cp.qyservers.xyz/public_html/include/db.php on line 6

bro your site seems down.
