### ISSUE TITLE
zmap issue on my vps

### ISSUE THREAD

**Issue by Reaper1255** [zmap/zmap#595]
Mar 18 21:35:31.822 [FATAL] get_gateway: Unexpected hardware address length (0).

    If you are using a VPN, supply the --vpn flag (and provide an interface via                                     -i)

im getting this error any fixes?

**Comment by imfht** [comment]
you can:
1. get the gateway mac address via `arp -a ` and paas it to zmap via `-G mac_address`
2. zmap can not run on openvz for some reason.
Could you give me more info about your vps? eg: ip address, gateway ipaddress virtual-tech?

**Comment by Reaper1255** [comment]
i fixed it and just moved host it was a openvz so i moved host thanks tho
