### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by r5za** [zmap/zmap#597]
Hi,

i try to scan with zmap on centos vps but i got this error [FATAL] get-iface-ip: ioctl failure: No such device
 help me plz

_Originally posted by @dadrian in https://github.com/zmap/zmap/issues/448#issuecomment-324943008_

**Comment by zakird** [comment]
You need to manually specify the source IP address you want to scan from. Results using a VPS are questionable and I would suggest not running ZMap over a VPS.
