### ISSUE TITLE
Resulting Output of Zmap

### ISSUE THREAD

**Issue by nweinshenker** [zmap/zmap#599]
I have a general question regarding the resulting output of a Zmap. Given that I pass a list of CIDR networks to scan with the command:
`zmap --probe-module=icmp_echoscan -B 10M -P 10 -f "saddr" -w <list_cidr_networks> -o result.csv`, I expect the output to be the list of distinct IP addresses that responded successfully.

However, with over 100 [/19 - /24] networks, I'm only receiving a fraction of unique addresses ~2000 that are being outputted from the scan.  From the metadata file, I can see Zmap is correctly running over the correct IPv4 address space but just isn't giving the resulting responsive addresses that I believe should exist (testing against scamper tool for ping parallelization).

Are there any suggestions for interpreting the results in a way that could provide me an output of all addresses that respond with packet lost > 10 %?

**Comment by zakird** [comment]
Does this occur when you scan at a much slower rate? You can look at hit
rate after 30 seconds in the stdout updates and see how they compare.
