### ISSUE TITLE
Shards Terminology and Usage

### ISSUE THREAD

**Issue by 0xCC00FFEE** [zmap/zmap#600]
Hello everyone,
Sorry if this is not exactly a technical issue, it's more of understanding a Zmap feature and how it works.

I'm actually a bit confused about the "shards" terminology, not really sure what does it represents, why the maximum number of shards is 254 specifically? I'm aware that it's mainly used to allow non-contiguous IPv4 addresses generation.
However, if I wanted to scan a portion of the whole IPv4 Address space (minus blacklisted addresses), say I wanted to scan 10% of the whole address space, would it be 0.1*254 ~ 26 shards, which mean I shall be scanning from shard=0 to shard=25, that would represent 10% of the whole IPv4 address space? So: 
```
zmap -B100M --shard=0 --shards=254 --seed=1234
zmap -B100M --shard=1 --shards=254 --seed=1234
zmap -B100M --shard=2 --shards=254 --seed=1234
.
.
zmap -B100M --shard=25 --shards=254 --seed=1234
```
A list of all the results of each of the above commands would give me in total 10% of the address space? Is that correct?

**Comment by zakird** [comment]
Shards are specifically designed to allow you split a scan across multiple executions. It is _not_ designed for non-contiguous address generation. If you want to scan 10% of the address space, you want to run `zmap --max-targets=10%`.  If you wanted to have 10 x 10% scans, together which you were guaranteed to reach 100% coverage of the IP space, then you could use use 10 shards.  If you want two machines to together have 10% coverage, you would run `zmap --max-targets=10% --shards=2`. https://github.com/zmap/zmap/wiki/Rate-Limiting-and-Sampling has the documentation I suspect you're looking for.
