### ISSUE TITLE
ZMap needs to set MSS options to detect all hosts

### ISSUE THREAD

**Issue by puneri78** [zmap/zmap#601]
Here is command I'm using for reaching IP Address. This IP address is reachable (ping, nmap works) and also accessible by browser. However zmap doesn't return any thing.

zmap -p 443 -o - -f saddr,sport --verbosity=5 <IP_ADDRESS> -b /etc/zmap/blacklist.conf

what could be wrong, is router of that IP_ADDRESS blacklisting/blocking zmap requests? or something else?

**Comment by zakird** [comment]
Is this a local IP address (i.e., within your local subnet)?

**Comment by puneri78** [comment]
nope, this is public IP, I could load that website using browser. 
If I use openssl to connect IP then could establish basic TLS handshake and see certificate.

**Comment by zakird** [comment]
It's hard to know without much more detail about your network. I suspect that packets are not being sent to the correct gateway, or something like that, but realistically, it could be just about any part of your configuration that's incorrect here and causing the problem.

**Comment by puneri78** [comment]
for example: say for following command with given IP, I don't see zmap returning any value.
However using openssl I could connect and can perform TLS handshake

`zmap -p 443 -o - -f saddr,sport --verbosity=0 192.124.249.102 -b /etc/zmap/blacklist.conf -B 1M -quiet`

**Comment by zakird** [comment]
Thanks for sharing the IP. We can confirm on our side too that ZMap SYN packet is ignored despite other ones going through.

**Comment by puneri78** [comment]
any workaround for this ? also are there any potential reason(s) SYN packet is ignored with such hosts, this is just for us to learn more on zmap ?

**Comment by zakird** [comment]
It looks like this is occurring because there is no MSS option set on the packet.
