### ISSUE TITLE
Problem with loading data in ZMAP6

### ISSUE THREAD

**Issue by rameshpudi** [zmap/zmap#602]
Dear all,
I am using ZMAP6 due to unavailability of latest Matlab version. I was trying to load .mat data file which is in ZMAP format but it is not loading and even it does not showing any error. Please find the image below for your reference. 

I hope some could solve this issue. Your kind help shall highly appreciated.

Thank you. 

![Zmap](https://user-images.githubusercontent.com/64882129/81136271-b98b8f00-8f78-11ea-80c3-2512a3d96190.JPG)

**Comment by zakird** [comment]
This is the wrong project. This ZMap is an Internet scanner.
