### ISSUE TITLE
No output from tcp_initcwnd_ssl

### ISSUE THREAD

**Issue by newmanjt15** [zmap/zmap#605]
Hello,

I'm attempting to use zmap from COMSYS (https://github.com/COMSYS/zmap) to estimate the initial TCP congestion window from a remote host. I built from source following the zmap directions. 

When I test without "-M tcp_initcwnd_ssl" it gives me the expected output, but when I run with the probe module as below it completes fine, however, it does not output the expected csv.

(sudo ./src/zmap -p443 -T1 -R1 -M tcp_initcwnd_ssl -f "saddr,classification" -i $iface -b /etc/blacklist.conf -o $out_file -m $meta_file -v5 -c 2 $test_ip > $log_file 2>&1)

[1589406401_meta.log](https://github.com/zmap/zmap/files/4624910/1589406401_meta.log)
[1589406401_out.txt](https://github.com/zmap/zmap/files/4624911/1589406401_out.txt)
[1589406401.log](https://github.com/zmap/zmap/files/4624916/1589406401.log)

**Comment by zakird** [comment]
I'm not sure how we can help here. It sounds like ZMap as provided in this repository works fine. As you write,

> When I test without "-M tcp_initcwnd_ssl" it gives me the expected output

If you have a problem with the module provided in the COMSYS repository, please create a bug in their repository. We aren't going to troubleshoot code that we didn't write and don't know anything about. :)

**Comment by newmanjt15** [comment]
Sorry, I could not find the place to create a bug there. I'll look for that.

However, it appears as though you did :) seems that Github has led me astray, apologies!

<img width="1054" alt="Screen Shot 2020-05-13 at 5 00 10 PM" src="https://user-images.githubusercontent.com/4359011/81870423-6c408c00-953b-11ea-97bb-68a1f7cc9510.png">
