### ISSUE TITLE
High CPU issue

### ISSUE THREAD

**Issue by puneri78** [zmap/zmap#606]
Whenever we scan IP ranges using ZMap we are seeing high cpu consistently.
Here is how our command looks like, any pointers, that could help reduce CPI spike?
Tried with -B 1M etc, but still CPU spikes to 300% 
`
time ./zmap -p 443 -O csv -f saddr,sport --quiet --verbosity=0 12.12.128.0/17 -b /etc/zmap/blacklist.conf --max-sendto-failures 1000000 -B 10M --sender-threads=5

109.44s user 
0.68s system 
362% cpu 
30.364 total
`

Also if we are doing such zmap scans from multiple threads, slows down everything, can anything being improved here? any pointers would help.

**Comment by zakird** [comment]
Your best bet here will be to use a single send thread, which will limit impact to a single CPU core. Unfortunately, Linux timers are too unreliable to use for spacing out how packets are sent, which is results in the higher CPU usage for a core unless the send rate is very slow. There isn’t a good alternative.

**Comment by puneri78** [comment]
ah I see, with zmap from master - build locally CPU is now mere 4%
`./zmap -p 443 -O csv -f saddr,sport --quiet --verbosity=0 12.12.128.0/17 -b /etc/zmap/blacklist.conf --max-sendto-failures 1000000 -B 10M`

However with zmap 2.1.1 CPU with same command is 200%, thought just share this.

**Comment by splitice** [comment]
I too noticed that even at low packet rates (1-3k pps) cpu usage was 100% on a core. 

I tested the master branch to confirm what @puneri78 saw, however continue to see 100% cpu utilization.

I'm figuring this has to do with the nanosleep usage. Perhaps a batch option would be a good addition. Waking and sending a user supplied number of messages (say 100) would allow for longer sleep periods. Also allowing usleep to be used for longer periods (yes - lower accuracy) might also be a good idea.

When limiting to low rates like these high accuracy doesnt make as much sense.

**Comment by splitice** [comment]
PR #610 solves the problem. With `--batch` CPU usage <2% at 3k PPS.

**Comment by dadrian** [comment]
Fixed by #610
