### ISSUE TITLE
Does not compile on ARM

### ISSUE THREAD

**Issue by githubee** [zmap/zmap#61]
I am not sure if this is made for x86 architecture only, but it won't compile on Debian on ARM (Sheevaplug).

Output is:
[..]
cc1: warnings being treated as errors
output_modules/module_csv.c: In function ‘csv_process’:
output_modules/module_csv.c:81: error: cast to pointer from integer of different size
output_modules/module_csv.c:83: error: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘uint64_t’
output_modules/module_csv.c:85: error: cast to pointer from integer of different size
make: **\* [module_csv.o] Error 1

Hardware-Info:
sheeva :~/zmap/zmap-master/src# uname -a
Linux sheeva 2.6.32-5-kirkwood #1 Tue Jan 17 05:11:52 UTC 2012 armv5tel GNU/Linux
sheeva :~/zmap/zmap-master/src# cat /proc/cpuinfo
Processor       : Feroceon 88FR131 rev 1 (v5l)
BogoMIPS        : 1192.75
Features        : swp half thumb fastmult edsp
CPU implementer : 0x56
CPU architecture: 5TE
CPU variant     : 0x2
CPU part        : 0x131
CPU revision    : 1

Hardware        : Marvell SheevaPlug Reference Board
Revision        : 0000
Serial          : 0000000000000000
sheeva :~/zmap/zmap-master/src#

**Comment by Lua12138** [comment]
After 10 years, there are now many ARM devices, are there any plans for a port?

**Comment by dadrian** [comment]
ZMap compiles on Mac arm devices.
