### ISSUE TITLE
send_packet failed

### ISSUE THREAD

**Issue by Changliting-letty** [zmap/zmap#611]
Hi, I want to scan IPv4 space with the udp module. But I fund the error.
![image](https://user-images.githubusercontent.com/57993597/86195947-a2d27480-bb84-11ea-85c3-a7822b2ba4b4.png)
![image](https://user-images.githubusercontent.com/57993597/86195981-bda4e900-bb84-11ea-826d-287ec6dce408.png)
I run zmap on vps of 2G memory.  I changed the kernel buffer. But it didn't work. What  is the root cause? Please help me.

**Comment by dadrian** [comment]
The VPS likely has an IPsec configuration that is incompatible with ZMap, as it is attempting to create one socket per, see https://serverfault.com/questions/614453/no-buffer-space-available-on-connect.

**Comment by dadrian** [comment]
@Changliting-letty What hosting provider are you using?

**Comment by Changliting-letty** [comment]
> @Changliting-letty What hosting provider are you using?

Thank you for your help. It's  DMIT.

**Comment by Changliting-letty** [comment]
@dadrian  Hi,Have you tried to dump the DNS packets ? I tried to dump the DNS packet to pcap file.I found that this  will made a little influence on  the numer of open DNS resolvers.   Do you think this phenomenon is normal？   Is it possible to dump packets without affecting the number of ODNS?
