### ISSUE TITLE
[FATAL] blocklist: unable to open blocklist file: /etc/zmap/blocklist.conf: No such file or directory

### ISSUE THREAD

**Issue by Positive-Engineer** [zmap/zmap#618]
you changed the blacklist to a blocklist, but forgot to create a blocklist and created anyway /etc/zmap/blacklist.conf.
Are you seriously?
https://github.com/zmap/zmap/commit/117dc62a1db920a4961d448fc11771098d5595c5

**Comment by dadrian** [comment]
@Positive-Engineer If you actually cared about this issue, you'd realize you simply need to rerun `cmake`. Instead, you came here to complain, which makes me seriously doubt your intentions.

**Comment by dlenskiSB** [comment]
> you'd realize you simply need to rerun `cmake`.

Having run into this issue myself, and found it while Googling…

Another reason this can happen is if you had installed an old (pre-https://github.com/zmap/zmap/commit/117dc62a1db920a4961d448fc11771098d5595c5), and then built a newer version (post-https://github.com/zmap/zmap/commit/117dc62a1db920a4961d448fc11771098d5595c5) from source. If the old config files with bl**a**cklist` still exist in `/etc/zmap`, they'll interfere with the operation of the new build, and it won't have anything to do with the correctness of the new build.

(Just in case anyone else comes across this :-) )
