### ISSUE TITLE
ICMP probe module prints debugging information

### ISSUE THREAD

**Issue by dallangoldblatt** [zmap/zmap#623]
**Describe the bug**
The probe module `icmp_echoscan` has extra per-packet logging that was [introduced with a recent pull request](https://github.com/zmap/zmap/commit/0f90f616a3f8da4f202a56eb7dc3bbab71267296).

![image](https://user-images.githubusercontent.com/20169912/89075227-b6235c00-d34b-11ea-98c1-9fca7aa7886c.png)

**CLI Arguments**
zmap --probe-module=icmp_echoscan

**Expected behavior**
For high PPS scans, this produces too much output. Removing this logging should be an easy fix by removing line 172 of `zmap/src/probe_modules/module_icmp_echo.c`.

**Comment by dadrian** [comment]
Thanks!
