### ISSUE TITLE
ioctl failure: Cannot assign requested address

### ISSUE THREAD

**Issue by Technik-J** [zmap/zmap#625]
**Describe the bug**
I get this error message when I try to do any scan:

`[FATAL] get-iface-ip: ioctl failure: Cannot assign requested address`

I think this is because I have multiple VLAN interfaces. When I specify interface with `-i` and gateway MAC with `-G`, everything starts to work.
I tested on another server with only one interface and it's working fine.

**Environment:**
 - OS: Ubuntu Server 18.04.3
 - Version: from commit 623d069

**Comment by dadrian** [comment]
Likely all we can do is clean this log message up to provide guidance.

**Comment by QGB** [comment]
[FATAL] get-iface-ip: ioctl failure: Cannot assign requested address 

指定的interface不存在
