### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by shaunwarman** [zmap/zmap#627]
**Describe the bug**
It looks like after simply following the github wiki, I can't get zmap to work on macOS.

**CLI Arguments**
```sh
zmap -B 10M -p 80 -n 10000 -o results.csv
Oct 10 08:26:25.314 [FATAL] zmap: could not detect GW MAC address for 1.5.0.0 on utun2. Try setting default gateway mac address (-G), or run "arp <gateway_ip>" in terminal.
```

**Expected behavior**
Expect zmap to port scan and write results to results.csv

**Environment:**
 - OS: MacOS Catalina version 10.15.4
 - Version: zmap 2.1.1 installed with brew

**Additional context**
I think I'm just dumb. After setting gateway, still issues.

```sh
netstat -nr | grep default
default            192.168.1.1        UGSc           en0

zmap -B 10M -p 80 -n 10000 -G 192.168.1.1 -o results.csv

zmap: invalid MAC address `192.168.1.1'
```

**Comment by zakird** [comment]
You need to set the MAC address of the gateway, not the IP address. ZMap operates on L2 not L3. The error provided is correct.

**Comment by shaunwarman** [comment]
You are absolutely right.

This worked for me
```sh
zmap -p 80 -o results.csv --verbosity=5 --disable-syslog -G <MAC_ADDRESS> -i en0
```
