### ISSUE TITLE
redis ip count is different from csv approach 

### ISSUE THREAD

**Issue by tahseen2k8** [zmap/zmap#631]
**Issue**
I am using csv approach which need manual human efforts to get results . tried to use redis to automate but the total count of redis approach is almost double then the count i was getting from csv approach . commands are given below can you guys please help me out in this issue .

**CLI Arguments**
Please paste your ZMap invocation below

```
Redis commands ..
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=0 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet -f saddr --output-module=redis-csv --output-args=tcp://localhost:6379/queue:2_80
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=1 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet -f saddr --output-module=redis-csv --output-args=tcp://localhost:6379/queue:2_80
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=2 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet -f saddr --output-module=redis-csv --output-args=tcp://localhost:6379/queue:2_80
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=3 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet -f saddr --output-module=redis-csv --output-args=tcp://localhost:6379/queue:2_80
=====================================CSV commands==================
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=0 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet  -f saddr --output-file=100_percent_p_80.csv

sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=1 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet  -f saddr --output-file=100_percent_p_80.csv
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=2 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet  -f saddr --output-file=100_percent_p_80.csv
sudo zmap 0.0.0.0/0 -B 300M -p 80 -n 1% --shards=4 --shard=3 --seed=9820 -l zmapLogs/Zmap_B300M_P80_n1%.logs --quiet  -f saddr --output-file=100_percent_p_80.csv

```

**Example Target IP**

this was full scan of internet for port 80 .

**Expected behavior**
from CSV approach i was getting `62086619` ips total
and from Redis approach i got `128973584` ips which is almost double of csv.
it could be command errors or any thing else please help me out to get out this issue .

**Comment by zakird** [comment]
I suspect that either RSTs or duplicates are coming through. The default mode in ZMap filters these out, but when you choose a different output module it inherits an empty output module. If you used `--output-module=csv`, then I think that they'd be the same number. If you want to filter those out, then an `--output-filter` can help you get there. 

This is really confusing. And to be honest, I'm not 100% sure what's the right way to make this clearer. We could have `--ouput-filter` be the same as the default, unless it's specified otherwise, but that would require the user to set `--output-filter=''` if they want all packets.

**Comment by tahseen2k8** [comment]
@zakird  the count is unique i have parsed somewhere in persistence. the count i had shared is unique ip count .
this will be great if you share complete command for redis approach, I will give a try and get back here

**Comment by dadrian** [comment]
We decided to drop the Redis output module from ZMap. It's been very bug-prone, may have memory-safety issues, and is likely better handled by piping into some data processing scripts. Example:

```
zmap -p 80 --output-module=csv | ztee --raw | python add_to_redis.py
```

**Comment by tahseen2k8** [comment]
@dadrian  thanks for your response that will be great if you can share add_to_redis.py script as well so  I can get idea how you are capturing output in python script . again really appericate your support.

**Comment by dadrian** [comment]
I don't have anything written, but roughly it'd look something like:

```
import redis
import csv
import sys

r = redis.Redis()

for row in csv.reader(sys.stdin):
    redis.set(row[0], ','.join(row))
```

To avoid escaping issues, you might be better off with the JSON output module.

```
import redis
import csv
import sys

r = redis.Redis()

for line in sys.stdin:
    obj = json.loads(line)
    redis.set(obj['saddr'], line)
```
