### ISSUE TITLE
PF_RING support not compiling

### ISSUE THREAD

**Issue by toomuchio** [zmap/zmap#636]
Getting compiler errors following the install steps from https://github.com/zmap/zmap/blob/master/10gigE.md and using the latest PF_RING headers.

Bug must have been introduced on https://github.com/zmap/zmap/commit/de9de39de1b371fd5a66a7ff20e5f720a8a3ae5a

/home/test/zmap/src/recv-pfring.c: In function ‘recv_packets’:
/home/test/zmap/src/recv-pfring.c:60:2: error: unknown type name ‘timespec’; use ‘struct’ keyword to refer to the type
  timespec ts = pf_buffer->ts;
  ^~~~~~~~
  struct

**Comment by jaredthecoder** [comment]
I can confirm this is broken for me as well. Same issue, latest PF_RING headers.

**Comment by jaredthecoder** [comment]
Also to note, @toomuchio's fix in their PR worked for me.

**Comment by zakird** [comment]
I believe this has been resolved in #637. Closing.
