### ISSUE TITLE
After a successful scan, continue to scan immediately and receive 0 packets

### ISSUE THREAD

**Issue by lemorn** [zmap/zmap#640]
Hello, I found an interesting thing. I use Amazon cloud server with 5G bandwidth. After a successful scan, continue to scan immediately and receive 0 packets. Why does it suddenly recive 0?Thank you！
![image](https://user-images.githubusercontent.com/53805865/105825203-4cce8e00-5ffa-11eb-81c8-92a6d4e2cdae.png)

**Comment by zakird** [comment]
This is the cooldown period, no packets are being sent. If all hosts respond quickly, this is normal behavior.
