### ISSUE TITLE
How to report ips that don’t reply

### ISSUE THREAD

**Issue by AbGitter** [zmap/zmap#641]
Let’s say I scanned a range of ips on port 80, and wanted to then see which of the ips with port 80 open had port 443 closed, how could I run a second scan/one scan that checks both ports and outputs ones with 80 open and 443 closed?

**Comment by zakird** [comment]
This would be best done in a post-processing step. Scan 80, scan 443, then compute set difference.

**Comment by AbGitter** [comment]
Let’s say I’m on Centos 6 and first I run

zmap -p 80 -w websites.txt -o Step1.txt

Then I run

zmap -p 443 -w Step1.txt -o Step2.txt

What could I run on the centos machine to delete any ip that is in Step2.txt from Step1.txt?
