### ISSUE TITLE
High memory usage and crash

### ISSUE THREAD

**Issue by NewToGithubAB** [zmap/zmap#642]
**Describe the bug**
A clear and concise description of what the bug is. Inability to get ZMap to run on a specific platform or network is not considered a bug.
Zmap uses more than 6 GB of ram to load (it doesn't start the scan) a list of ips, and then crashes zmap (My server has 6GB, so I have no clue how much it wants for this list). the list has 29 million ips, which i'm sure is the main  problem, but I feel zmap shouldn't use 6 GB of ram for a 336MB file, I would expect 1.5 GB at most..
**CLI Arguments**
Please paste your ZMap invocation below

```
zmap -p21 -w 42.txt -B125M -o R.txt
```

**Expected behavior**
I expected it to load the list and use maybe 1 GB or 1.5 GB of memory to load and constantly store 29 million ips.

**Environment:**
 - OS: Centos 7

**Comment by dadrian** [comment]
For large whitelists, use `--list-of-ips-file` (`-I`) instead of `-w`. It should use roughly 512MB.
