### ISSUE TITLE
[FATAL] get-iface-ip: ioctl failure: Cannot assign requested address

### ISSUE THREAD

**Issue by crazyRM** [zmap/zmap#651]
**Describe the bug**
iv tryed to run zmap scanning on tons of vps and even a vm and every time no matter what diffrent way i try to install it i get this [FATAL] get-iface-ip: ioctl failure: Cannot assign requested address

**Environment:**
 - OS: [Ubuntu Server 18.04] [Centos 7] [Centos 6]
 - Version: [all newest]

**Additional context**
iv looked everywhere and cant find a fix please help

**Comment by zakird** [comment]
This is a duplicate of #625.

**Comment by crazyRM** [comment]
> This is a duplicate of #625.

No it’s not tho I can’t get it to work at all
