### ISSUE TITLE
Failed to send packets!

### ISSUE THREAD

**Issue by crazyRM** [zmap/zmap#652]
I have installed zMap a VM and other hosts (aka friends pcs), but it is not working properly. Can you please suggest me what is going wrong?

code when running:
 0:00 0%; send: 181 11.5 Kp/s (2.17 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:01 0%; send: 3350 3.04 Kp/s (2.97 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:02 0%; send: 3350 0 p/s (1.57 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:03 0%; send: 3350 0 p/s (1.07 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:04 0%; send: 3357 6 p/s (812 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:05 0% (65d left); send: 3362 4 p/s (654 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:06 0% (78d left); send: 3367 4 p/s (548 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:07 0% (90d left); send: 3367 0 p/s (471 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:08 0% (18h left); send: 464483 457 Kp/s (57.0 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:09 0% (4h57m left); send: 1896303 1.43 Mp/s (207 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:10 0% (3h28m left); send: 3010174 1.11 Mp/s (296 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%

With -5v logging

root@riley-VirtualBox:~# zmap -p23 -omfu.txt -v5
May 09 20:43:49.160 [TRACE] zmap: zmap main thread started
May 09 20:43:49.160 [TRACE] zmap: requested ouput-module: default

May 09 20:43:49.160 [DEBUG] zmap: no output module provided. will use csv.
May 09 20:43:49.160 [DEBUG] zmap: requested output field (0): saddr
May 09 20:43:49.160 [INFO] zmap: started
May 09 20:43:49.672 [DEBUG] zmap: no interface provided. will use default interface (eth0).
May 09 20:43:49.672 [DEBUG] zmap: no source IP address given. will use default address: 10.0.2.15.
May 09 20:43:49.672 [DEBUG] zmap: found gateway IP 10.0.2.2 on eth0
May 09 20:43:49.672 [DEBUG] zmap: MAC address of selected gateway 52:54:00:12:35:02
May 09 20:43:49.672 [INFO] zmap: zmap selected output module: csv
May 09 20:43:49.672 [DEBUG] csv: more than one field, will add headers
May 09 20:43:49.672 [TRACE] constraint: Initializing
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 0.0.0.0/8
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 10.0.0.0/8
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 100.64.0.0/10
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 127.0.0.0/8
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 169.254.0.0/16
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 172.16.0.0/12
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 192.0.0.0/24
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 192.0.2.0/24
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 192.88.99.0/24
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 192.168.0.0/16
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 198.18.0.0/15
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 198.51.100.0/24
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 203.0.113.0/24
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 240.0.0.0/4
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 255.255.255.255/32
May 09 20:43:49.672 [TRACE] blacklisting: blacklisting 224.0.0.0/4
May 09 20:43:49.672 [TRACE] constraint: Painting value 1
May 09 20:43:49.679 [DEBUG] constraint: 3702243328 IPs in radix array, 15104 IPs in tree
May 09 20:43:49.679 [DEBUG] blacklist: 3702258432 addresses allowed to be scanned (86% of address space)
May 09 20:43:49.679 [DEBUG] cyclic: using prime 4294967311, known_primroot 3
May 09 20:43:49.679 [DEBUG] cyclic: primitive root: 2527344651
May 09 20:43:49.681 [DEBUG] cyclic: starting point: 2359336920
May 09 20:43:49.681 [DEBUG] send: will send from 1 address on 28233 source ports
May 09 20:43:49.681 [TRACE] zmap: set thread 3929790208 affinity to core 0
May 09 20:43:49.681 [DEBUG] recv: thread started
May 09 20:43:49.681 [DEBUG] recv: using dev eth0
May 09 20:43:49.736 [DEBUG] recv: receiver ready
May 09 20:43:49.736 [DEBUG] recv: duplicate responses will be excluded from output
May 09 20:43:49.736 [DEBUG] recv: unsuccessful responses will be excluded from output
May 09 20:43:49.736 [DEBUG] zmap: using 1 sender threads
May 09 20:43:49.737 [TRACE] zmap: set thread 3919300352 affinity to core 1
May 09 20:43:49.741 [DEBUG] send: thread started
May 09 20:43:49.742 [TRACE] zmap: set thread 3910907648 affinity to core 2
 0:00 0%; send: 70 1.98 Kp/s (723 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:01 0%; send: 3351 3.28 Kp/s (3.04 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:02 0%; send: 3351 0 p/s (1.59 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%
 0:03 0%; send: 3351 0 p/s (1.08 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%

Please Help! i can open ports if needed and what it has to be on TCP or so

**Comment by crazyRM** [comment]
btw it always says

 0 p/s (36.4 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hits: 0.00%

No matter how long i have it run for

**Comment by crazyRM** [comment]
is it bc im on a VM and it says

[DEBUG] zmap: no source IP address given. will use default address: 10.0.2.15.

how would i set it to 192.168.##.###
and let it use that if that is the problem!

**Comment by crazyRM** [comment]
wifi speed 

100Mbps Download
20Mbps Upload

one of the best in Australia!

**Comment by dadrian** [comment]
You need a public IP to use ZMap. You can specify source address on the command line.
