### ISSUE TITLE
Unable to filter for unsuccessful ICMPs

### ISSUE THREAD

**Issue by marklit** [zmap/zmap#655]
**Describe the bug**

I want to examine ICMP error codes of unsuccessful pings and see how long they took to manifest. I am able to filter on successful ICMP requests but not unsuccessful ones.

**CLI Arguments**

```
$ sudo zmap --probe-module=icmp_echo_time \
            -o result.csv \
            --output-module=csv \
            --output-fields=type,code,repeat,cooldown,icmp_id,seq,sent_timestamp_ts,sent_timestamp_us,dst-raw,classification,success \
            --output-filter="success = 0" \
            192.168.0.0/24
```

I've removed the default 192.168 rule from the boilerplate blacklist:

```bash
$ grep 192.168 /etc/zmap/blocklist.conf
#192.168.0.0/16      # RFC1918: Private-Use
```

If I include ``--verbosity=5`` in the command then the following is printed out:

```
Jun 22 13:14:05.866 [DEBUG] filter: will use output filter success = 0
...
Jun 22 13:14:06.947 [DEBUG] recv: unsuccessful responses will be included in output
```

The above leads me to believe unsuccessful pings will be included in the output.

The above does run without issue and results in:

```
Jun 09 17:14:31.300 [INFO] zmap: completed
```

**Example Target IP**

I am running this on my local network 192.168.0.0/24 for now.

**Expected behavior**

I would expect a CSV with all but the 7 IPv4s in use on my local network to be listed in the results file, with their ICMP error type and the microseconds it took for each failure to occur. Instead I'm given a CSV with just the headers.

**Environment:**
 - OS: Raspbian
 - Version: GitHub HEAD, compiled

**Comment by dadrian** [comment]
This may be related to #631, where the output filter application is unclear, and may/may not be getting applied.
