### ISSUE TITLE
JSON module producing negative numbers

### ISSUE THREAD

**Issue by arsarabi** [zmap/zmap#657]
Hello,

I've noticed that the JSON output module is producing negative numbers for the following fields whenever the MSB is one: saddr-raw, daddr-raw, seqnum, acknum. This is probably due to reading these as signed rather than unsigned integers. At first I thought this was the intended behavior, but the CSV module is outputting unsigned integers which makes more sense. Is it possible to make the behavior consistent? This is also creating issues with other software that read from ZMap (see https://github.com/stanford-esrg/lzr/issues/5). I'm using ZMap version 2.1.1 on Ubuntu 18.04.

**Comment by zakird** [comment]
Can you provide an example? The code looks right at a glance, and fields are output correctly when I run ZMap locally on Ubuntu. If this was an integer signing problem, I would expect half of the records to come out negative, and I just dumped 100,000 records without a single negative value output.

**Comment by arsarabi** [comment]
When I run `zmap -p 80 -N 10 -f saddr-raw,daddr-raw,seqnum,acknum -O json` I see lots of negative numbers. If you are not seeing the same thing then it's probably limited to my system. I'll track down the issue when I get a chance and report back if it has something to do with ZMap.

**Comment by dadrian** [comment]
This can happen if you pipe through `jq` or certain other JSON pretty-print software.

**Comment by arsarabi** [comment]
I was reading the raw output from ZMap. In any case, compiling the latest version fixed the issue for me (I had installed using `apt` before), so I'm closing the issue.
