### ISSUE TITLE
Enabling `--output-module=json` Returns Approx. Double the Number of IP's Responding 

### ISSUE THREAD

**Issue by JustinTimperio** [zmap/zmap#676]
**Describe the bug**
It is unclear to me if this is a bug or some very weird async behavior but enabling the JSON module always returns approximately double the number of IPs compared to the normal output. I have tested this on multiple systems across multiple ports and shards with the exact same behavior existing in each case.

**CLI Arguments**
```
sudo zmap -p 80 --shards=250 --shard=0 --seed=1337 -o shard_0.csv
cat shard_0.csv | wc -l 
243204
```
VS
```
sudo zmap -p 80 --shards=250 --shard=0 --seed=1337 -o shard_0.json --output-module=json
cat shard_0.json | wc -l 
514767
```

**Expected behavior**
I think most users would expect that enabling the JSON module would only change the output type. I certainly did not expect enabling it would yield 2x the number of responses.

**Environment:**
 - OS: Arch Linux 5.13.12-arch1-1 
 - Version: zmap 2.1.1

**Comment by dadrian** [comment]
Just to confirm, you checked something along the lines of `cat shard_0.json | jq -cr '.saddr' | sort | uniq -d | wc -l`?

Also, can you post the output of info-level logs or higher (`-v`) from startup, prior to sending the first packet?

**Comment by JustinTimperio** [comment]
@dadrian So when I discovered the bug, the entries were in a database so I just checked for duplicate ips which only came in about 3%(pretty average for what we scan). I'll do a quick double-check in bash just to be safe though.

**Comment by JustinTimperio** [comment]
Okay, so I just double-checked this, and here are the results.
```
cat shard_0.csv | sort | uniq -d | wc -l
0
```
VS
```
cat shard_0.json | jq -cr '.saddr' | sort | uniq -d | wc -
4473
```
Looks like some dups but certainly not enough to cause the discrepancy being seen here. 

Logs show nothing suspect but I'll pass them on just in case. 
[JSON_LOG.txt](https://github.com/zmap/zmap/files/7080232/JSON_LOG.txt)
[CSV_LOG.txt](https://github.com/zmap/zmap/files/7080233/CSV_LOG.txt)

**Comment by dadrian** [comment]
CSV
```
Aug 31 00:04:36.089 [DEBUG] recv: duplicate responses will be included in output
Aug 31 00:04:36.090 [DEBUG] recv: unsuccessful responses will be included in output
```

JSON
```
Aug 31 00:04:36.089 [DEBUG] recv: duplicate responses will be included in output
Aug 31 00:04:36.090 [DEBUG] recv: unsuccessful responses will be included in output
```

If you don't specify an output module, exclude duplicates and unsuccessful responses (RSTs), skip the header, and only output saddr, so that ZMap output can be easily piped into another program.

If you do specify an output module, whether it's JSON or CSV, we don't automatically do any of that. We should probably increase the verbosity of the log messages explaining this.

You're getting "extra" results in the JSON case because it includes RSTs _and_ duplicates, not just unique SYN ACKs
