### ISSUE TITLE
A potential error due to unreleased lock send_mutex

### ISSUE THREAD

**Issue by ycaibb** [zmap/zmap#677]
Hi developers, it seems the lock send_mutex is not released in the function `send_run`, if `send_run_init(st)==1`. I think, there shoud be `pthread_mutex_unlock(&send_mutex);` before returning `-1`.

https://github.com/zmap/zmap/blob/967c58953f39a6a4342ae1628dbc50c9ee957ac0/src/send.c#L214-L242

**Comment by dadrian** [comment]
Thanks for the report!
