### ISSUE TITLE
zmap doesn't run in kubernetes unless ARP gets pre-populated

### ISSUE THREAD

**Issue by d33tah** [zmap/zmap#678]
**Describe the bug**

When ran in kubernetes, zmap crashes with the following error (example):

```
Sep 09 13:47:57.825 [FATAL] zmap: could not detect GW MAC address for 10.244.0.237 on eth0. Try setting default gateway mac address (-G), or run "arp <gateway_ip>" in terminal.
```

This reproduces across different kubernetes providers and also on the latest git repository of zmap.

**CLI Arguments**

```
zmap --probe-module=icmp_echoscan
```

**Example Target IP**

Not applicable

**Expected behavior**

Communicate in the error that if it's happening in the kubernetes, a simple `wget http://example.com` might make it go away. Otherwise debugging this might be pretty complex.

Alternatively, automate this a bit more.

**Environment:**

* Default kubernetes set-up on DigitalOcean or Linode
* Example Dockerfile:

```
FROM golang:1.16

RUN apt-get update && apt-get install build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev -y

RUN git clone https://github.com/zmap/zmap.git && cd zmap && mkdir /zmap && cmake -DCMAKE_INSTALL_PREFIX=/zmap && make && make install
```

**Comment by dadrian** [comment]
To be honest, I'm surprised ZMap works on K8S at all, since all the Internet access is behind a NAT.

**Comment by nominalval** [comment]
It shouldn't work?? I observer that from 10 servers 1-2 give this error, other not. What it could be?
