### ISSUE TITLE
Data consumption and some other questions

### ISSUE THREAD

**Issue by 737simpilot** [zmap/zmap#679]
Hi. Have a few questions:

A) If zmap scans just one port across the whole IPv4 space, how much data is consumed? I plan on running zmap in Linode so I'd like to know how much data a one port scan will consume so that I don't go past my data allotment. I'm thinking it's not very much, but I'd like to know the real numbers.

B) The readme states a 45 minute scan across all of the IPv4 space with a Gig connection. Is that just for one port? How long would it take for all 65,535 ports? I guess I'd like to know the rate for a one port scan on a Gig connection. My project just involves looking to see if a port is open. Don't need banners or other stuff beyond that.

Thanks.

**Comment by MiyakoYakota** [comment]
> If zmap scans just one port across the whole IPv4 space, how much data is consumed? I plan on running zmap in Linode so I'd like to know how much data a one port scan will consume so that I don't go past my data allotment. I'm thinking it's not very much, but I'd like to know the real numbers.

A standard SYN packet is 44 (Minimal) <-> 72 (Normal) bytes and SYN-ACK is around 70 bytes (according to [Akamai](https://www.akamai.com/blog/security/anatomy-of-a-syn-ack-attack)). Not sure if zmap sends RST upon receiving SYN-ACK, but if it does, my 1 minute google says they're [around 11 bytes](https://isc.sans.edu/forums/diary/The+special+case+of+TCP+RST/26824/). Multiply these by the number of ports and hosts and you should get an answer with a huge margin of error.

> The readme states a 45 minute scan across all of the IPv4 space with a Gig connection. Is that just for one port? How long would it take for all 65,535 ports?

45 Minutes * 65,535 Ports = 2,949,075 minutes


(Not a professional or related to zmap development in any way)

**Comment by 737simpilot** [comment]
Thanks for the input. Sounds prudent I guess based on your quick research. Looks like ~ 4.5 MB per IP address for all 65,535 ports. And given there are over 4.2 billion IPs in the IPv4 space that means a ton of data I guess. 

>45 Minutes * 65,535 Ports = 2,949,075 minutes

That's around ~ 5.5 years. :laughing: 


My intended use case for right now is one port scanning for a project I'm a member of.  So I guess I'm looking at around ~ 280 GB based on just 70 bytes per IP and port. ( 70 * 4 billion).
