### ISSUE TITLE
Zmap replaces some bytes with null bytes

### ISSUE THREAD

**Issue by nveloso** [zmap/zmap#680]
**Describe the bug**
Zmap replaces some bytes of UDP response with null bytes. I capture the received packet and looked into it with Wireshark and the response packet has all the data without null bytes. Sometimes zmap inserts the null bytes closer to the end of the response and sometimes is the last bytes.

Zmap output:
`{ "saddr": "189.130.197.6", "daddr": "REDACTED", "udp_pkt_size": 1469, "data": "3c3f786d6c2076657273696f6e3d27312e302720656e636f64696e673d277574662d38273f3e3c736f61703a456e76656c6f706520786d6c6e733a736f61703d22687474703a2f2f7777772e77332e6f72672f323030332f30352f736f61702d656e76656c6f70652220786d6c6e733a643d22687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030352f30342f646973636f766572792220786d6c6e733a7773616469733d22687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030342f30382f61646472657373696e672220786d6c6e733a646e3d22687474703a2f2f7777772e6f6e7669662e6f72672f76657231302f6e6574776f726b2f7773646c223e3c736f61703a4865616465723e3c7773616469733a416374696f6e3e687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030352f30342f646973636f766572792f50726f62654d6174636865733c2f7773616469733a416374696f6e3e3c7773616469733a4d65737361676549443e757569643a63393037373733322d613239342d663930612d373561632d6561336365356632613465383c2f7773616469733a4d65737361676549443e3c7773616469733a52656c61746573546f3e75726e3a757569643a37336165363630312d396134362d343632322d396134662d6565376162376130303538333c2f7773616469733a52656c61746573546f3e3c7773616469733a546f3e687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030342f30382f61646472657373696e672f726f6c652f616e6f6e796d6f75733c2f7773616469733a546f3e3c643a41707053657175656e636520496e7374616e636549643d2239353432383439363022204d6573736167654e756d6265723d22333522202f3e3c2f736f61703a4865616465723e3c736f61703a426f64793e3c643a50726f62654d6174636865733e3c643a50726f62654d617463683e3c7773616469733a456e64706f696e745265666572656e63653e3c7773616469733a416464726573733e75726e3a757569643a38306534653936322d633462612d316332312d616162652d3730303638306466353731623c2f7773616469733a416464726573733e3c2f7773616469733a456e64706f696e745265666572656e63653e3c643a54797065733e646e3a4e6574776f726b566964656f5472616e736d69747465723c2f643a54797065733e3c643a53636f7065733e6f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f766964656f5f656e636f646572206f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f617564696f5f656e636f646572206f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f766964656f5f616e616c79746963206f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f70747a206f6e7669663a2f2f7777772e6f6e7669662e6f72672f6c6f636174696f6e2f676c6f62616c206f6e7669663a2f2f7777772e6f6e7669662e6f72672f6e616d652f6e6574776f726b63616d657261206f6e7669663a2f2f7777772e6f6e7669662e6f72672f50726f66696c652f53747265616d696e67206f6e7669663a2f2f7777772e6f6e7669662e6f72672f68617264776172652f464438313633206f6e7669663a2f2f7777772e6f6e7669662e6f72672f6465766963652f43616d6572613c2f643a53636f7065733e3c643a5841646472733e687474703a2f2f3139322e3136382e312e32313a383030302f6f6e7669662f6465766963655f736572766963653c2f643a5841646472733e3c643a4d6574616461746156657273696f6e3e3935343238343936313c2f643a4d6574616461746156657273696f6e3e3c2f643a50726f62654d617463683e3c2f643a50726f62654d6174636865733e3c2f736f61703a426f64793e3c2f736f61703a456e76656c6f000000" }`

If you take a look into the last 3 bytes of the data field, they are null bytes but they should be `70653e` instead. In Wireshark I don't have any null byte, just the expected response.

**CLI Arguments**

```
zmap --probe-module=udp --target-port=3702 --output-module=json --output-fields=saddr,daddr,udp_pkt_size,data --ignore-invalid-host --verbosity=0 --quiet --probe-args=file:/zmap/examples/udp-probes/wsd_3702.pkt -T 1 --source-ip=REDACTED --bandwidth=10M --cooldown-time=12 -i wan0 189.130.197.6/32
```

**Example Target IP**
All on UDP port 3702

- 189.130.197.6
- 89.177.113.5
- 190.219.18.183
- 129.236.30.17
- 85.187.2.134
- 119.200.32.197
- 181.231.5.208
- 77.29.105.214
- 125.242.142.13
- 73.166.97.85
- 24.88.206.112

**Expected behavior**
I expected zmap to not replace bytes with null bytes. I expected zmap to output the same response as I found in Wireshark packets.

I expected the record above to be like:
`{ "saddr": "189.130.197.6", "daddr": "REDACTED", "udp_pkt_size": 1469, "data": "3c3f786d6c2076657273696f6e3d27312e302720656e636f64696e673d277574662d38273f3e3c736f61703a456e76656c6f706520786d6c6e733a736f61703d22687474703a2f2f7777772e77332e6f72672f323030332f30352f736f61702d656e76656c6f70652220786d6c6e733a643d22687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030352f30342f646973636f766572792220786d6c6e733a7773616469733d22687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030342f30382f61646472657373696e672220786d6c6e733a646e3d22687474703a2f2f7777772e6f6e7669662e6f72672f76657231302f6e6574776f726b2f7773646c223e3c736f61703a4865616465723e3c7773616469733a416374696f6e3e687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030352f30342f646973636f766572792f50726f62654d6174636865733c2f7773616469733a416374696f6e3e3c7773616469733a4d65737361676549443e757569643a63393037373733322d613239342d663930612d373561632d6561336365356632613465383c2f7773616469733a4d65737361676549443e3c7773616469733a52656c61746573546f3e75726e3a757569643a37336165363630312d396134362d343632322d396134662d6565376162376130303538333c2f7773616469733a52656c61746573546f3e3c7773616469733a546f3e687474703a2f2f736368656d61732e786d6c736f61702e6f72672f77732f323030342f30382f61646472657373696e672f726f6c652f616e6f6e796d6f75733c2f7773616469733a546f3e3c643a41707053657175656e636520496e7374616e636549643d2239353432383439363022204d6573736167654e756d6265723d22333522202f3e3c2f736f61703a4865616465723e3c736f61703a426f64793e3c643a50726f62654d6174636865733e3c643a50726f62654d617463683e3c7773616469733a456e64706f696e745265666572656e63653e3c7773616469733a416464726573733e75726e3a757569643a38306534653936322d633462612d316332312d616162652d3730303638306466353731623c2f7773616469733a416464726573733e3c2f7773616469733a456e64706f696e745265666572656e63653e3c643a54797065733e646e3a4e6574776f726b566964656f5472616e736d69747465723c2f643a54797065733e3c643a53636f7065733e6f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f766964656f5f656e636f646572206f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f617564696f5f656e636f646572206f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f766964656f5f616e616c79746963206f6e7669663a2f2f7777772e6f6e7669662e6f72672f747970652f70747a206f6e7669663a2f2f7777772e6f6e7669662e6f72672f6c6f636174696f6e2f676c6f62616c206f6e7669663a2f2f7777772e6f6e7669662e6f72672f6e616d652f6e6574776f726b63616d657261206f6e7669663a2f2f7777772e6f6e7669662e6f72672f50726f66696c652f53747265616d696e67206f6e7669663a2f2f7777772e6f6e7669662e6f72672f68617264776172652f464438313633206f6e7669663a2f2f7777772e6f6e7669662e6f72672f6465766963652f43616d6572613c2f643a53636f7065733e3c643a5841646472733e687474703a2f2f3139322e3136382e312e32313a383030302f6f6e7669662f6465766963655f736572766963653c2f643a5841646472733e3c643a4d6574616461746156657273696f6e3e3935343238343936313c2f643a4d6574616461746156657273696f6e3e3c2f643a50726f62654d617463683e3c2f643a50726f62654d6174636865733e3c2f736f61703a426f64793e3c2f736f61703a456e76656c6f70653e" }`

**Environment:**
 - OS: Ubuntu 16.04.5 LTS 
 - Version: commit from 7 Jul 2021, commit hash: 73cf120. [https://github.com/zmap/zmap/tree/73cf12084475b6009a7c6f99236ad341674a1af6](https://github.com/zmap/zmap/tree/73cf12084475b6009a7c6f99236ad341674a1af6)

**Additional context**

**Comment by dadrian** [comment]
My guess is that our packet capture max size passed to libpcap is too small.

**Comment by nveloso** [comment]
Can this be related to IP/UDP fragmentation?

**Comment by lhmenden2** [comment]
Assuming standard MTU of 1500, and UDP + IP header size of 28 bytes, these responses come very close to maxing out the packet size (len 1461 bytes, max 1472 bytes).

What happens when ZMAP gets a response packet that is greater than 1472 bytes?

**Comment by dadrian** [comment]
Our PCAP snaplen is 1500, and the total length of this packet is 1469+20+14 = 1503. This explains the zeros---our buffer is the full size and zeroed, but then PCAP only populates the first 1500 bytes.

**Comment by dadrian** [comment]
I increased the snaplen, please try again with main
