### ISSUE TITLE
UDP probe arbitrarily missing hosts

### ISSUE THREAD

**Issue by averysumner** [zmap/zmap#683]
**Describe the bug**
When using a zmap UDP probe, it will arbitrarily miss some confirmed hosts when scanning the entire IPv4 range. When these hosts are whitelisted specifically, zmap is able to illicit a response from them.

**CLI Arguments**

```
zmap -M udp -p 1001 --probe-args=hex:0900 -f saddr,data -o output.csv
```

**Example Target IP**
All three of the following should result in a hex response of `0a00`, these are also the hosts that zmap was unable to consistently find:
65.21.255.0
35.230.103.180
116.202.21.138

**Expected behavior**
I expected it to be able to consistently find these hosts when scanning the IPv4 range.

**Environment:**
 - OS: Debian Buster
 - Version: from package manager

**Additional context**
This was running on a server at a rate of about 900-1000 kP/s. It is possible that my VPS provider may be to blame.

**Comment by zakird** [comment]
This is likely due to packet drop, especially if you're on a VPS, but it's pretty hard to tell. If they're just ephemerally missing that might be it. You can also try a more recent version. While I don't know what's in your package manager (that description is rather unhelpful...), it's likely quite outdated compared to 3.0.0-RC1.

**Comment by averysumner** [comment]
> This is likely due to packet drop, especially if you're on a VPS, but it's pretty hard to tell. If they're just ephemerally missing that might be it. If they're consistently not findable, then it's probably a ZMap issue. You can also try a more recent version. While I don't know what's in your package manager (that description is rather unhelpful...), it's likely quite outdated compared to 3.0.0-RC1.

Yeah, I'm thinking it is from packet drop. I ran it again with 500 kP/s and I'm getting significantly more hits. It's from apt on debian, so likely from the debian repos. I'll try building from source on the newest version. If that doesn't work I'll just give in and shard it out over multiple instances.

**Comment by averysumner** [comment]
Seems to be due to packet drop from what I can tell... Is there a reason it's not detected by zmap in the "drop" output?

**Comment by averysumner** [comment]
More than likely due to packet drop, closing this.
