### ISSUE TITLE
Debian 11 Segfault

### ISSUE THREAD

**Issue by toomuchio** [zmap/zmap#685]
Installed Deb 11, minimal latest. Clone master off git local build.

Run a udp scan and after a few seconds, seg fault.

Not sure what could be causing this, I reinstalled Deb 10 runs fine.

Just wondering if anybody else has run into this.

**Comment by dadrian** [comment]
Can you post your arguments / which UDP scan type you were using?

**Comment by dadrian** [comment]
I believe this was fixed by #689
