### ISSUE TITLE
No data in Redis server?

### ISSUE THREAD

**Issue by Furry** [zmap/zmap#691]
I apologize if this question is a bit trivial, but I can't quite figure it out.

I have a Redis instance listening on the default port within a Docker Container with an exposed port. To test, I'm running the command `zmap -p 80 -n 100 --output-module=redis-csv -f "saddr,daddr,sport,saddr-raw,timestamp-str,success"`, which according to all output works perfectly,
![xCJieg2](https://user-images.githubusercontent.com/22103494/163692781-abee4fc1-1d96-4b64-8785-2d06344679a5.png)
Though my Redis doesn't seem to have any new elements in it. This is my first time using Redis, so I'm likely doing something wrong but I'm not sure what. Any advice would be greatly appreciated!

**Comment by dadrian** [comment]
You didn't get any results, which is why there was no output.
