### ISSUE TITLE
Very slow sending rate despite high bandwidth

### ISSUE THREAD

**Issue by meikelko** [zmap/zmap#692]
I am trying to scan the entire IPv4 for my final thesis. As a setup I am using Zmap on the Linux sub system on windows (Ubuntu-20.04) and a VPN connection to my home university with a fairely high ping around 200-300ms. I am achieving around 100mb download- and uploadspeed (with the VPN turned on).

I noticed a very slow sending rate around 4.75 Kp/s with the following invocation

`sudo zmap -M udp -p 53 --probe-args=file:examples/udp-probes/dns_53_queryAwww.google.com.pkt -o sample.csv
`

I tried to adjust the bandwidth manually with the -B option, starting with 2MB, increasing. It turns out that anything above "-B 4M" results in the same sending rate as stated above.

I hope you have an idea what could cause that issue.

Additional information:

- Zmap version: "zmap 2.1.1"
- I also tried using my home network with around 250mb up and download rate (~ ping around 2ms). Here I achieved slightly more, around 7 kp/s sending rate.
- I performed a speedtest on my linux subsystem to make sure I really achieve the data rate mentioned above.
- During testing the sending rate, I ran above command around 24 hours without noticing an increase in the sending rate.

**Comment by dadrian** [comment]
Try using the current ZMap release candidate from Github. 2.1.1 is old and bandwidth calculations with UDP had a longstanding bug that has since been fixed, IIRC.

**Comment by dadrian** [comment]
Please reopen if this persists after you've tried the 3.0.0-beta1
