### ISSUE TITLE
 Zmap cannot run successfully

### ISSUE THREAD

**Issue by fandazhou123** [zmap/zmap#696]
### os:
- CentOS
### install command:
- cmake .
- make -j4
- sudo make install.
### command that I want to excute and the error I get: 
- ./zmap -p 80 192.168.0.0/16 : 
   - [ERROR] blocklist: no addresses are eligible to be scanned in the current configuration. This may be because the blocklist being used by ZMap (/etc/zmap/blocklist.conf) prevents any addresses from receiving probe packets.
    [FATAL] zmap: unable to initialize blocklist / allowlist

- ./zmap -p 80 45.33.45.53
   -  [WARN] blocklist: ZMap is currently using the default blocklist located at /etc/zmap/blocklist.conf. By default, this blocklist excludes locally scoped networks (e.g. 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blocklist by editing the default ZMap configuration at /etc/zmap/zmap.conf.
    [FATAL] get-iface-ip: Unable to automatically identify the correct source address for nflog interface. ioctl failure: No such device. If this is the unexpected interface, you can manually specify the correct interface with "-i" flag. If this is the correct interface, you likely need to manually specify the source IP address to use with the "-S" flag.
- ./zmap -N 5 -B 10M -p 80 -S 45.33.45.53
   -  [FATAL] get-gateway: The specified network ("nflog") does not match the interface associated with the default gateway (ens160). You will need to manually specify the MAC address of your gateway using the "--gateway-mac" flag.

**Comment by fandazhou123** [comment]
By the way, I can't find blocklist.conf in /etc/zmap but in zmap-main/conf/. When I delete 192.168.0.0/16 in blocklist.conf, it  still warn that FATAL: zmap: unable to initialize blocklist / allowlist.

**Comment by dadrian** [comment]
It looks like the bug is the warning is not listing the correct location of the default blocklist. As a workaround, manually specify a blocklist file from the CLI.
