### ISSUE TITLE
 ipv6_target_file: could not parse target IPv6 address from line: 

### ISSUE THREAD

**Issue by lzy-lsf** [zmap/zmap#699]
I keep getting address resolution errors when using the tool to scan ipv6. What's the reason, please?
The address is in the TXT file. Each line has an ipv6 address. The address is correct and active.

Aug 31 21:19:10.796 [INFO] zmap: output module: csv
Aug 31 21:19:10.796 [INFO] csv: no output file selected, will use stdout
Aug 31 21:19:10.808 [INFO] recv: Data link layer Ethernet
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
: Success:19:10.809 [FATAL] ipv6_target_file: could not parse target IPv6 address from line:

**Comment by ogasser** [comment]
Are there empty lines in your file containing the IPv6 target addresses? If so, please delete the empty lines and try again.

**Comment by lzy-lsf** [comment]
Thank you for your reply. This is the file I tested and the content is correct. However, parsing errors are always reported, and I really can't find the reason.
![image](https://user-images.githubusercontent.com/60493049/188054628-d9f96185-4070-4299-8391-69ca2aeaf3a7.png)
![image](https://user-images.githubusercontent.com/60493049/188054712-0d4b0852-e1dc-4af5-8f72-39f5e5cd9c45.png)

**Comment by ogasser** [comment]
Are there spaces (or other invisible characters) before the newline? If yes, remove them and try again. If not, please upload the file somewhere or send me an email with it, so that I can test it out myself.

**Comment by lzy-lsf** [comment]
![image](https://user-images.githubusercontent.com/60493049/188633376-42a278a5-3a88-42e4-ad80-d3545217fda2.png)
Hello, I have found the reason, it is the problem of the tool, the default file format of this tool is DOS after opening the file, and the problem is solved by changing it to UNIX.

**Comment by Hzwords** [comment]
hello,Why do I get the following error when I run the  command:

map --probe-module=icmp6_echoscan --ipv6-target-file=addresses1.txt --output-file=result.txt --ipv6-source-ip=2001:250:xxxx --bandwidth=10M --cooldown-time=4

zmap: unrecognized option '--ipv6-target-file=addresses1.txt'

**Comment by ogasser** [comment]
For IPv6 scanning you need to use the following repository: https://github.com/tumi8/zmap
