### ISSUE TITLE
zmap is scanning only 24% of subnet

### ISSUE THREAD

**Issue by h33raj** [zmap/zmap#700]
we have tried to scan the whole internet or the subnet. 

`Oct 05 07:45:01.061 [DEBUG] constraint: 1040187392 IPs in radix array, 0 IPs in tree
Oct 05 07:45:01.061 [DEBUG] constraint: 1040187392 addresses (24% of address space) can be scanned`

Our results are very less, we have observed that some of the IPs were not scanned. Individually when the zmap was run on the IP we could see the result.

**Comment by dadrian** [comment]
Did you try with current `main`?

**Comment by OldMonK00007** [comment]
hey im also facing same issue the results are very less ! what's the point of high speed  when results are too low
