### ISSUE TITLE
Data races in  ztee.c

### ISSUE THREAD

**Issue by ycaibb** [zmap/zmap#710]
Dear developers:

The shared variable `process_done` is protected by lock in the  process_done
https://github.com/zmap/zmap/blob/73cf12084475b6009a7c6f99236ad341674a1af6/src/ztee.c#L318-L330

The shared variable `process_done` is not protected by lock in the  process_done
https://github.com/zmap/zmap/blob/73cf12084475b6009a7c6f99236ad341674a1af6/src/ztee.c#L368-L371

**Comment by dadrian** [comment]
Confirmed `int` is atomic enough for our purposes.
