### ISSUE TITLE
How can i make zmap scan a range

### ISSUE THREAD

**Issue by dudulitrin** [zmap/zmap#717]
How can i make zmap scan a range for example from 120.0.0.0 to 220.0.0.0. I Try: zmap -p 80 -S 120.0.0.0-220.0.0.0 and zmap -p 80 -S 120-220.0.0.0 and didnt work.
Can someone explain?

**Comment by imfht** [comment]
Hi. you can have a look at the latest zmap.
Download v3.0.0-rc1 at `https://github.com/zmap/zmap/archive/refs/tags/v3.0.0-RC1.zip`
and follow `https://github.com/zmap/zmap/blob/main/INSTALL.md` to compile it.

run zmap -h it output 
```
Examples:
    zmap -p 80 (scan full IPv4 address space for hosts on TCP/80)
    zmap -N 5 -B 10M -p 80 (find 5 HTTP servers, scanning at 10 Mb/s)
    zmap -p 80 10.0.0.0/8 192.168.0.0/16 (scan both subnets on TCP/80)
    zmap -p 80 1.2.3.4 10.0.0.3 (scan 1.2.3.4, 10.0.0.3 on TCP/80)
```
I think `zmap -p 80 10.0.0.0/8 192.168.0.0/16 (scan both subnets on TCP/80)` would be a good choice for you.(just change  120.0.0.0-220.0.0.0 in cidr format)

**Comment by dudulitrin** [comment]
> Hi. you can have a look at the latest zmap. Download v3.0.0-rc1 at `https://github.com/zmap/zmap/archive/refs/tags/v3.0.0-RC1.zip` and follow `https://github.com/zmap/zmap/blob/main/INSTALL.md` to compile it.
> 
> run zmap -h it output
> 
> ```
> Examples:
>     zmap -p 80 (scan full IPv4 address space for hosts on TCP/80)
>     zmap -N 5 -B 10M -p 80 (find 5 HTTP servers, scanning at 10 Mb/s)
>     zmap -p 80 10.0.0.0/8 192.168.0.0/16 (scan both subnets on TCP/80)
>     zmap -p 80 1.2.3.4 10.0.0.3 (scan 1.2.3.4, 10.0.0.3 on TCP/80)
> ```
> 
> I think `zmap -p 80 10.0.0.0/8 192.168.0.0/16 (scan both subnets on TCP/80)` would be a good choice for you.(just change 120.0.0.0-220.0.0.0 in cidr format)

i want to scan from 10.0.0.0 to 150.0.0.0 for example, not subclass for 10.0.0.0 and 150.0.0.0.
i want to start with 10.x.x.x go to 11.x.x.x , 12.x.x.x ,13.x.x.x ,......, 150.x.x.x. this is what i mean.

**Comment by dadrian** [comment]
You have to specify ranges as CIDRs, so for your example you would need to compute a set of CIDRs that span the range 10.0.0.0/8 through 150.0.0.0/8 (I think for you that would be 10.0.0.0/8, 11/8, 12/8, 13/8, 14/8, 15/8, 16/4, 32/4, 64/3, 128/4, 144/8, 145/8, 146/8, 147/8, ... 149.0.0.0/8)
