### ISSUE TITLE
When I am trying to open ZMap using MATLAB, I am getting this error in the code

### ISSUE THREAD

**Issue by Ruba2723** [zmap/zmap#732]
1. In rc_cross_a2.m code I am getting this error - 

Error: File: rc_cross_a2.m Line: 620 Column: 33
Invalid syntax for calling function 'tmpgri' on the path. Use a valid syntax or explicitly initialize 'tmpgri' to make it a
variable. 
620 line - normlap2=NaN(length(tmpgri(:,1)),1);

Error in ZmapMainWindow/create_all_menus/create_xsec_analysis_menu (line 96)
        rc_cross_a2.AddMenuItem(submenu, @()obj.xsec_zap);
Line 96 - obj.EventSelector=res.evsel;

2. In create_all_menus code I am getting this error - 

Error in ZmapMainWindow/create_all_menus (line 29)
    create_xsec_analysis_menu();
Line 29 - create_xsec_analysis_menu();

3, In ZmapMainWindow,m code I am getting this error - 

Error in ZmapMainWindow/prepareMainFigure (line 701)
            obj.create_all_menus(true); % plot_base_events(...) must have already been called, in order to load the features from ZG

Error in ZmapMainWindow (line 207)
            obj.prepareMainFigure();

4. In zmap.m code I am getting this error - 

Error in zmap (line 139)
            ZmapMainWindow(cw,ZG.primeCatalog);

Please help me solve these errors!!!!!!!!

**Comment by zakird** [comment]
I think this is the wrong project. This is the ZMap that is a network scanner.
