### ISSUE TITLE
ZMap does not send at 1gbps on vanilla Ubuntu

### ISSUE THREAD

**Issue by zakird** [zmap/zmap#734]
ZMap no longer sends probes at 1.44M pps on modern, vanilla Ubuntu systems. We seem to plateau around 1M pps. We need to investigate what has changed and address the problem to return to be able to scan at >1gbps. As a first step, I would recommend that we look at batched sending of packets on Linux-based systems.

**Comment by jhalderm** [comment]
I was recently tripped up by the fact that ZMap now defaults to using only one send thread. It happily pushes multiple Gbps if I use 5 senders. This is ZMap 3.0 on a 6-core VM running stock Ubuntu 22.04:

```
$ sudo zmap -p 80 -T5 -B 10G -o /dev/null
 0:00 0%; send: 92 1 p/s (4.15 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 2792412 2.79 Mp/s (2.73 Mp/s avg); recv: 37868 37.9 Kp/s (37.0 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.36%
 0:02 0%; send: 5665652 2.87 Mp/s (2.80 Mp/s avg); recv: 83535 45.7 Kp/s (41.3 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.47%
 0:03 0%; send: 8530811 2.86 Mp/s (2.82 Mp/s avg); recv: 128796 45.3 Kp/s (42.6 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.51%
 0:04 0%; send: 11417487 2.89 Mp/s (2.84 Mp/s avg); recv: 174348 45.5 Kp/s (43.3 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.53%
 0:05 0% (21m left); send: 14292988 2.87 Mp/s (2.85 Mp/s avg); recv: 219629 45.3 Kp/s (43.7 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.54%
```

I'll add that although I didn't have to change any OS settings in the guest, I did have to do a lot of tuning in the hypervisor's BIOS to get decent performance under NUMA.

**Comment by zakird** [comment]
Oh, interesting! I wasn't able to push past ~1M pps with multiple sender threads, but sounds like that could be attributed to our host configuration rather than a more generic problem.

I don't know if there's any good reason we're defaulting to one sender thread. I could have sworn we used to look at the number of cores. It certainly seems to me that out of the box that we want to be able to run at 1gbps. @dadrian do you remember either?

**Comment by dadrian** [comment]
We used to hit about 90% of 1Gbps with a single thread. We switched it to default to 1 thread because in the common case, you don't scan at line rate and you're piping ZMap output into other tools (ZGrab). The way rate limting is implemented, ZMap will suck up every core it assigns a thread to. So defaulting to 1 thread kept us from constantly having trash data because we forgot to limit ourselves.

**Comment by dadrian** [comment]
I suspect the "right" answer is to switch ZMap to use io_uring, and hope that we both get faster per-core performance, and can reach 10G+ on capable uplinks without having to call PF_RING.

**Comment by phillip-stephens** [comment]
@dadrian Hadn't heard of `io_uring`, looks pretty cool! Looks like there's a library that helps abstract some of the complexity away, [liburing](https://github.com/axboe/liburing). I did notice that it's only available in _very_ up-to-date linux distros. Like for [Ubuntu](https://manpages.ubuntu.com/cgi-bin/search.py?q=io_uring&cx=003883529982892832976%3A5zl6o8w6f0s&cof=FORID%3A9&ie=UTF-8&siteurl=manpages.ubuntu.com%2Fmanpages%2Fjammy%2F&ref=manpages.ubuntu.com%2Fmanpages%2Flunar%2Fman7%2Fio_uring.7.html&ss=1033j187267j9), >= 22.04. But could def be interesting to look into for users that need that level of performance.

**Comment by dadrian** [comment]
I think @jhalderm might have a patch, but I'd recommend not bringing in another library, since we'd have a single call with static properties (send packets fast on L2). I haven't used it myself at all. I do know it can be tricky to get to work both correct and fast, but when it does, it really shines.
