### ISSUE TITLE
Bogus check for config file existence

### ISSUE THREAD

**Issue by yurivict** [zmap/zmap#735]
The check in [this](https://github.com/zmap/zmap/blob/main/CMakeLists.txt#L138) line is bogus.

The installation command doesn't generally install into ```/etc/zmap/```. Instead, it installs into ```$DESTDIR/etc/zmap/```, where ```$DESTDIR``` is a stage directory, which may or may not be empty. ```$DESTDIR``` is only known at the time when ```gmake install``` runs. cmake has no way of knowing what ```$DESTDIR``` will be during the ```gmake install``` command.

Therefore, unfortunately, this existence check is bogus - it can't be properly performed considering the way how cmake+gmake commands work.

I suggest that you remove this check, along with the ```FORCE_CONF_INSTALL``` cmake option. This option is meaningless when ```$DESTDIR``` is set during ```gmake install```.

Version: 3.0.0
FreeBSD 13.2

**Comment by zakird** [comment]
Thanks, agree this looks broken. I'm not sure that the option is meaningless as much as that we're not using `$DESTDIR` like we should be.

**Comment by yurivict** [comment]
FORCE_CONF_INSTALL depends on the validity of a bogus check, so it can't be valid itself.
