### ISSUE TITLE
Validation of destination port fails

### ISSUE THREAD

**Issue by davideandres95** [zmap/zmap#736]
**Describe the bug**
Validation of destination port fails if `validation[1] % num_ports` is greater than `(validation[1] + zconf.packet_streams - 1) % num_ports` at:

https://github.com/zmap/zmap/blob/146ded1a1949220c815302df26052dbc9bfa12a4/src/probe_modules/packet.h#L147C1-L159

This can happen when the group is completely cycled.

**CLI Arguments**

```
zmap --probe-module=tcp_synscan --output-module=json --output-file=res.json --output-fields=success,ttl,saddr,daddr,repeat,timestamp_ts,timestamp_us,classification --target-port=80 --source-port=40002-40005 --gateway-mac=fa:76:a0:08:60:5f --allowlist-file=whitelist.conf --probes=3 --output-filter= --interface=def-red --bandwidth=100M --rate=0 --sender-threads=1 --source-ip=10.0.1.1 --verbosity 4
```

**Example Target IP**
I am running netcat at my local target (10.0.3.252) port 80.

**Expected behavior**
Validation should pass

**Environment:**
 - OS: Ubuntu Server 16.04
 - Version: Github HEAD

**Comment by zakird** [comment]
Just writing down some notes, validated that this is indeed broken and test here:

```c
// Returns 0 if dst_port is outside the expected valid range, non-zero otherwise
int check_dst_port(uint16_t port, int num_ports,
				 uint32_t *validation)
{
	if (port > SOURCE_PORT_LAST || port < SOURCE_PORT_FIRST) {
		return 0;
	}
	int32_t to_validate = port - SOURCE_PORT_FIRST;
	int32_t min = validation[1] % num_ports;
	int32_t max = (validation[1] + PACKET_STREAMS  - 1) % num_ports;

	return (((max - min) % num_ports) >= ((to_validate - min) % num_ports));
}

uint16_t get_src_port(int num_ports, int probe_num, uint32_t *validation)
{
	return SOURCE_PORT_FIRST +
	       ((validation[1] + probe_num) % num_ports);
}


//uint16_t ports[] = {80, 443, 50000};

int main(void) {
	srand(time(NULL));
	for (int t=0; t < TRIALS; t++) {
		printf("Trial %i\n", t);
		uint32_t validation[4];
		validation[0] = rand();
		validation[1] = rand();
		validation[2] = rand();
		validation[3] = rand();
		for (int i=0; i< PACKET_STREAMS; i++) {
			uint16_t dst =  get_src_port(NUM_PORTS, i, validation);
			printf("\tport: %hu, validates: %i\n", dst, check_dst_port(dst, NUM_PORTS, validation));
		}
	}
}```

Working on a fix

**Comment by zakird** [comment]
This should be fixed in #738. @davideandres95 would you be willing to try again and see if that resolves for you?

**Comment by davideandres95** [comment]
> This should be fixed in #738. @davideandres95 would you be willing to try again and see if that resolves for you?

After testing it I can confirm this fixes the issue. Thank you!

**Comment by zakird** [comment]
Thank you!!

**Comment by davideandres95** [comment]
I believe the inequality sign in the warning is flipped:
https://github.com/zmap/zmap/blob/3a188f944a8277ddc57b5b2e4662341047240cfb/src/zmap.c#L657
Could this be? Sorry that I missed it before.
