### ISSUE TITLE
ZMap has memory leaks/still reachable memory at program termination

### ISSUE THREAD

**Issue by phillip-stephens** [zmap/zmap#743]
## ZMap Version
Most current `main`

## Description
After compiling `main` from source in an Ubuntu Docker (Dockerfile below), I ran the binary with `Valgrind` and it's showing we should be explicitly freeing our memory a bit better.

## Valgrind Report
Valgrind Command - `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose zmap --bandwidth=10M --target-ports=80 --max-targets=100 --output-file=results.csv -c 1`
```
==13== LEAK SUMMARY:
==13==    definitely lost: 8 bytes in 1 blocks
==13==    indirectly lost: 0 bytes in 0 blocks
==13==      possibly lost: 0 bytes in 0 blocks
==13==    still reachable: 4,343,720 bytes in 303 blocks
==13==         suppressed: 0 bytes in 0 blocks
```

## Dockerfile (For reproducibility)
```
FROM ubuntu:latest

RUN apt-get update -y --quiet
RUN apt-get upgrade -y --quiet
RUN apt-get install -y build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev libjudy-dev curl git man
RUN apt-get install -y valgrind
RUN yes | unminimize
WORKDIR "/zmap"
COPY ./zmap /zmap/
# by default, uses the main branch. Feel free to check out a commt if you want to play with an older version

RUN cmake .;make -j4; make install
```

## Next Steps
We should investigate cleaning up these pointers.

**Comment by dadrian** [comment]
For what it's worth, we did this intentionally. As long as the memory usage doesn't grow significantly during send, it doesn't matter if we never free our global structures. I know for sure the output filter structure has no free method.

**Comment by phillip-stephens** [comment]
@dadrian That's fair, I just checked with `--max-targets` of 100, 10k, and 100k and didn't see any scaling of un-freed memory. I'll close this issue!
