### ISSUE TITLE
Problem with -P option in DNS module

### ISSUE THREAD

**Issue by BoningZ** [zmap/zmap#746]
> Notice: Please don't file a bug report for questions on how to use ZMap, etc. Check out our [Resources](https://github.com/zmap/zmap/tree/main#resources) section for FAQ and feel free to chime in on [Github Discussions](https://github.com/zmap/zmap/discussions) if you're still unclear and we'll be happy to assist!

**Describe the bug**
I encountered an issue when using the -P option with the DNS module in zmap. It seems that the option is not applicable for the DNS module, but it gives the following error message:
```
[WARN] blocklist: ZMap is currently using the default blocklist located at /etc/zmap/blocklist.conf. By default, this blocklist excludes locally scoped networks (e.g., 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blocklist by editing the default ZMap configuration at /etc/zmap/blocklist.conf. If you have modified the default blocklist, you can ignore this message.
[FATAL] dns: Invalid probe args. Format: "A,google.com" or "A,google.com;A,example.com"
```

**CLI Arguments**
Please paste your ZMap invocation below

```
zmap -p 53 -P 10 --probe-module=dns --probe-args="A,example.com" -B 400K --output-filter="" -O json -o logfile.json 
```

**Expected behavior**
The -P option should not be applicable for the DNS module, or there should be proper documentation indicating that it is not supported.

**Environment:**
 - OS:  Ubuntu 22.04

**Comment by phillip-stephens** [comment]
Hey @BoningZ, thanks for reporting this issue. I'm able to reproduce on my machine and am taking a look!
