### ISSUE TITLE
Unreliable hitrate checking IPs.

### ISSUE THREAD

**Issue by Outcalled** [zmap/zmap#747]
> Notice: Please don't file a bug report for questions on how to use ZMap, etc. Check out our [Resources](https://github.com/zmap/zmap/tree/main#resources) section for FAQ and feel free to chime in on [Github Discussions](https://github.com/zmap/zmap/discussions) if you're still unclear and we'll be happy to assist!

**Describe the bug**
Using ZMap to search the following IPs for all open ports, I am getting barely any valid results. Whilst switching to masscan it works just fine. Any ideas?

(Masscan does not support multi-threading like ZMap so it's painfully slow to use, looking to make ZMap work)

**CLI Arguments**
Please paste your ZMap invocation below

```
zmap -p 0-65535 -I "ips.txt" -o "save.txt" -B 10G
```

**Example Target IP**

Small list, checking 442k IPs.

187.190.144.41
200.71.109.253
177.239.36.114
177.240.145.117
200.24.139.237
187.251.215.93
187.139.175.247
190.87.170.239
181.118.154.98
187.149.251.229

**Expected behavior**
Higher hitrate like on masscan.

**Environment:**
 - OS: Ubuntu server 22.04
 - Version: zmap-4.0.0-RC1

**Additional context**
Don't know if it's just how ZMap works or I did something wrong.

**Comment by phillip-stephens** [comment]
Hey @Outcalled, thanks for raising this issue! Sorry you didn't get the hit-rate you were expecting. 

Can you provide a bit more details so I can triage this? Specifically:
- What hit rate did you observe with ZMap? When I just ran a test with your list of IPs, I got a hit-rate of `9.87%` with the small list you provided.
    - Can you attach your input list of IPs?
- What hit-rate did you observe with `masscan`/did you expect to get with ZMap and please provide what you ran to get that hit-rate.
- Can you describe the networking IRT the Ubuntu Server 22.04? What's the bandwidth available to it, any firewalls in between you and your ISP,....

Without knowing what your expected hit-rate is compared to observed, I won't be able to identify if this is a ZMap issue or something with your setup.

**Comment by Outcalled** [comment]
No firewalls seem to be set, 10 GB bandwidth. I was getting 0.00% hitrate on zmap, maybe my configuration is wrong? What build did you use and config?

**Comment by Outcalled** [comment]
Hitrate on masscan I have no idea as it doesn't really tell, but it's extremely big.

**Comment by Outcalled** [comment]
I think I figured out the issue, zmap is just worse for multi-port checking because it does not check the same IP 65k times, it just checks for 1 open port and that's it. Masscan is superior <3

**Comment by zakird** [comment]
This is not how ZMap works, but I don't get the sense you're looking to productively engage here, so I'm going to close this issue. I'm glad you were able to do what you needed with Masscan.
