### ISSUE TITLE
zmap: unrecognized option '--ipv6-target-file=addresses1.txt

### ISSUE THREAD

**Issue by Hzwords** [zmap/zmap#754]
hello,Why do I get the following error when I run the command:

map --probe-module=icmp6_echoscan --ipv6-target-file=addresses1.txt --output-file=result.txt --ipv6-source-ip=2001:250:xxxx --bandwidth=10M --cooldown-time=4

zmap: unrecognized option '--ipv6-target-file=addresses1.txt'

**Comment by phillip-stephens** [comment]
Hey @Hzwords! ZMap doesn't support `IPv6`. The flag you're using (`--ipv6-target-file`) I don't see documented in any of our `--help` or manpages, and isn't supported.
Closing since we don't support this use case, unfortunately.
