### ISSUE TITLE
Kali Linux - ZMap no longer in package manager

### ISSUE THREAD

**Issue by 0martheone** [zmap/zmap#762]
When ever I type sudo apt install zmap I get "unable to locate package zmap"

**Comment by phillip-stephens** [comment]
What OS and version are you using? Ex: `Ubuntu 18.04`

**Comment by 0martheone** [comment]
I'm using the latest version of kali linux

**Comment by phillip-stephens** [comment]
Looks like `ZMap` was removed from the Kali Linux [package manager](https://pkg.kali.org/pkg/zmap) earlier this month. Kali Linux isn't presently one of our core supported OS's so we don't maintain it in the package manager. I'd follow the build-from-source instructions available [here](https://github.com/zmap/zmap/blob/main/INSTALL.md) for Debian-based distros. 

Moving forward, we're planning on a new ZMap release version soon and I'll be sure to get it back in the Kali Linux package manager at that point. Leaving this issue open and I'll close when its installable from the package manager again.

**Comment by zakird** [comment]
Looks like this was addressed on 1/31/24.
