### ISSUE TITLE
DNS probe module: let user set recursion desired bit

### ISSUE THREAD

**Issue by gutjuri** [zmap/zmap#763]
Hello, I would like to do DNS probes that have the dns_rd bit set to 0. Currently, it is always set to 1 (see https://github.com/zmap/zmap/blob/main/src/probe_modules/module_dns.c#L190).

I have make a fork of the project in which I've changed this value, however, this means that I have to recompile each time I want to change the value of this bit. Instead, I had ther idea to make this configurable to the user and i wanted to ask you if that would be a desirable change to zmap in your opinion. I'd offer to you to implement this change, however, I am not yet sure on how exactly to realize it. For example, it is conceivable to change the syntax to the value of `--probe-args`. Currently. users can specify questions like `--probe-args="A,google.com;A,example.org"`. I can imagine allowing e.g. `--probe-args="A,google.com;A,example.org;rd"` to explicitly desire recursion and e.g. `--probe-args="A,google.com;A,example.org;nrd"` to explicitly set this bit to 0. 

Do you think that this would be a worthwhile change to the project? Or do you see this change breaking backwards-compatibility? I'd be thankful for any feedback.

**Comment by zakird** [comment]
We could also add a new "probe-type" that's something like "A:rn". It's all a bit kludgy since we're passing it in via a string we're parsing in C, but I'm supportive. It would be nice to do it in a way that's backwards compatible if we can (e.g., if not specific, it still works and has the same behavior as today).

**Comment by gutjuri** [comment]
> We could also add a new "probe-type" that's something like "A:rn". It's all a bit kludgy since we're passing it in via a string we're parsing in C, but I'm supportive. It would be nice to do it in a way that's backwards compatible if we can (e.g., if not specific, it still works and has the same behavior as today). Any chance that you'd be willing to submit a PR that adds the proposed functionality?

I have submitted a Draft PR under #764. I am not sure whether or not more documentation needs to be updated.

**Comment by zakird** [comment]
Thanks for doing that!! Left some notes on help on that PR!
