### ISSUE TITLE
CPU USAGE

### ISSUE THREAD

**Issue by neginsadeghi** [zmap/zmap#768]
> Notice: Please don't file a bug report for questions on how to use ZMap, etc. Check out our [Resources](https://github.com/zmap/zmap/tree/main#resources) section for FAQ and feel free to chime in on [Github Discussions](https://github.com/zmap/zmap/discussions) if you're still unclear and we'll be happy to assist!

**Describe the bug**
I think the CPU usage of zmap is so much high in compare of what it is doing, I've run it with sharding, threads in different values but CPU load is still so much high!

**CLI Arguments**
Please paste your ZMap invocation below

 time ./zmap -q --disable-syslog -T 8 -p 80 -N 1000 -B 10000M  --shards 10 --shard 1 --seed 1000

 time ./zmap -q --disable-syslog -T 8 -p 80 -N 1000 -B 10000

![image](https://github.com/zmap/zmap/assets/85784596/b376146e-b121-4541-86e1-cbc2e0b0f26b)

**Expected behavior**
please give me instructions to run it with high speed and accuracy in less CPU load 

**Environment:**
 - OS:Ubuntu Server 18.04

**Comment by zakird** [comment]
@phillip-stephens would be willing to add a question to the FAQ about this? I'll also note that if you send at a low packet rate, then ZMap does sleep between packets, but this would have to be at a rate far, far below 10gbps.

**Comment by phillip-stephens** [comment]
@zakird Yeah of course, that's a good call. I'll add those details to the FAQ page and close this ticket.

I will say, even lowering the `-B/--bandwidth` to `1M`, the core the send thread is pinned to is still maxed at 100% utilization. Not sure if it's a priority/large enough use-case to worry about CPU utilizations at low send rates, but might be some optimization to be done here. If you think I should look into it, I'll update the issue.

`htop` 
<img width="1289" alt="image" src="https://github.com/zmap/zmap/assets/23459798/1eccc9ef-ff7d-42b0-83e9-dbfd2313253e">
Command - `./src/zmap  -p 80 -o "output.csv" 171.67.70.0/2 --max-runtime=10 -c 2 -B 1M --sender-threads=1 -v 5`

**Comment by phillip-stephens** [comment]
[FAQ](https://github.com/zmap/zmap/wiki/FAQ) has been updated.

**Comment by neginsadeghi** [comment]
Thanks for your answer, I want to scan as fast as possible about 256 IP addresses ( a /24 subnet ) with the least CPU utilization 

here is my command to simulate that: 

./zmap -q --disable-syslog -T 1 -p 80 -B 1000M -c 2 -N 256

is there anything else that I could set on command that It would use less CPU time ?

**Comment by phillip-stephens** [comment]
Really only one last suggestion. As I mentioned, we start 1+ (1 in your command) sender threads, 1 receiving thread, 1 monitoring thread. You can use the `--cores` flag to tell ZMap what cores it should pin to. By only giving it a single core: a) the send performance shouldn't really be degraded (especially only scanning 256 IP's) and b) you'll at MOST be loading a single core. That core will be loaded to 100%, but only that core will get any load.

`zmap -o "output.csv" -p 80   -c 2 -B 1G --sender-threads=1 -v 5 --cores=0`
