### ISSUE TITLE
-X Option doesn't get any hits on Ubuntu

### ISSUE THREAD

**Issue by phillip-stephens** [zmap/zmap#821]
> Notice: Please don't file a bug report for questions on how to use ZMap, etc. Check out our [Resources](https://github.com/zmap/zmap/tree/main#resources) section for FAQ and feel free to chime in on [Github Discussions](https://github.com/zmap/zmap/discussions) if you're still unclear and we'll be happy to assist!

**Describe the bug**
ZMap isn't getting any hits on an Ubuntu VM when only sending IP packets

**CLI Arguments**
`sudo ./src/zmap -p 80 -N 5 -X -i enp0s8 -T 1`
or
`sudo ./src/zmap -p 80 -N 5 -X -T 1`

**Expected behavior**
ZMap should scan until it gets 5 hits before terminating.

**Environment:**
 - OS: Ubuntu Server 23.10
 - Version: Github HEAD

**Additional context**
```
$ sudo ./src/zmap -p 80 -N 5 -X -i enp0s8 -T 1
Mar 14 17:49:02.371 [INFO] zmap: By default, ZMap will output the unique IP addresses of hosts that respond successfully (e.g., SYN-ACK packet). This is equivalent to running ZMap with the following flags: --output-module=csv --output-fields=saddr --output-filter='success=1 && repeat=0' --no-header-row. If you want all responses, explicitly set an output module or set --output-filter="".
Mar 14 17:49:02.371 [INFO] dedup: Response deduplication method is full
Mar 14 17:49:02.415 [INFO] recv: duplicate responses will be excluded from output
Mar 14 17:49:02.415 [INFO] recv: unsuccessful responses will be excluded from output
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 10361 10.4 Kp/s (10.0 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:02 0%; send: 20361 10.00 Kp/s (10.0 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:03 0%; send: 30363 10.0 Kp/s (10.0 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:04 0%; send: 40367 10.0 Kp/s (10.0 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:05 0% (4d23h left); send: 50366 10.00 Kp/s (10.0 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
```

**Comment by phillip-stephens** [comment]
I'll work backwards down the `main` branch commit log and see if there was a point in which this didn't happen on the lab VM. Also would be good to add an `--iplayer` test to the Integration suite.

**Comment by phillip-stephens** [comment]
So went back to December (commit `02e2`) and it still wasn't working. I'm almost positive in the past 3 months I've used the `-X` flag successfully, so not entirely sure what's up. Dumping the packets sent:
With `-X` (ZMap only creates IP layer packets)
```
18:41:23.784900 enp0s8 Out ifindex 3 52:54:00:41:ab:f0 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 255, id 22643, offset 0, flags [none], proto TCP (6), length 60)
    171.67.71.209.55992 > 1.1.1.0.80: Flags [S], cksum 0x73c4 (correct), seq 3243772287, win 65535, options [mss 1460,sackOK,TS val 1710441683 ecr 2483812979,nop,wscale 7], length 0
    ```
Without `-X` (ZMap generates Ethernet header as well)
```
18:41:39.180904 enp0s8 Out ifindex 3 52:54:00:41:ab:f0 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 255, id 3391, offset 0, flags [none], proto TCP (6), length 60)
    171.67.71.209.43430 > 1.1.1.0.80: Flags [S], cksum 0x3734 (correct), seq 254851001, win 65535, options [mss 1460,sackOK,TS val 1710441699 ecr 0,nop,wscale 7], length 0
    ```
    
    
    I don't see any difference between these two packets except for the IP ID, which is randomized now and the `cksum`. I'll keep investigating.

**Comment by phillip-stephens** [comment]
Note: Seems to be reproducible on a Digital Ocean droplet.

**Comment by droe** [comment]
I noticed this too but thought it's some Linux quirk, guess I was wrong :(  I suspect the gateway MAC addr lookup code: When using `--iplayer` on Linux, I see packets with destination MAC address of 00:00:00:00:00:00, and -v 5 has this:

```
Mar 14 20:19:23.223 [DEBUG] send: gateway MAC address 00:00:00:00:00:00
```

When omitting `--iplayer`, the gateway MAC addr is picked up correctly.

**Comment by droe** [comment]
This seems to fix it at least for Ethernet, untested w/VPN interfaces:

```
diff --git a/src/socket-linux.c b/src/socket-linux.c
index b1710c7..c1e2208 100644
--- a/src/socket-linux.c
+++ b/src/socket-linux.c
@@ -20,7 +20,7 @@ sock_t get_socket(UNUSED uint32_t id)
 {
        int sock;
        if (zconf.send_ip_pkts) {
-               sock = socket(AF_PACKET, SOCK_DGRAM, htons(ETH_P_ALL));
+               sock = socket(PF_INET, SOCK_RAW, IPPROTO_RAW);
        } else {
                sock = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL));
        }
```
