### ISSUE TITLE
Issue for scanning port 25

### ISSUE THREAD

**Issue by developeraether** [zmap/zmap#885]
Hi

zmap -p 25 

I just used this command and it didn't gave result. Is that prevention of scanning mail servers for malicious usage? I am just wondered. Anyway, maybe that needs some configuration too. I need help. I am just data collector.

Best regards

**Comment by phillip-stephens** [comment]
Hey @developeraether! Thanks for reaching out.

So on an `Ubuntu 23.10` host I'm able to run ZMap on port 25 and get results:
```
$ sudo zmap -p 25 -B 1M -n 1000
...
 0:00 0%; send: 2 1 p/s (56 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
202.11.171.66
27.126.181.250
...
 0:09 100% (0s left); send: 1000 done (1.32 Kp/s avg); recv: 2 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.20%
```

So I can better assist you, can you provide the following:

- What OS you're using
- What version of ZMap you're using and how you installed it
- Confirm that you're running ZMap with `zmap -p 25`
- Can you scan on any other ports? (`zmap -p 80`)?

**Comment by phillip-stephens** [comment]
I'm going to close this issue due to inactivity. If anyone runs into this again or would like support, please re-open and I'll take a look!
