### ISSUE TITLE
Support for Scanning with Multiple IPs from a /24 Subnet Using PF_RING ZC

### ISSUE THREAD

**Issue by miladtempaccount** [zmap/zmap#893]
Hello ZMap Team,

Use Case
I am currently working on a project where I need to scan the entire internet very quickly using a /24 subnet (i.e., 254 IP addresses). To achieve this, I am using PF_RING ZC, which allows high-performance packet processing on a 10Gbps port. However, I’ve encountered an issue with ZMap where it only allows me to specify a single source IP in the command line using the --source-ip option.

Problem
Given that I have 254 IP addresses available, I want to distribute the scanning load across all of these IPs to avoid getting blocked quickly and to maximize the scanning speed. Currently, ZMap requires passing a single IP address, which limits this functionality.

Feature Request
Could you please add support for specifying a range or list of source IP addresses in the command line (e.g., --source-ip 192.168.1.1-192.168.1.254) or allow rotating through a list of IP addresses during the scanning process? This would greatly enhance the flexibility and performance of ZMap when used with a large pool of IP addresses.

Question: PF_RING ZC Compatibility
Additionally, I am using PF_RING ZC for its zero-copy capabilities. Could you confirm whether PF_RING ZC can be used with all existing tools, or does it require specific software-side support? Given that PF_RING ZC can be assigned to a separate interface, can we simply pass this interface to other tools, or does the software need explicit support for this type of interface?

Thank you for your support and for the incredible tool that is ZMap. Looking forward to your guidance on these issues.

Best regards,

**Comment by phillip-stephens** [comment]
Hey @miladtempaccount! Thanks for your detailed GH issue. I don't presently have access to a machine with `PF_RING ZC` configured, so I can't confirm this works for your use case. However, ZMap has ` -S, --source-ip=ip|range      Source address(es) for scan packets`.

I tried it out and confirm it works at least with non-PF_RING usage.

```
~/zmap-dev on  main! ⌚ 13:46:01
$ ./src/zmap -S 171.67.71.209-171.67.71.216 -p 80 -n 5 --dryrun
Sep 19 13:46:10.322 [INFO] zmap: By default, ZMap will output the unique IP addresses of hosts that respond successfully (e.g., SYN-ACK packet). This is equivalent to running ZMap with the following flags: --output-module=csv --output-fields=saddr --output-filter='success=1 && repeat=0' --no-header-row. If you want all responses, explicitly set an output module or set --output-filter="".
Sep 19 13:46:10.322 [INFO] dedup: Response deduplication method is full
Sep 19 13:46:10.325 [WARN] zmap: too few targets relative to senders, dropping to one sender
Sep 19 13:46:10.325 [INFO] send: dryrun mode -- won't actually send packets
tcp { source: 45335 | dest: 80 | seq: 1352151182 | checksum: 0X75EF }
ip { saddr: 171.67.71.211 | daddr: 243.81.224.42 | checksum: 0XC8C8 }
eth { ---}
------------------------------------------------------
tcp { source: 56646 | dest: 80 | seq: 249281168 | checksum: 0X40ED }
ip { saddr: 171.67.71.215 | daddr: 212.7.191.254 | checksum: 0XA524 }
eth { --- }
------------------------------------------------------
tcp { source: 36769 | dest: 80 | seq: 2128693618 | checksum: 0X5477 }
ip { saddr: 171.67.71.210 | daddr: 174.93.32.225 | checksum: 0XB12A }
eth { --- }
------------------------------------------------------
tcp { source: 43936 | dest: 80 | seq: 2632029279 | checksum: 0XA478 }
ip { saddr: 171.67.71.209 | daddr: 230.225.19.112 | checksum: 0X6A13 }
eth { --- }
------------------------------------------------------
tcp { source: 38390 | dest: 80 | seq: 560082503 | checksum: 0X5506 }
ip { saddr: 171.67.71.214 | daddr: 99.107.221.149 | checksum: 0XF03F }
eth { --- }
```

Does this address your need?
