### ISSUE TITLE
Fails to correctly determine default interface on Fedora

### ISSUE THREAD

**Issue by ppannuto** [zmap/zmap#91]
**Running Without Root:**

```
Nov 25 13:18:38.012 [INFO] zmap: started
Nov 25 13:18:38.025 [FATAL] zmap: could not detect default network interface (e.g. eth0). Try running as root or setting interface using -i flag.
```

**Running as Root:**

```
Nov 25 13:18:45.075 [INFO] zmap: started
Nov 25 13:18:45.199 [ERROR] get-gw: ioctl failure: No such device
Nov 25 13:18:45.199 [FATAL] zmap: could not detect default IP address for for usbmon1. Try specifying a source address (-S).
```

`usbmon1` is not a valid interface for this machine. Running with `-ip2p1` (the correct interface) works correctly.

**ifconfig output:**

```
$ ifconfig 
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 12  bytes 1124 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 1124 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

p2p1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet ANONYMIZED  netmask 255.255.255.0  broadcast ANONYMIZED
        inet6 ANONYMIZED  prefixlen 64  scopeid 0x20<link>
        inet6 ANONYMIZED  prefixlen 64  scopeid 0x0<global>
        ether ANONYMIZED  txqueuelen 1000  (Ethernet)
        RX packets 63972  bytes 88285317 (84.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13434  bytes 1697321 (1.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by eegilbert** [comment]
This still occurs in centos 7.1.1503:

[root@fry ~]# zmap -p 53 8.8.8.8/32
Nov 02 21:58:44.352 [WARN] zmap: too few targets relative to senders, dropping to one sender
Nov 02 21:58:44.398 [FATAL] get-iface-ip: ioctl failure: No such device

[root@fry ~]# zmap -p 53 -i eno16780032 8.8.8.8/32
Nov 02 21:59:37.272 [WARN] zmap: too few targets relative to senders, dropping to one sender
Nov 02 21:59:37.273 [INFO] zmap: output module: csv
Nov 02 21:59:37.273 [INFO] csv: no output file selected, will use stdout
 0:00 0%; send: 1 done (48 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:00 0%; send: 1 done (48 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
8.8.8.8
 0:01 13%; send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:02 25%; send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:03 38%; send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:04 50%; send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:05 63% (3s left); send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:06 75% (2s left); send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:07 88% (1s left); send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
 0:08 100% (0s left); send: 1 done (48 p/s avg); recv: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00%
Nov 02 21:59:46.304 [INFO] zmap: completed

**Comment by cicku** [comment]
centos is based on f19. You probably need to file a ticket against RHEL 7 or CentOS 7.
