### ISSUE TITLE
There are no response when using zmapv6 with icmp6echo probe 

### ISSUE THREAD

**Issue by Abintong** [zmap/zmap#915]
for a active IPv6 Address Set
I use ZMAPv6 with icmp6ehcscan probe and ping6.
The former has not response ,but the later has?      
Do you have ever meet this problem?
![image](https://github.com/user-attachments/assets/605b4a5b-8689-4860-8eef-bb0a1ce5a408)

**Comment by phillip-stephens** [comment]
ZMapv6 isn't maintained by us. I'd open an issue with them!
